import type { Module } from "./types";

export const module4: Module = {
  id: "m4",
  title: "People",
  blurb:
    "Introduce yourself, ask where someone lives, and pick up the tiny pronouns that make conversations personal - me, you, mine, yours.",
  lessons: [
    {
      id: "m4l1",
      title: "What's your name?",
      subtitle: "казвам се, как, Приятно ми е",
      items: [
        {
          type: "note",
          title: "Warm-up",
          body: "Before we learn to introduce ourselves, let's make sure everything from the last module is still running. No new words here - just three sentences from things you already own.",
        },
        {
          type: "exercise",
          prompt: "**The new car is good.**",
          answer: "Новата кола е добра",
          hint: "новата (article rides the adjective) + кола + е + добра (feminine).",
          after: "Adjective agreement, article on the adjective, feminine forms. All working together.",
        },
        {
          type: "exercise",
          prompt: "**He must work today.**",
          answer: "Той трябва да работи днес",
          accept: ["трябва да работи днес"],
          hint: "трябва (frozen) + да + работи (и-family, he-form) + днес.",
        },
        {
          type: "exercise",
          prompt: "**Can I have the coffee, please?**",
          answer: "Може ли кафето, моля?",
          hint: "Може ли + кафето (neuter article) + моля.",
          after: "Three for three. You're ready for new ground.",
        },
        {
          type: "note",
          title: "Calling yourself",
          body: "**Казвам** = *I say / I call* - a regular а-family verb, so you already know the endings: казвам, казваш, казва...\n\n**Се** = *oneself*. Put them together:\n\n**Казвам се** = literally 'I call myself' = *my name is*.\n\nAnd one more new word: **как** = *how*. That's all you need.",
          speak: ["Казвам се.", "Как?"],
          he: "**Се** is like Hebrew's reflexive hitpa'el - except it's a separate word rather than a verb-internal pattern.",
          ru: "**Казвам се** maps almost perfectly to Russian 'меня зовут' (or the reflexive 'называюсь'). Same logic, nearly the same word.",
        },
        {
          type: "exercise",
          prompt: "Ask: **What's your name?** (literally: 'How do you call yourself?')",
          answer: "Как се казваш?",
          hint: "как + се + казваш (ти-form of казвам).",
          speak: "Как се казваш?",
          after: "**Как се казваш?** - your first question that can start a real conversation.",
        },
        {
          type: "exercise",
          prompt: "Answer: **My name is Maria.**",
          answer: "Казвам се Мария",
          hint: "Казвам се + the name.",
          speak: "Казвам се Мария.",
        },
        {
          type: "exercise",
          prompt: "**Her name is Maria. She is a student.**",
          answer: "Казва се Мария. Тя е студентка.",
          hint: "казва се = her name is. студентка = student (female, -ка ending).",
        },
        {
          type: "note",
          title: "Nice to meet you",
          body: "**Приятно ми е.** = *Nice to meet you.* Literally something like 'pleasant to-me it-is.'\n\nLearn it as a chunk for now. That little **ми** inside it will make full sense in a couple of lessons.",
          speak: ["Приятно ми е."],
        },
        {
          type: "exercise",
          prompt: "Someone says: Казвам се Петър. Respond with: **Nice to meet you.**",
          answer: "Приятно ми е",
          hint: "The set phrase: Приятно ми е.",
          speak: "Приятно ми е.",
          after: "You just introduced yourself in Bulgarian. Say it out loud a few times - it sticks faster that way.",
        },
        {
          type: "exercise",
          prompt: "Respond: **Nice to meet you, Maria.**",
          answer: "Приятно ми е, Мария",
          hint: "The set phrase + a name.",
        },
        {
          type: "exercise",
          prompt: "Introduce yourself: **My name is Peter. Nice to meet you.**",
          answer: "Казвам се Петър. Приятно ми е.",
          hint: "Казвам се + name. Then Приятно ми е.",
        },
        {
          type: "note",
          title: "The question you'll use every day",
          body: "Point at anything and ask:\n\n**Как се казва това на български?**\n*What is this called in Bulgarian?*\n\n- **това** = this/that\n- **на български** = in Bulgarian\n\nBulgarians love being asked this. Use it shamelessly - it turns every interaction into a free lesson.",
          speak: ["Как се казва това на български?"],
        },
        {
          type: "exercise",
          prompt: "Ask: **What is this called in Bulgarian?**",
          answer: "Как се казва това на български?",
          accept: ["как се казва това на български"],
          hint: "Как се казва + това + на български?",
          after: "Memorize this one sentence and you have a skeleton key to learning outside this course.",
        },
        {
          type: "exercise",
          prompt: "Ask: **What is her name?**",
          answer: "Как се казва?",
          accept: ["Как се казва тя?"],
          hint: "Как + се + казва (he/she form of казвам).",
        },
        {
          type: "exercise",
          prompt: "Someone asks: Как се казваш? Answer: **My name is Peter. I am from Canada.**",
          answer: "Казвам се Петър. Аз съм от Канада.",
          accept: ["Казвам се Петър. От Канада съм."],
          hint: "Казвам се + name. Аз + съм + от + country.",
        },
      ],
    },
    {
      id: "m4l2",
      title: "Where I live",
      subtitle: "живея в София, къде, Как си?",
      items: [
        {
          type: "note",
          title: "A new verb family - same skeleton",
          body: "**Живея** = *I live*. This is an е-family verb, like мога - but tidier:\n\n- **живея** - I live\n- **живееш** - you live\n- **живее** - he/she lives\n\nPlural: живеем, живеете, живеят.\n\nSame person markers you already know (-м/-ш/bare, -ме/-те/-ят). Only the linking vowel changed: а-family has а, и-family has и, е-family has е. Same skeleton, different shirt.",
          speak: ["живея", "живееш", "живее"],
        },
        {
          type: "note",
          title: "In",
          body: "**В** = *in*. One letter, one job:\n\n- **Живея в София.** - I live in Sofia.\n- **Живея в Канада.** - I live in Canada.\n\nBefore words starting with в or ф, it becomes **във** for ease of pronunciation. The same thing happens with с/със later.",
          speak: ["Живея в София.", "Живея в Канада."],
        },
        {
          type: "exercise",
          prompt: "**I live in Sofia.**",
          answer: "Живея в София",
          accept: ["аз живея в София"],
          hint: "живея + в + София.",
        },
        {
          type: "exercise",
          prompt: "**She lives in Canada.**",
          answer: "Тя живее в Канада",
          accept: ["живее в Канада"],
          hint: "тя + живее (she-form) + в + Канада.",
        },
        {
          type: "exercise",
          prompt: "**We live in a big city.**",
          answer: "Живеем в голям град",
          accept: ["ние живеем в голям град"],
          hint: "живеем (we-form) + в + голям (big, masculine) + град (city).",
          after: "голям stays in its bare form because град is masculine. The adjective agreement from last module keeps paying rent.",
        },
        {
          type: "exercise",
          prompt: "**We are from Canada, but we live in Sofia.**",
          answer: "Ние сме от Канада, но живеем в София",
          accept: ["сме от Канада, но живеем в София"],
          hint: "сме (we are) + от + но (but) + живеем (we live).",
        },
        {
          type: "note",
          title: "Where?",
          body: "**Къде** = *where*. It usually leads the sentence:\n\n- **Къде живееш?** - Where do you live?\n- **Къде е хотелът?** - Where is the hotel?\n\nYou've had **тук** (here), **там** (there), and **от** (from). Now you can ask the question that completes the set.",
          speak: ["Къде живееш?", "Къде е хотелът?"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Where do you live?**",
          answer: "Къде живееш?",
          hint: "Къде + живееш?",
          after: "**Къде живееш?** followed by **Живея в...** - you now own the most universal small-talk exchange.",
        },
        {
          type: "exercise",
          prompt: "Ask: **Where is the restaurant?**",
          answer: "Къде е ресторантът?",
          accept: ["къде е ресторанта"],
          hint: "Къде + е + ресторантът (masculine article).",
        },
        {
          type: "exercise",
          prompt: "Ask: **Where does she live?**",
          answer: "Къде живее?",
          accept: ["Къде живее тя?", "Къде тя живее?"],
          hint: "Къде + живее (he/she form of живея).",
        },
        {
          type: "note",
          title: "How are you?",
          body: "Remember **как** from last lesson? Combine it with **си**:\n\n**Как си?** = *How are you?*\n\nAnswers you can already build: **Добре съм.** (I'm well.) **Добре, благодаря.** (Well, thanks.)\n\nAnd one new reflexive verb: **чувствам се** = *I feel* (а-family, same **се** as казвам се).\n\n**Чувствам се добре.** - I feel well.",
          speak: ["Как си?", "Добре съм.", "Чувствам се добре."],
        },
        {
          type: "exercise",
          prompt: "Ask: **How are you?**",
          answer: "Как си?",
          hint: "как + си.",
          speak: "Как си?",
        },
        {
          type: "exercise",
          prompt: "**I feel well.**",
          answer: "Чувствам се добре",
          hint: "чувствам + се + добре.",
          after: "Two reflexive verbs now - казвам се and чувствам се. Same **се**, same behavior.",
        },
        {
          type: "exercise",
          prompt: "Say: **I'm well, thanks.**",
          answer: "Добре съм, благодаря",
          accept: ["Добре, благодаря"],
          hint: "Добре + съм (I am) + благодаря (thanks).",
        },
      ],
    },
    {
      id: "m4l3",
      title: "Me, you, him, her",
      subtitle: "Виждам те. Не те разбирам.",
      items: [
        {
          type: "note",
          title: "The other side of the verb",
          body: "So far you've been the one doing things - *I* want, *you* speak, *she* lives. Now: what about the person on the receiving end?\n\n**Виждам** = *I see* (а-family, predictable). To say *who* you see, stick a tiny pronoun right after the verb. The first one:\n\n- **ме** - me\n\n**Виждаш ме.** - You see me.",
          speak: ["Виждаш ме."],
        },
        {
          type: "exercise",
          prompt: "**You see me.**",
          answer: "Виждаш ме",
          hint: "You see = виждаш (а-family, ти-form). Then me = ме.",
        },
        {
          type: "note",
          title: "You",
          body: "The other side of ме:\n\n- **те** - you (as an object)\n\n**Виждам те.** - I see you.\n\nSame position - right after the verb.",
          speak: ["Виждам те."],
        },
        {
          type: "exercise",
          prompt: "**I see you.**",
          answer: "Виждам те",
          hint: "Verb first, then the pronoun: виждам + те.",
        },
        {
          type: "note",
          title: "Him",
          body: "Third person masculine:\n\n- **го** - him / it (masculine or neuter)\n\n**Виждам го.** - I see him.",
          speak: ["Виждам го."],
        },
        {
          type: "exercise",
          prompt: "**I see him.**",
          answer: "Виждам го",
          hint: "Виждам + го.",
        },
        {
          type: "note",
          title: "Her",
          body: "Third person feminine:\n\n- **я** - her / it (feminine)\n\n**Виждам я.** - I see her.",
          speak: ["Виждам я."],
          ru: "Watch out: Bulgarian **я** means *her* - not 'I' like in Russian (I = аз). This will be confusing at first.",
        },
        {
          type: "exercise",
          prompt: "**I see her.**",
          answer: "Виждам я",
          hint: "her = я, right after the verb.",
        },
        {
          type: "note",
          title: "Clitic placement",
          body: "These small words (ме, те, го, я) are clitics - like съм's family, they **never come first** in the sentence and they hug the verb. When something leads (не, a subject pronoun), they slide in front of the verb:\n\n**Не го виждам.** - I don't see him.\n**Аз те виждам.** - I see you.",
          speak: ["Не го виждам.", "Аз те виждам."],
        },
        {
          type: "exercise",
          prompt: "**I don't see him.**",
          answer: "Не го виждам",
          hint: "Не leads, so го slides in before the verb.",
          after: "Same clitic dance as съм. Не pushes everything forward.",
        },
        {
          type: "exercise",
          prompt: "**She doesn't see him.**",
          answer: "Тя не го вижда",
          accept: ["не го вижда"],
          hint: "тя leads, не pushes го before вижда.",
        },
        {
          type: "note",
          title: "A second verb - and no 'for'",
          body: "**Чакам** = *I wait for* (а-family). Bulgarian swallows the 'for' - you wait *someone* directly:\n\n**Чакам те.** - I'm waiting for you.",
          speak: ["Чакам те."],
        },
        {
          type: "exercise",
          prompt: "**I'm waiting for you.**",
          answer: "Чакам те",
          hint: "чакам + те. No word for 'for'.",
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you see me?**",
          answer: "Виждаш ли ме?",
          hint: "Виждаш ли... then me (ме).",
          after: "Notice how ли and ме coexist: ли follows the verb, then ме tags along at the end.",
        },
        {
          type: "exercise",
          prompt: "**She doesn't see me.**",
          answer: "Тя не ме вижда",
          accept: ["не ме вижда"],
          hint: "тя leads, не pushes ме before the verb: тя не ме вижда.",
          after: "Не + clitic + verb. The clitic stays glued to the verb even with не in front.",
        },
        {
          type: "exercise",
          prompt: "**I'm waiting for her.**",
          answer: "Чакам я",
          hint: "чакам + я (her).",
        },
        {
          type: "exercise",
          prompt: "**I don't see her.**",
          answer: "Не я виждам",
          hint: "Не leads, я goes before виждам.",
        },
        {
          type: "exercise",
          prompt: "**I love you.**",
          answer: "Обичам те",
          hint: "Обичам + те.",
          after: "**Обичам те.** Two words. No decoration needed.",
        },
        {
          type: "exercise",
          prompt: "**I'm not waiting for him.**",
          answer: "Не го чакам",
          hint: "Не leads, го goes before чакам.",
        },
        {
          type: "note",
          title: "Four small words",
          body: "ме, те, го, я - four tiny words that never lead a sentence and always stay near the verb. Their placement will start to *feel* right long before you can explain it.\n\nNext: the plural set.",
        },
      ],
    },
    {
      id: "m4l4",
      title: "Us, you all, them",
      subtitle: "ни, ви, ги",
      items: [
        {
          type: "note",
          title: "Warm-up",
          body: "Before the plural pronouns, let's make sure the singular ones are running.",
        },
        {
          type: "exercise",
          prompt: "**I see him.**",
          answer: "Виждам го",
          hint: "Виждам + го.",
        },
        {
          type: "exercise",
          prompt: "**I don't see her.**",
          answer: "Не я виждам",
          hint: "Не leads, so я slides in before the verb.",
          after: "Good. Same clitic dance. Now the plural set.",
        },
        {
          type: "note",
          title: "Us",
          body: "The plural pronouns work exactly like the singular ones. Same positions, same rules. First:\n\n- **ни** - us\n\n**Виждаш ли ни?** - Do you see us?",
          speak: ["Виждаш ли ни?"],
        },
        {
          type: "exercise",
          prompt: "**She sees us.**",
          answer: "Тя ни вижда",
          accept: ["вижда ни"],
          hint: "With тя up front, ни slips in before the verb: тя + ни + вижда.",
        },
        {
          type: "exercise",
          prompt: "**He doesn't see us.**",
          answer: "Той не ни вижда",
          accept: ["не ни вижда"],
          hint: "Не leads, so ни goes before вижда.",
          after: "Same clitic placement as the singular: не + pronoun + verb.",
        },
        {
          type: "exercise",
          prompt: "**He is waiting for us.**",
          answer: "Чака ни",
          accept: ["той ни чака"],
          hint: "чака (he/she-form of чакам) + ни.",
        },
        {
          type: "note",
          title: "You all",
          body: "- **ви** - you all (plural/formal object)\n\n**Чакам ви.** - I'm waiting for you (all).",
          speak: ["Чакам ви."],
        },
        {
          type: "exercise",
          prompt: "**I don't understand you (all).**",
          answer: "Не ви разбирам",
          hint: "Не leads, so ви goes before разбирам.",
        },
        {
          type: "exercise",
          prompt: "**I'm waiting for you (all).**",
          answer: "Чакам ви",
          hint: "чакам + ви. Same position as те.",
        },
        {
          type: "exercise",
          prompt: "**She sees you (all).**",
          answer: "Тя ви вижда",
          accept: ["вижда ви"],
          hint: "тя leads, ви goes before вижда.",
        },
        {
          type: "note",
          title: "Them",
          body: "- **ги** - them\n\n**Виждам ги.** - I see them.\n\nThat completes the set: ме, те, го, я, ни, ви, ги. Seven tiny words, same rules for all of them.",
          speak: ["Виждам ги."],
        },
        {
          type: "exercise",
          prompt: "**I don't understand them.**",
          answer: "Не ги разбирам",
          hint: "Не leads, so ги goes before разбирам.",
        },
        {
          type: "exercise",
          prompt: "**She sees them.**",
          answer: "Тя ги вижда",
          accept: ["вижда ги"],
          hint: "тя leads, ги goes before вижда.",
          after: "Same pattern as тя ни вижда. The plural pronouns behave identically to the singular ones.",
        },
        {
          type: "exercise",
          prompt: "**I'm waiting for them.**",
          answer: "Чакам ги",
          hint: "чакам + ги.",
        },
        {
          type: "exercise",
          prompt: "**I don't understand you.** (singular)",
          answer: "Не те разбирам",
          hint: "Singular you = те. Не goes first, so те comes before разбирам.",
          after: "Say it kindly. Bulgarians will slow down and love you for trying.",
        },
        {
          type: "exercise",
          prompt: "**She understands me.**",
          answer: "Тя ме разбира",
          accept: ["разбира ме"],
          hint: "With тя up front, ме slips in before the verb.",
        },
        {
          type: "note",
          title: "Seven small words, strict habits",
          body: "ме, те, го, я, ни, ви, ги - seven small words that never lead a sentence and always stay near the verb. Their placement will start to *feel* right long before you can explain it. That's normal. It's how natives run it too.",
        },
      ],
    },
    {
      id: "m4l5",
      title: "Mine and yours",
      subtitle: "колата ми, майка ми, кафе с мляко",
      items: [
        {
          type: "note",
          title: "Warm-up",
          body: "Let's make sure those object pronouns are settling in before we move on.",
        },
        {
          type: "exercise",
          prompt: "**I'm waiting for her.**",
          answer: "Чакам я",
          hint: "чакам + я (her).",
        },
        {
          type: "exercise",
          prompt: "**I don't understand them.**",
          answer: "Не ги разбирам",
          hint: "Не leads, so ги goes before разбирам.",
          after: "Good. Those pronouns are working. Now - ownership.",
        },
        {
          type: "note",
          title: "'s and 'of' - both are на",
          body: "When one noun owns another, **на** does all the work:\n\n**колата на Мария** - Maria's car (literally 'the-car of Maria')\n\nNo apostrophe-s, no cases. Just на + the owner.",
          speak: ["колата на Мария"],
          he: "Same word order as של: האוטו **של מריה** = колата **на Мария**. Noun first, owner after.",
          ru: "This replaced the entire Russian genitive case: машина Марии -> колата на Мария. Preposition + unchanged noun. One less declension to carry.",
        },
        {
          type: "exercise",
          prompt: "**Peter's car** (Peter = Петър)",
          answer: "колата на Петър",
          hint: "the-car + на + the name.",
        },
        {
          type: "exercise",
          prompt: "**Maria's house**",
          answer: "къщата на Мария",
          hint: "the-house + на + the name.",
        },
        {
          type: "exercise",
          prompt: "**The coffee is Peter's.**",
          answer: "Кафето е на Петър",
          hint: "кафето (neuter article) + е + на + the name.",
        },
        {
          type: "note",
          title: "My",
          body: "For *your own* stuff, even shorter - a tiny word after the definite noun:\n\n- **ми** - my\n\n**колата ми** - my car (literally 'the-car to-me')",
          speak: ["колата ми"],
        },
        {
          type: "exercise",
          prompt: "**my car**",
          answer: "колата ми",
          hint: "Definite noun + ми: колата + ми.",
        },
        {
          type: "exercise",
          prompt: "**my house**",
          answer: "къщата ми",
          hint: "the-house + ми.",
        },
        {
          type: "exercise",
          prompt: "**My coffee is good.**",
          answer: "Кафето ми е добро",
          hint: "кафето (neuter article) + ми + е + добро (neuter).",
        },
        {
          type: "note",
          title: "Your",
          body: "Same pattern, different person:\n\n- **ти** - your\n\n**къщата ти** - your house",
          speak: ["къщата ти"],
          he: "Same word order as של: הבית **שלך** = къщата **ти**. Noun first, owner after.",
        },
        {
          type: "exercise",
          prompt: "**your house**",
          answer: "къщата ти",
          hint: "Definite noun + ти: къщата + ти.",
        },
        {
          type: "exercise",
          prompt: "**Your car is new.**",
          answer: "Колата ти е нова",
          hint: "колата + ти + е + нова (feminine).",
        },
        {
          type: "note",
          title: "His",
          body: "One more possessive:\n\n- **му** - his\n\n**къщата му** - his house",
          speak: ["къщата му"],
        },
        {
          type: "exercise",
          prompt: "**his house**",
          answer: "къщата му",
          hint: "the-house + му.",
        },
        {
          type: "exercise",
          prompt: "**His car is good.**",
          answer: "Колата му е добра",
          hint: "колата + му + е + добра (feminine).",
        },
        {
          type: "note",
          title: "Her (possessive)",
          body: "- **ѝ** - her (that accent mark just separates it from и 'and' in writing - typing plain и is fine)\n\n**колата ѝ** - her car",
          speak: ["колата ѝ"],
        },
        {
          type: "exercise",
          prompt: "**her car**",
          answer: "колата ѝ",
          accept: ["колата и"],
          hint: "the-car + ѝ.",
        },
        {
          type: "exercise",
          prompt: "**Her house is big.**",
          answer: "Къщата ѝ е голяма",
          accept: ["Къщата и е голяма"],
          hint: "къщата + ѝ + е + голяма (feminine of голям).",
        },
        {
          type: "note",
          title: "Family drops the article",
          body: "With close family, the article drops away. One new noun to show this:\n\n**Майка** = *mother* (feminine).\n\n- **майка ми** - my mother (not *майката ми*)\n\nThis is a special rule - only close family words skip 'the' before the possessive.",
          speak: ["майка ми"],
          ru: "**Майка** = *mother* in Bulgarian. In Russian, майка is an undershirt. Possibly the most important false friend in the language.",
        },
        {
          type: "exercise",
          prompt: "**my mother**",
          answer: "майка ми",
          hint: "Close family drops 'the' - just майка + ми.",
        },
        {
          type: "exercise",
          prompt: "**your mother**",
          answer: "майка ти",
          hint: "Close family drops 'the' - just майка + ти.",
        },
        {
          type: "note",
          title: "Father",
          body: "One more family noun: **баща** = *father*.\n\n**Баща** ends in -а but is masculine - same kind of exception you've seen before.\n\n**баща ми** - my father (again, no article with close family).",
          speak: ["баща ми"],
        },
        {
          type: "exercise",
          prompt: "**My father lives in Sofia.**",
          answer: "Баща ми живее в София",
          hint: "баща ми (no article) + живее + в + София.",
          after: "No article on баща, живее from last lesson, в from this module. Everything connecting.",
        },
        {
          type: "exercise",
          prompt: "**His father is a student.**",
          answer: "Баща му е студент",
          hint: "баща му (no article, family) + е + студент.",
        },
        {
          type: "note",
          title: "With",
          body: "**С** = *with*. Another one-letter preposition:\n\n- **кафе с мляко** - coffee with milk\n- **чай с мляко** - tea with milk\n\nBefore consonant clusters it becomes **със** - same pattern as в/във.",
          speak: ["кафе с мляко"],
        },
        {
          type: "exercise",
          prompt: "**I want coffee with milk, please.**",
          answer: "Искам кафе с мляко, моля",
          hint: "Искам + кафе с мляко + моля.",
          after: "You can order coffee exactly how you want it now.",
        },
        {
          type: "exercise",
          prompt: "**I want tea with milk, please.**",
          answer: "Искам чай с мляко, моля",
          hint: "Искам + чай с мляко + моля.",
        },
        {
          type: "exercise",
          prompt: "**I live with my mother.**",
          answer: "Живея с майка ми",
          accept: ["аз живея с майка ми"],
          hint: "живея + с + майка ми (no article for family).",
        },
        {
          type: "exercise",
          prompt: "**My mother is from Germany.** (Germany = Германия)",
          answer: "Майка ми е от Германия",
          hint: "майка ми (no article) + е + от + Германия.",
          after: "на for someone else's things, ми/ти/му/ѝ after the noun for yours, family without 'the', с for company. Four small patterns, and people start belonging to each other.",
        },
        {
          type: "exercise",
          prompt: "**I see your car.**",
          answer: "Виждам колата ти",
          hint: "колата + ти (your). Not те - that would mean 'I see you'.",
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you see my car?**",
          answer: "Виждаш ли колата ми?",
          hint: "колата + ми = my car.",
        },
        {
          type: "exercise",
          prompt: "**I'm waiting for your mother.**",
          answer: "Чакам майка ти",
          hint: "чакам + майка ти - family drops 'the'.",
        },
      ],
    },
  ],
};
