import type { Module } from "./types";

export const module3: Module = {
  id: "m3",
  title: "4. Shapes and descriptions",
  blurb:
    "Can, should, please, thank you - and the aha moment when you notice the pattern hiding in every noun ending.",
  lessons: [
    {
      id: "m3l1",
      title: "What you can already say",
      subtitle: "One new word, no new rules",
      items: [
        {
          type: "note",
          title: "Breathe",
          body:
            "No new grammar in this lesson. One new word, and you'll meet it halfway through. Everything else is built from pieces you already own - you're just going to see how many sentences fall out when you recombine them.\n\nThis should feel easy. If it does, that's because you actually know things.",
        },
        {
          type: "exercise",
          prompt: "How would you say: **I want to learn Macedonian**?",
          answer: "Сакам да учам македонски",
          accept: ["јас сакам да учам македонски"],
          hint: "сакам + да + учам + македонски - all words you know.",
          after: "Two verbs stitched with да, both ending in -м because both are 'I'. You didn't even hesitate, did you?",
          reviews: ["да-subjunctive", "verb-а-group", "сакам", "учам", "verb-и-group", "македонски", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**She doesn't have a car.**",
          answer: "Таа нема кола",
          accept: ["нема кола"],
          hint: "The fused 'don't have' verb - немам. Her form?",
          after: "Таа нема кола. Three words, and you reached for нема without thinking about it.",
          reviews: ["немам-fused", "pronoun-subject", "немам", "кола"],
        },
        {
          type: "exercise",
          prompt: "**He works here.**",
          answer: "Тој работи тука",
          accept: ["работи тука", "тој работи овде", "работи овде"],
          hint: "работам is an и-verb - the he-form is работи.",
          after: "работи - the и-group he/she form, the you-form minus its ш. That move is automatic now.",
          reviews: ["verb-и-group", "pronoun-subject", "работам", "тука"],
        },
        {
          type: "exercise",
          prompt: "Ask someone: **Do you understand Macedonian?**",
          answer: "Дали разбираш македонски?",
          accept: ["разбираш ли македонски"],
          hint: "дали at the front, then разбираш + македонски. Or ли right after the verb.",
          after: "A real question you could ask someone on the street in Skopje right now. Дали up front or ли after the verb - both are yours.",
          reviews: ["дали-question", "ли-question", "разбирам", "verb-а-group", "македонски", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**I want to speak Macedonian well.**",
          answer: "Сакам добро да зборувам македонски",
          accept: [
            "сакам да зборувам добро македонски",
            "сакам да зборувам македонски добро",
            "јас сакам добро да зборувам македонски",
          ],
          hint: "сакам да зборувам македонски - and добро likes to sit just before да, or right after the verb.",
          after: "Five words, all familiar. That's a real aspiration, not a textbook sentence.",
          reviews: ["да-subjunctive", "сакам", "зборувам", "verb-а-group", "македонски", "добро", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**I don't have time today.** (време = time)",
          answer: "Немам време денес",
          accept: ["денес немам време", "јас немам време денес"],
          hint: "немам + време + денес.",
          after: "The most useful excuse in any language. Stress by the rule: ВРЕ-ме, two syllables, so the first.",
          reviews: ["немам-fused", "немам", "време", "денес"],
          ru: "The same word as in Russian, with both senses.",
        },
        {
          type: "note",
          title: "One word, two jobs",
          body:
            "**Време** is *time* - and it's also *weather*. Context decides. **Времето** is 'the weather' (or 'the time'): you know what that -то is doing there, because време ends in -е like кафе.\n\nSo **Времето е добро** means *The weather is good*. You've been using добро as 'well'; here it sits after е and describes the weather. Keep that in the back of your mind - it will matter in a couple of lessons.",
          speak: ["време", "Времето е добро."],
          bg: "Same word as Bulgarian време, both senses. Only the article is the one Macedonian shape: времето.",
        },
        {
          type: "exercise",
          prompt: "**The weather is good today.**",
          answer: "Времето е добро денес",
          accept: ["денес времето е добро"],
          hint: "време + -то, then е добро, then денес.",
          after: "Времето е добро денес. You attached an article to a brand new word and it landed on the right ending.",
          reviews: ["definite-neuter", "време", "сум-present", "добро", "денес"],
        },
        {
          type: "exercise",
          prompt: "**They don't understand, but I speak a little.**",
          answer: "Тие не разбираат, но зборувам малку",
          accept: [
            "тие не разбираат, но јас зборувам малку",
            "не разбираат, но зборувам малку",
            "тие не разбираат, ама зборувам малку",
            "не разбираат, ама зборувам малку",
          ],
          hint: "they-form of разбирам: the double-а ending. Then но + the I-form: зборувам малку.",
          after:
            "Subject switch, negation, conjunction, adverb - and the double а of разбираат. You built all of it from scratch.",
          reviews: ["не-negation", "но-but", "pronoun-subject", "разбирам", "verb-а-group", "зборувам", "малку", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "Ask a group: **Do you all want to speak Macedonian?**",
          answer: "Дали сакате да зборувате македонски?",
          accept: ["сакате ли да зборувате македонски", "дали вие сакате да зборувате македонски"],
          hint: "дали + сакате (you all want) + да зборувате (you all speak).",
          after: "Both verbs took -те because both belong to 'you all'. Да never changes the person - the verb after it carries its own.",
          reviews: ["дали-question", "да-subjunctive", "сакам", "verb-а-group", "зборувам", "македонски", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**We are from Skopje, but we travel a lot.**",
          answer: "Ние сме од Скопје, но многу патуваме",
          accept: [
            "ние сме од скопје, но патуваме многу",
            "од скопје сме, но многу патуваме",
            "од скопје сме, но патуваме многу",
            "сме од скопје, но многу патуваме",
          ],
          hint: "сме од Скопје, then но, then патуваме with многу before or after it.",
          after: "Од for 'from', но for 'but', and патуваме for 'we travel'. Многу sits happily on either side of the verb.",
          reviews: ["сум-present", "сум-position", "од-from", "но-but", "патувам", "многу"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Is there a hotel here?**",
          answer: "Има ли хотел тука?",
          accept: ["дали има хотел тука", "има ли хотел овде", "дали има хотел овде"],
          hint: "The 'there is' word is има. Then ли, then what you're looking for.",
          after: "Има ли хотел тука? Four words that will get you a bed for the night.",
          reviews: ["има-existential", "ли-question", "дали-question", "тука"],
        },
        {
          type: "note",
          title: "What just happened",
          body:
            "You just built a dozen sentences from pieces you own, plus one new word. No new rules - just recombination. That's not memorizing. That's thinking in Macedonian.\n\nNow that you know how much you can already do, let's add three more tools to the kit.",
        },
      ],
    },
    {
      id: "m3l2",
      title: "Can and should",
      subtitle: "можам, Може ли, треба да",
      items: [
        {
          type: "note",
          title: "I can: можам",
          body:
            "**Можам** = *I can*. It ends in -м, like every I-form you know. When another action follows, да does its usual job: **Можам да зборувам.** - I can speak.\n\nNew verb, same skeleton. You already know how to use it.",
          speak: ["можам", "Можам да зборувам."],
          introduces: ["verb-е-group", "можам-conjugation"],
          he: "Hebrew יכול changes with gender (יכול / יכולה); можам changes with person, like every verb here - and the person after да changes with it.",
          ru: "Same root as Russian могу. Macedonian keeps the ж of the Russian you-form in every form - including the I-form, можам.",
          bg: "Bulgarian мога swaps г for ж between forms (мога, можеш); Macedonian keeps ж everywhere, and the I-form ends in -м like all the others: можам.",
        },
        {
          type: "exercise",
          prompt: "**I can speak Macedonian.**",
          answer: "Можам да зборувам македонски",
          accept: ["јас можам да зборувам македонски"],
          hint: "можам + да + зборувам + македонски.",
          after: "Two I-forms, two -м endings, one да between them. That's the whole trick.",
          reviews: ["да-subjunctive", "зборувам", "verb-а-group", "македонски", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**I can work today.**",
          answer: "Можам да работам денес",
          accept: ["денес можам да работам"],
          hint: "можам + да + работам + денес.",
          after: "Same pattern. Можам да + any verb you know.",
          reviews: ["да-subjunctive", "работам", "verb-и-group", "денес"],
        },
        {
          type: "exercise",
          prompt: "**I can't travel today.**",
          answer: "Не можам да патувам денес",
          accept: ["денес не можам да патувам"],
          hint: "не goes right before можам, as with any verb.",
          after: "Не можам - negation is just не in front, same as не сум, не сакам.",
          reviews: ["не-negation", "да-subjunctive", "патувам", "денес"],
        },
        {
          type: "note",
          title: "You can: можеш",
          body:
            "The you-form is **можеш** - the -ш ending you know. Now look at the vowel just before it: сака**ш**, учи**ш**, може**ш**. Three vowels, three verb groups. That **е** marks the third and last one: the е-group.\n\nThe verb after да shifts to you-form too: **Можеш да зборуваш.**",
          speak: ["можеш", "Можеш да зборуваш."],
          bg: "Bulgarian можеш has the same shape; the difference is only in the I-form (мога vs можам).",
        },
        {
          type: "exercise",
          prompt: "Ask: **Can you speak English?**",
          answer: "Дали можеш да зборуваш англиски?",
          accept: ["можеш ли да зборуваш англиски"],
          hint: "дали + можеш + да + зборуваш...",
          after: "Both verbs changed to match 'you': можеш, зборуваш. Да sits between them and stays out of it.",
          reviews: ["дали-question", "ли-question", "да-subjunctive", "зборувам", "verb-а-group", "англиски"],
        },
        {
          type: "exercise",
          prompt: "**You can learn Macedonian here.**",
          answer: "Можеш да учиш македонски тука",
          accept: ["тука можеш да учиш македонски", "можеш да учиш македонски овде", "овде можеш да учиш македонски"],
          hint: "можеш + да + учиш (you-form of учам) + македонски + тука.",
          after: "можеш is е-group, учиш is и-group. The group only decides that one vowel; the -ш is the same.",
          reviews: ["да-subjunctive", "учам", "verb-и-group", "македонски", "тука"],
        },
        {
          type: "exercise",
          prompt: "**You can't work today.**",
          answer: "Не можеш да работиш денес",
          accept: ["денес не можеш да работиш"],
          hint: "не + можеш + да + работиш + денес.",
          reviews: ["не-negation", "да-subjunctive", "работам", "verb-и-group", "денес"],
        },
        {
          type: "note",
          title: "He or she can: може",
          body:
            "Drop the ш and you have the he/she form: **може**. Exactly the move you made with сака and учи - the you-form minus its ш.\n\n**Таа може да зборува.** - She can speak. **Тој не може да работи.** - He can't work.",
          speak: ["може", "Таа може да зборува."],
        },
        {
          type: "exercise",
          prompt: "**She can't speak English.**",
          answer: "Таа не може да зборува англиски",
          accept: ["не може да зборува англиски"],
          hint: "не може да зборува + англиски. Both verbs in she-form.",
          after: "не може - negation works the same as always. Just put не before the verb.",
          reviews: ["pronoun-subject", "не-negation", "да-subjunctive", "зборувам", "verb-а-group", "англиски"],
        },
        {
          type: "exercise",
          prompt: "**He can work here.**",
          answer: "Тој може да работи тука",
          accept: ["може да работи тука", "тој може да работи овде", "може да работи овде"],
          hint: "може + да + работи (he-form) + тука.",
          after: "може да работи - both verbs in he/she form. The pattern is solid.",
          reviews: ["pronoun-subject", "да-subjunctive", "работам", "verb-и-group", "тука"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Can she understand Macedonian?**",
          answer: "Дали таа може да разбира македонски?",
          accept: [
            "дали може да разбира македонски",
            "може ли таа да разбира македонски",
            "може ли да разбира македонски",
          ],
          hint: "дали + таа може + да разбира + македонски.",
          after: "Дали in front, and everything else stays in its place. That's why дали is the easy question word.",
          reviews: ["дали-question", "ли-question", "pronoun-subject", "разбирам", "verb-а-group", "македонски"],
        },
        {
          type: "note",
          title: "We can: можеме",
          body:
            "**Можеме** = *we can*. The -ме is the same 'we' marker as сме, сакаме, учиме. Only the vowel before it belongs to the group: може-ме.\n\n**Можеме да патуваме.** - We can travel.",
          speak: ["можеме", "Можеме да патуваме."],
        },
        {
          type: "exercise",
          prompt: "**We can speak a little Macedonian.**",
          answer: "Можеме да зборуваме малку македонски",
          accept: [
            "можеме малку да зборуваме македонски",
            "можеме да зборуваме македонски малку",
            "ние можеме да зборуваме малку македонски",
          ],
          hint: "можеме + да зборуваме + малку + македонски.",
          after: "Two -ме endings, one for each verb. 'We' is stamped on both.",
          reviews: ["да-subjunctive", "зборувам", "verb-а-group", "малку", "македонски"],
        },
        {
          type: "exercise",
          prompt: "**We can't travel today.**",
          answer: "Не можеме да патуваме денес",
          accept: ["денес не можеме да патуваме"],
          hint: "не + можеме + да + патуваме + денес.",
          reviews: ["не-negation", "да-subjunctive", "патувам", "денес"],
        },
        {
          type: "note",
          title: "You all can, they can: можете, можат",
          body:
            "Two forms left, and you can predict both. **Можете** = *you all can* - the -те of сте and сакате. **Можат** = *they can* - the -ат of учат.\n\nNotice: only the а-group doubles its vowel in the they-form (сакаат). The и-group and the е-group keep a single а: учат, можат.",
          speak: ["можете", "можат"],
          bg: "Bulgarian brings back the г in могат; Macedonian keeps ж to the end: можат.",
        },
        {
          type: "exercise",
          prompt: "Ask a group: **Can you all understand?**",
          answer: "Дали можете да разбирате?",
          accept: ["можете ли да разбирате", "дали вие можете да разбирате"],
          hint: "дали + можете + да + разбирате.",
          after: "можете, разбирате - both wearing the you-all -те.",
          reviews: ["дали-question", "ли-question", "да-subjunctive", "разбирам", "verb-а-group"],
        },
        {
          type: "exercise",
          prompt: "**They can't work today.**",
          answer: "Тие не можат да работат денес",
          accept: ["не можат да работат денес", "денес тие не можат да работат", "денес не можат да работат"],
          hint: "не можат + да работат (they-form of работам) + денес.",
          after: "можат, работат - single а in both, because neither is an а-verb. You kept the double а for сакаат and разбираат.",
          reviews: ["не-negation", "pronoun-subject", "да-subjunctive", "работам", "verb-и-group", "денес"],
        },
        {
          type: "exercise",
          prompt: "**The students can learn Macedonian here.**",
          answer: "Студентите можат да учат македонски тука",
          accept: ["студентите можат да учат македонски овде", "тука студентите можат да учат македонски"],
          hint: "студентите (the students) + можат + да учат + македонски + тука.",
          after: "A plural noun with its article, a they-form, and да. That's a sentence with real structure.",
          reviews: ["plural-и", "да-subjunctive", "учам", "verb-и-group", "македонски", "тука"],
        },
        {
          type: "note",
          title: "Може ли - polite requests",
          body:
            "**Може ли...?** - literally 'can it?', 'is it possible?' This is your universal polite request:\n\n- **Може ли кафе?** - Could I get a coffee?\n- **Може ли?** - May I? (entering, passing, taking a seat...)\n\nThe answer you'll hear: **Може!** - sure, go ahead.\n\nRemember **Ве молам**? Add it to sound even more polite: **Може ли кафе, Ве молам?**",
          speak: ["Може ли кафе?", "Може!", "Може ли кафе, Ве молам?"],
          introduces: ["може-ли-polite"],
          he: "The same shortcut as Hebrew אפשר...? - one frozen word, no subject, and the thing you want after it.",
          bg: "Identical to Bulgarian Може ли; only the 'please' after it is Ве молам, not моля.",
        },
        {
          type: "exercise",
          prompt: "Ask for tea politely.",
          answer: "Може ли чај?",
          accept: ["може ли чај, ве молам"],
          hint: "Може ли + what you want.",
          after: "Three words and you just ordered tea in a Skopje cafe.",
          reviews: ["чај"],
        },
        {
          type: "exercise",
          prompt: "Ask for **the bill, please**.",
          answer: "Може ли сметката, Ве молам?",
          accept: ["може ли сметката"],
          hint: "сметка → сметката (the bill), then Ве молам for 'please'.",
          after: "Може ли сметката, Ве молам? You'll use this one a lot.",
          reviews: ["сметка", "definite-fem", "ве молам"],
        },
        {
          type: "exercise",
          prompt: "Ask for **water, please**.",
          answer: "Може ли вода, Ве молам?",
          accept: ["може ли вода"],
          hint: "Може ли + вода + Ве молам.",
          reviews: ["вода", "ве молам"],
        },
        {
          type: "note",
          title: "Thank you: благодарам",
          body:
            "When they bring your order, you need one word: **Благодарам!** - thank you. Look at its ending: -м. It's really a verb, 'I thank'. Stress by the rule, third from the end: бла-го-ДА-рам.\n\nВе молам to ask, благодарам to receive - your full cafe toolkit.",
          speak: ["Благодарам!"],
          ru: "Same verb as the Russian formal thank-you (благодар-) - but here it is the everyday 'thanks'.",
          bg: "Bulgarian благодаря ends in the 1sg -я with final stress; Macedonian благодарам ends in -м like every I-form, and the stress moves back to ДА.",
        },
        {
          type: "exercise",
          prompt: "Say **thank you**.",
          answer: "Благодарам",
          hint: "бла-го-ДА-рам - it ends like an I-form because it is one.",
          after:
            "Благодарам! Everyone in Skopje also says the short, friendly **фала**. Благодарам is safe anywhere; фала is what you'll hear most.",
          speak: "Благодарам!",
          reviews: ["благодарам", "stress-antepenult"],
        },
        {
          type: "exercise",
          prompt: "Order a coffee politely, then say thank you. (Two sentences.)",
          answer: "Може ли кафе, Ве молам? Благодарам!",
          accept: ["може ли кафе? благодарам"],
          hint: "Може ли кафе, Ве молам? Then: Благодарам!",
          after: "A complete cafe interaction in two sentences. You're ready.",
          reviews: ["може-ли-polite", "ве молам", "благодарам"],
        },
        {
          type: "exercise",
          prompt: "**Thank you, I understand.**",
          answer: "Благодарам, разбирам",
          accept: ["благодарам, јас разбирам"],
          hint: "благодарам + разбирам.",
          after: "Two I-forms in a row - one of them a thank-you.",
          reviews: ["благодарам", "разбирам", "verb-а-group", "pronoun-drop"],
        },
        {
          type: "note",
          title: "Треба да - need to, should",
          body:
            "**Треба да** = *need to / have to / should*. The important part: **треба itself never changes**. The person lives entirely in the verb after да:\n\n- **Треба да работам.** - I have to work.\n- **Треба да работиш.** - You have to work.\n- **Треба да работи.** - She has to work.\n\nSame треба every time. Only the verb after да moves.",
          speak: ["Треба да работам.", "Треба да работиш."],
          introduces: ["треба-да"],
          he: "Hebrew צריך agrees with the subject (צריך / צריכה); треба never does. Think of it as a frozen 'it is needed that...'.",
          ru: "Треба behaves like Russian надо / нужно - frozen, impersonal. Ukrainian has the same word: треба. But no dative: not 'мне надо', just треба да + verb.",
          bg: "Bulgarian трябва да → треба да: я becomes е, as in хляб → леб. Same frozen shape, same да.",
        },
        {
          type: "exercise",
          prompt: "**I have to work.**",
          answer: "Треба да работам",
          accept: ["јас треба да работам"],
          hint: "треба (frozen) + да + работам.",
          reviews: ["да-subjunctive", "работам", "verb-и-group", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**We have to speak Macedonian.**",
          answer: "Треба да зборуваме македонски",
          accept: ["ние треба да зборуваме македонски"],
          hint: "треба да + the we-form: зборуваме.",
          after: "The person lives in зборуваме, not in треба. Треба just sits there, unchanging.",
          reviews: ["да-subjunctive", "зборувам", "verb-а-group", "македонски"],
        },
        {
          type: "exercise",
          prompt: "**You need to learn Macedonian.**",
          answer: "Треба да учиш македонски",
          accept: ["ти треба да учиш македонски"],
          hint: "треба (frozen) + да + учиш (you-form) + македонски.",
          after:
            "Треба covers 'should' and 'need to'. When it's a hard must, people reach for **мора да** instead - Мора да работам. Треба is enough for now.",
          reviews: ["да-subjunctive", "учам", "verb-и-group"],
        },
        {
          type: "exercise",
          prompt: "**She doesn't have to work today.**",
          answer: "Таа не треба да работи денес",
          accept: ["не треба да работи денес", "денес таа не треба да работи"],
          hint: "не + треба + да + работи (she-form) + денес.",
          after: "не треба да - negation goes on треба, and the person still lives in работи.",
          reviews: ["не-negation", "pronoun-subject", "да-subjunctive", "работам", "verb-и-group", "денес"],
        },
        {
          type: "exercise",
          prompt: "**I can't work today.**",
          answer: "Не можам да работам денес",
          accept: ["денес не можам да работам"],
          hint: "не можам да работам + денес.",
          after: "You just combined negation with можам - which you learned ten minutes ago. The system compounds.",
          reviews: ["не-negation", "да-subjunctive", "работам", "verb-и-group", "денес"],
        },
        {
          type: "exercise",
          prompt: "**The city is here.** (град = city)",
          answer: "Градот е тука",
          accept: ["градот е овде"],
          hint: "град ends in a consonant - same pattern as хотел → хотелот.",
          after:
            "Градот - you've now put the article on three masculine nouns: хотелот, телефонот, градот. All consonant endings, all -от. File that away.",
          speak: "Градот е тука.",
          reviews: ["град", "definite-masc", "сум-present", "тука"],
          ru: "Russian город is the same word with the full vowel; the short град survives in city names like Волгоград.",
          bg: "Bulgarian градът → градот. One masculine article, always -от, whether the noun is subject or object.",
        },
        {
          type: "exercise",
          prompt: "**The city is not there.**",
          answer: "Градот не е таму",
          hint: "градот + не + е + таму.",
          reviews: ["град", "definite-masc", "не-negation", "сум-present", "таму"],
        },
        {
          type: "note",
          title: "Three ways to combine verbs",
          body:
            "**сакам да / можам да / треба да** + any verb you know = want to / can / should do anything. Three structures, one glue word - and Може ли + Ве молам + благодарам handle all the politeness you need.\n\nNext: you'll notice a pattern you've actually been using all along.",
        },
      ],
    },
    {
      id: "m3l3",
      title: "The discovery",
      subtitle: "Why noun endings matter",
      items: [
        {
          type: "note",
          title: "A little test",
          body:
            "You've been adding 'the' to nouns for a while now. Кафето, водата, телефонот, градот... and I haven't told you a single rule. Let's see whether you've already worked one out.\n\nI'll give you a new noun. You tell me what 'the' version looks like.",
        },
        {
          type: "exercise",
          prompt: "**Куќа** means *house*. How would you say **the house**?",
          answer: "куќата",
          hint: "Look at the ending of куќа. You've seen колата and водата - what do кола and вода have in common with куќа?",
          after: "Куќа ends in **-а**, just like кола and вода. They all take **-та**. You saw the pattern before I said it.",
          speak: "куќата",
          reviews: ["куќа", "definite-fem"],
          bg: "Bulgarian къща → куќа: the щ becomes ќ (as in нощ → ноќ). The article is -та in both.",
        },
        {
          type: "exercise",
          prompt: "**Море** means *sea*. How would you say **the sea**?",
          answer: "морето",
          hint: "Remember кафето and виното? Look at how море ends.",
          after: "Море ends in **-е**, like кафе; вино ends in -о. They all take **-то**.",
          speak: "морето",
          reviews: ["море", "definite-neuter"],
        },
        {
          type: "exercise",
          prompt: "And **леб** means *bread*. **The bread**?",
          answer: "лебот",
          hint: "Remember хотелот and градот? What kind of ending does леб have?",
          after: "Леб ends in a **consonant**, like хотел and град. They all take **-от**.",
          speak: "лебот",
          reviews: ["леб", "definite-masc"],
          ru: "Same word as хлеб, minus the х.",
          bg: "Bulgarian хляб → леб: я becomes е and the х is gone; the article is -от, not -ът.",
        },
        {
          type: "note",
          title: "You already knew this",
          body:
            "You've been doing this all along. The ending tells you everything:\n\n- **Consonant** → masculine → **-от** (хотелот, градот, лебот)\n- **-а** → feminine → **-та** (колата, водата, куќата)\n- **-о / -е** → neuter → **-то** (кафето, виното, морето)\n\nThree genders. Three article endings. And the noun itself announces which one it wants.",
          introduces: ["noun-gender"],
          he: "Hebrew has the same idea - endings hint at gender, ה- is usually feminine - but Macedonian is more consistent. In Hebrew you still get surprises like עין; here the ending really is the rule.",
          bg: "The same three-way split as Bulgarian, with one difference: the masculine has a single article, -от, where Bulgarian juggles -ът and -а.",
        },
        {
          type: "note",
          title: "A new noun: маса",
          body: "**Маса** means *table*. It ends in -а, so it's feminine - the article will be -та.",
          speak: ["маса"],
          ru: "Macedonian стол means *chair*, not table. Table is маса. This trips up every Russian speaker.",
        },
        {
          type: "exercise",
          prompt: "**the table**",
          answer: "масата",
          hint: "маса ends in -а → feminine → add -та.",
          after: "масата - the pattern holds. Feminine noun, -та article.",
          speak: "масата",
          reviews: ["маса", "definite-fem"],
        },
        {
          type: "exercise",
          prompt: "**The table is there.**",
          answer: "Масата е таму",
          hint: "маса → масата + е + таму.",
          reviews: ["маса", "definite-fem", "сум-present", "таму"],
        },
        {
          type: "exercise",
          prompt: "**I don't have a table.**",
          answer: "Немам маса",
          accept: ["јас немам маса"],
          hint: "немам + маса. No article - it's 'a table', not 'the table'.",
          reviews: ["немам", "немам-fused", "маса", "pronoun-drop"],
        },
        {
          type: "note",
          title: "A new noun: жена",
          body: "**Жена** means *woman*. Ends in -а - feminine again. You already know what the article will look like.",
          speak: ["жена"],
          ru: "Same as Russian жена, but here it's simply 'woman', not only 'wife'.",
        },
        {
          type: "exercise",
          prompt: "**the woman**",
          answer: "жената",
          hint: "жена ends in -а → feminine → -та.",
          after: "жената - same rule, new word. The pattern is automatic now.",
          speak: "жената",
          reviews: ["жена", "definite-fem"],
        },
        {
          type: "exercise",
          prompt: "**The woman understands Macedonian.**",
          answer: "Жената разбира македонски",
          hint: "жена → жената + разбира (she-form) + македонски.",
          reviews: ["жена", "definite-fem", "разбирам", "verb-а-group", "македонски"],
        },
        {
          type: "exercise",
          prompt: "**The woman works here.**",
          answer: "Жената работи тука",
          accept: ["жената работи овде"],
          hint: "жена → жената + работи + тука.",
          reviews: ["жена", "definite-fem", "работам", "verb-и-group", "тука"],
        },
        {
          type: "note",
          title: "A new noun: маж",
          body: "**Маж** means *man*. Ends in a consonant - so it's masculine. You know the drill.",
          speak: ["маж"],
          ru: "Looks like муж, but муж is a husband. Маж is any man.",
          bg: "Bulgarian мъж → маж: ъ becomes а, as in път → пат.",
        },
        {
          type: "exercise",
          prompt: "**the man**",
          answer: "мажот",
          hint: "маж ends in a consonant → masculine → -от.",
          after: "мажот - consonants take -от. Three new nouns, three correct articles.",
          speak: "мажот",
          reviews: ["маж", "definite-masc"],
        },
        {
          type: "exercise",
          prompt: "**The man can speak Macedonian.**",
          answer: "Мажот може да зборува македонски",
          hint: "маж → мажот + може + да + зборува + македонски.",
          after: "Article on the noun, he-form on both verbs. Everything from the last two lessons in one line.",
          reviews: ["маж", "definite-masc", "можам-word", "можам-conjugation", "да-subjunctive", "зборувам", "verb-а-group", "македонски"],
        },
        {
          type: "choice",
          prompt: "You learn a new word: **пиво** (beer). What gender is it?",
          options: [
            "Neuter - it ends in -о",
            "Feminine - it ends in -о",
            "Masculine - it's a drink",
          ],
          correct: 0,
          after: "Neuter. Пиво ends in -о, like вино, so 'the beer' is **пивото**. You can do this for any noun now.",
          speak: "пивото",
          reviews: ["noun-gender", "пиво"],
          ru: "Same word, same gender as Russian пиво.",
          bg: "Bulgarian says бира, and it's feminine (бирата). Macedonian пиво ends in -о, so it's neuter: пивото. Don't carry the gender across.",
        },
        {
          type: "exercise",
          prompt: "Ask for **a beer, please**.",
          answer: "Може ли пиво, Ве молам?",
          accept: ["може ли пиво"],
          hint: "Може ли + пиво + Ве молам.",
          after: "Може ли пиво - no article, because you want *a* beer, any beer.",
          reviews: ["може-ли-polite", "пиво", "ве молам"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Is there bread?**",
          answer: "Има ли леб?",
          accept: ["дали има леб"],
          hint: "The 'there is' word, then ли, then леб.",
          reviews: ["има-existential", "ли-question", "дали-question", "леб"],
        },
        {
          type: "exercise",
          prompt: "**The man is here and the woman is there.**",
          answer: "Мажот е тука и жената е таму",
          accept: ["мажот е овде и жената е таму"],
          hint: "маж → мажот, жена → жената; use тука and таму.",
          after: "Two articles, two genders, one sentence. The system works.",
          reviews: ["маж", "definite-masc", "сум-present", "тука", "и-conjunction", "жена", "definite-fem", "таму"],
        },
        {
          type: "note",
          title: "The rule for everything",
          body:
            "From now on, every new noun you meet tells you its gender through its ending. No lists to memorize - just look at the last letter.\n\nAnd gender is about to matter for more than the article. Next lesson, other words will start matching the noun too.",
        },
      ],
    },
    {
      id: "m3l4",
      title: "Describing things",
      subtitle: "нов, нова, ново, нови",
      items: [
        {
          type: "note",
          title: "Adjectives match the noun",
          body:
            "In Macedonian, describing words change shape to match the noun they describe. Let's start with **нов** (new).\n\nWith a masculine noun, the adjective stays bare - no ending: **нов град** (a new city).",
          speak: ["нов", "нов град"],
          introduces: ["adj-agreement"],
          he: "Hebrew does this too - חדש / חדשה - and the logic is the same: the adjective borrows the noun's gender.",
          ru: "Macedonian нов looks like the Russian short form (нов, нова, ново) - and here it is the only form there is.",
        },
        {
          type: "exercise",
          prompt: "**a new hotel**",
          answer: "нов хотел",
          hint: "хотел is masculine (consonant ending) → the adjective stays bare: нов.",
          after: "нов хотел - masculine noun, bare adjective. That's the simplest case.",
          reviews: ["нов", "noun-gender"],
        },
        {
          type: "exercise",
          prompt: "**a new city**",
          answer: "нов град",
          hint: "град is masculine → the adjective stays bare.",
          after: "Masculine: the adjective stays stripped down, no ending.",
          reviews: ["нов", "град", "noun-gender"],
        },
        {
          type: "note",
          title: "Feminine: нова",
          body:
            "With a feminine noun, the adjective adds **-а** to match: **нова кола** (a new car). The adjective rhymes with the noun - both end in -а.",
          speak: ["нова кола"],
        },
        {
          type: "exercise",
          prompt: "**a new car**",
          answer: "нова кола",
          hint: "кола is feminine → the adjective takes -а.",
          after: "Feminine noun, feminine adjective. They rhyme.",
          reviews: ["нов", "кола", "noun-gender"],
        },
        {
          type: "exercise",
          prompt: "**The table is new.**",
          answer: "Масата е нова",
          hint: "маса is feminine → нова; 'the table' = масата.",
          after: "The adjective agrees even when it comes after е. It always matches the noun.",
          reviews: ["нов", "маса", "definite-fem", "сум-present"],
        },
        {
          type: "exercise",
          prompt: "**a new house**",
          answer: "нова куќа",
          hint: "куќа is feminine → the adjective takes -а: нова.",
          reviews: ["нов", "куќа", "noun-gender"],
        },
        {
          type: "note",
          title: "Neuter: ново",
          body:
            "With a neuter noun, the adjective adds **-о**: **ново кафе** (a new coffee). Neuter nouns end in -о or -е; the adjective always picks -о.",
          speak: ["ново кафе"],
        },
        {
          type: "exercise",
          prompt: "**a new coffee** (as in: a new kind)",
          answer: "ново кафе",
          hint: "кафе is neuter → the adjective takes -о.",
          after: "ново кафе - neuter noun, -о adjective. Three genders, three shapes.",
          reviews: ["нов", "noun-gender"],
        },
        {
          type: "exercise",
          prompt: "**a new beer**",
          answer: "ново пиво",
          hint: "пиво ends in -о → neuter → ново.",
          reviews: ["нов", "пиво", "noun-gender"],
        },
        {
          type: "exercise",
          prompt: "**The wine is new.**",
          answer: "Виното е ново",
          hint: "вино → виното + е + ново.",
          after: "Виното е ново. Three singular forms down: нов, нова, ново.",
          reviews: ["нов", "вино", "definite-neuter", "сум-present"],
        },
        {
          type: "note",
          title: "Plural: нови",
          body:
            "For plural nouns, all three genders collapse into ONE adjective form: **нови**. Doesn't matter what gender the nouns were - plural is always -и.\n\n**нови хотели** (new hotels), **нови студенти** (new students).",
          speak: ["нови хотели"],
          he: "Like Hebrew adjective agreement - חדש / חדשה / חדשים - but simpler: one plural form (нови) instead of separate masculine and feminine plurals.",
        },
        {
          type: "exercise",
          prompt: "**new hotels**",
          answer: "нови хотели",
          hint: "Plural → one form for all genders: нови.",
          after: "нови - the plural adjective. Three singular shapes, one plural. That's the whole system.",
          reviews: ["нов", "plural-и"],
        },
        {
          type: "exercise",
          prompt: "**We have new problems.**",
          answer: "Имаме нови проблеми",
          accept: ["ние имаме нови проблеми"],
          hint: "имаме + нови + проблеми.",
          after: "нови проблеми - the plural -и on both words. They rhyme, like нова кола did.",
          reviews: ["нов", "имам", "verb-а-group", "plural-и", "pronoun-drop"],
        },
        {
          type: "note",
          title: "'The' jumps to the adjective",
          body:
            "When a noun has both an adjective and an article, 'the' rides on the adjective instead:\n\n- кола → **колата** (the car)\n- нова кола → **новата** кола (the new car)\n\nThe article moved from the noun to the adjective. Macedonian marks 'the' once, on the first word of the phrase.",
          speak: ["новата кола"],
          introduces: ["adj-definite"],
          he: "Hebrew puts ה on both words (הבית החדש); Macedonian marks 'the' once, and on the adjective.",
        },
        {
          type: "exercise",
          prompt: "**the new car**",
          answer: "новата кола",
          hint: "'The' rides on the adjective: нова + -та → новата.",
          after: "новата кола - the article jumped onto the adjective. The noun stays bare.",
          reviews: ["нов", "кола", "definite-fem"],
        },
        {
          type: "exercise",
          prompt: "**the new house**",
          answer: "новата куќа",
          hint: "куќа is feminine → 'the' on the adjective: новата.",
          reviews: ["нов", "куќа", "definite-fem"],
        },
        {
          type: "exercise",
          prompt: "**the new coffee**",
          answer: "новото кафе",
          hint: "кафе is neuter → 'the' on the adjective: новото.",
          after: "новото кафе - the neuter -то, riding on ново.",
          reviews: ["нов", "definite-neuter"],
        },
        {
          type: "note",
          title: "Masculine: -иот",
          body:
            "For a masculine noun, the article on the adjective is **-иот** - an и slips in before the -от:\n\n**новиот** хотел - the new hotel\n**новиот** град - the new city\n\nThree patterns: нов**ата** (feminine), нов**ото** (neuter), нов**иот** (masculine).",
          speak: ["новиот хотел"],
          bg: "Bulgarian новият → новиот (-ият → -иот). And there is no short form новия: one masculine article, always -иот.",
        },
        {
          type: "exercise",
          prompt: "**the new hotel**",
          answer: "новиот хотел",
          hint: "Masculine definite adjective: -иот.",
          reviews: ["нов", "definite-masc"],
        },
        {
          type: "exercise",
          prompt: "**The new restaurant is there.**",
          answer: "Новиот ресторан е таму",
          hint: "новиот + ресторан + е + таму.",
          after: "Новиот ресторан - masculine, so -иот on the adjective and nothing on the noun.",
          reviews: ["нов", "definite-masc", "сум-present", "таму"],
        },
        {
          type: "exercise",
          prompt: "**The city is new.**",
          answer: "Градот е нов",
          hint: "град is masculine → градот, and after е the adjective is bare: нов.",
          after: "Градот е нов. The article stays on the noun here because there is no adjective in front of it.",
          reviews: ["нов", "град", "definite-masc", "сум-present"],
        },
        {
          type: "note",
          title: "Good: добар, and the vanishing а",
          body:
            "**Добар** = *good*. It follows нов's pattern with one twist: the **а** before р disappears the moment an ending arrives. **Добар** хотел, but **добра** куќа, **добро** вино, **добри** студенти.\n\nAnd you already know добро - it's the neuter form, and it doubles as 'well'. Времето е добро was this word all along.",
          speak: ["добар", "добар хотел", "добра куќа", "добро вино"],
          ru: "Careful: the Russian cognate means 'kind'. Macedonian добар is plain 'good'.",
          bg: "Bulgarian добър → добар (ъ → а). The vowel vanishes before endings in both languages: добра, добро, добри.",
        },
        {
          type: "exercise",
          prompt: "**a good hotel**",
          answer: "добар хотел",
          hint: "хотел is masculine → the bare form, with its а still in place.",
          reviews: ["добар", "noun-gender"],
        },
        {
          type: "exercise",
          prompt: "**a good house**",
          answer: "добра куќа",
          hint: "куќа is feminine → add -а, and the а before р drops out.",
          after: "добра - not добара. The extra а only lives in the bare masculine form.",
          reviews: ["добар", "куќа", "noun-gender"],
        },
        {
          type: "exercise",
          prompt: "**The wine is good.**",
          answer: "Виното е добро",
          hint: "виното + е + the neuter form.",
          after: "Виното е добро - the same добро you've been using for 'well', now doing its neuter-adjective job.",
          reviews: ["добар", "вино", "definite-neuter", "сум-present"],
        },
        {
          type: "exercise",
          prompt: "**good students**",
          answer: "добри студенти",
          hint: "Plural → -и, and the а drops as it does before every ending.",
          reviews: ["добар", "plural-и"],
        },
        {
          type: "note",
          title: "Greetings you can now derive",
          body:
            "Here's something fun. **Утро** (morning) is neuter. **Ден** (day) is masculine. Add добар in the right shape, and you get the two greetings people say all day.\n\nCan you predict them?",
          speak: ["утро", "ден"],
        },
        {
          type: "exercise",
          prompt: "Say **good morning**.",
          answer: "Добро утро",
          hint: "утро is neuter - which ending does the adjective take for neuter?",
          after: "Утро is neuter - the adjective took **-о**. You didn't memorize this greeting. You derived it.",
          speak: "Добро утро!",
          reviews: ["добар", "добро утро", "noun-gender"],
        },
        {
          type: "exercise",
          prompt: "Say **good day**.",
          answer: "Добар ден",
          hint: "ден is masculine - and masculine adjectives stay bare.",
          after: "Ден is masculine - добар stays whole. Two greetings, zero memorization.",
          speak: "Добар ден!",
          reviews: ["добар", "добар ден", "noun-gender"],
          bg: "Bulgarian добър ден → добар ден. Good evening is different too, but that comes later.",
        },
        {
          type: "exercise",
          prompt: "**The morning is good.**",
          answer: "Утрото е добро",
          hint: "утро → утрото (the morning) + е + добро (neuter).",
          reviews: ["добро утро", "definite-neuter", "добар", "сум-present"],
        },
        {
          type: "note",
          title: "Big and beautiful",
          body:
            "Every adjective plays by the same rules, so two more cost you nothing. **Голем** = *big*. **Убав** = *nice, beautiful*.\n\n**голем** град, **голема** куќа, **големо** море. **убав** ден, **убава** жена, **убаво** утро.",
          speak: ["голем град", "голема куќа", "убав ден", "убава жена"],
          bg: "Bulgarian голям → голем (я → е), хубав → убав (the х is gone). The endings behave exactly as in Bulgarian.",
        },
        {
          type: "exercise",
          prompt: "**a big city**",
          answer: "голем град",
          hint: "град is masculine → the bare form.",
          reviews: ["голем", "град", "noun-gender"],
        },
        {
          type: "exercise",
          prompt: "**The house is big.**",
          answer: "Куќата е голема",
          hint: "куќата + е + the feminine form of голем.",
          after: "Куќата е голема - feminine noun, -а on the adjective, even across е.",
          reviews: ["голем", "куќа", "definite-fem", "сум-present"],
        },
        {
          type: "exercise",
          prompt: "**The sea is beautiful.**",
          answer: "Морето е убаво",
          hint: "море is neuter → морето, and убав takes -о.",
          reviews: ["убав", "море", "definite-neuter", "сум-present"],
        },
        {
          type: "exercise",
          prompt: "**The new house is big.**",
          answer: "Новата куќа е голема",
          hint: "новата (article on the adjective) + куќа + е + голема.",
          after: "Two adjectives agreeing with one feminine noun - one carrying the article, one sitting after е. That's real Macedonian.",
          reviews: ["нов", "голем", "куќа", "adj-agreement", "сум-present"],
        },
        {
          type: "note",
          title: "Hello: здраво",
          body:
            "One more greeting, and it needs no grammar at all: **Здраво!** - hello. One word for anyone, at any time of day, formal or not.\n\nWith добро утро, добар ден and здраво, you can greet anyone in Macedonia. You know what things are, you can ask for what you want, you can describe what you see. The scaffolding is up.",
          speak: ["Здраво!"],
          ru: "Same root as the Russian greeting - literally a wish of health.",
          bg: "Bulgarian splits здравей / здравейте by formality; Macedonian здраво serves everyone.",
        },
        {
          type: "exercise",
          prompt: "Say hello, then ask: **Do you speak English?**",
          answer: "Здраво! Дали зборуваш англиски?",
          accept: [
            "здраво, зборуваш ли англиски",
            "здраво, дали зборувате англиски",
            "здраво, зборувате ли англиски",
          ],
          hint: "Здраво, then дали + зборуваш + англиски.",
          after: "A greeting and a question. That's how every conversation you'll have in Skopje starts.",
          reviews: ["здраво", "дали-question", "ли-question", "зборувам", "verb-а-group", "англиски"],
        },
        {
          type: "note",
          title: "The whole shape",
          body:
            "You've now used every piece, so here is the picture in one place:\n\n- **нов / нова / ново / нови** - bare, -а, -о, -и\n- **добар / добра / добро / добри** - same endings, and the а before р vanishes\n- with 'the': **новиот / новата / новото / новите** - the article rides the adjective, and the masculine slips in an и\n\nThe noun's ending picks the gender; the adjective copies it. That single idea covers every adjective you'll ever meet.",
          speak: ["новиот град", "новата куќа", "новото кафе", "новите хотели"],
        },
      ],
    },
  ],
};
