import type { Module } from "./types";

export const module2: Module = {
  id: "m2",
  title: "Wanting and having",
  blurb:
    "Your first action verbs, a 'the' that sticks to the end of the word, and the most Bulgarian thing about Bulgarian: да.",
  lessons: [
    {
      id: "m2l1",
      title: "I want",
      subtitle: "искам, моля, and the article -то",
      items: [
        {
          type: "note",
          title: "The verb tells you who",
          body: "Bulgarian verb endings carry the person. **Искам** = I want. Change the ending, change the person:\n\n- аз **искам** (-м = I)\n- ти **искаш** (-ш = you)\n- той/тя **иска** (bare stem = he/she)\n\nThe ending does the work, so pronouns are optional - just like with съм.",
          he: "Like Hebrew past tense - הלכתי, הלכת, הלך - the ending tells you who.",
          speak: ["искам", "искаш", "иска"],
        },
        {
          type: "exercise",
          prompt: "**I want coffee.**",
          answer: "Искам кафе",
          accept: ["аз искам кафе"],
          hint: "искам = I want. The -м ending is 'I'.",
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you want tea?**",
          answer: "Искаш ли чай?",
          hint: "ли goes right after the verb: Искаш ли...",
          after: "Same ли you used with 'to be' - it works with every verb.",
        },
        {
          type: "exercise",
          prompt: "**He wants tea.**",
          answer: "Той иска чай",
          accept: ["иска чай"],
          hint: "He/she form: иска - bare stem, no ending.",
        },
        {
          type: "note",
          title: "The plural half",
          body: "The plural forms follow the same logic:\n\n- ние **искаме** (-ме = we)\n- вие **искате** (-те = you all)\n- те **искат** (-ат = they)\n\nSame markers as съм's family: -ме for we, -те for you-all.",
          speak: ["искаме", "искате", "искат"],
        },
        {
          type: "exercise",
          prompt: "**We want water.** (вода = water)",
          answer: "Искаме вода",
          accept: ["ние искаме вода"],
          hint: "We-form ends in -ме: искаме.",
        },
        {
          type: "exercise",
          prompt: "**They want coffee.**",
          answer: "Те искат кафе",
          accept: ["искат кафе"],
          hint: "They-form ends in -ат: искат.",
        },
        {
          type: "note",
          title: "Please",
          body: "One word to file away: **моля** = please. At a cafe:\n\n**Кафе, моля.** - Coffee, please.\n**Вода, моля.** - Water, please.\n\nThat's a complete, polite order. No verb needed.",
          speak: ["Кафе, моля.", "Вода, моля."],
        },
        {
          type: "exercise",
          prompt: "**Water, please.**",
          answer: "Вода, моля",
          hint: "вода = water, моля = please.",
        },
        {
          type: "exercise",
          prompt: "**I don't want tea.**",
          answer: "Не искам чай",
          accept: ["аз не искам чай"],
          hint: "не before the verb: не искам.",
          after: "Не works the same way it did with съм - put it before the verb and you're done.",
        },
        {
          type: "note",
          title: "'The' lives at the end",
          body: "Bulgarian marks 'the' by adding to the end of the word. No separate word - just a suffix:\n\nкафе + -то = **кафето** (the coffee)",
          he: "Like Hebrew's ה, but at the end instead of the beginning. הקפה becomes кафе**то**.",
          speak: ["кафето"],
        },
        {
          type: "exercise",
          prompt: "**The coffee is here.**",
          answer: "Кафето е тук",
          hint: "кафе + -то = кафето.",
          after: "Кафето е тук. You just used your first Bulgarian article.",
        },
        {
          type: "exercise",
          prompt: "**I want the coffee.**",
          answer: "Искам кафето",
          hint: "искам + кафето (the coffee).",
        },
        {
          type: "exercise",
          prompt: "**Is the coffee here?**",
          answer: "Кафето тук ли е?",
          accept: ["тук ли е кафето"],
          hint: "ли after the word being asked about: тук ли е?",
        },
        {
          type: "note",
          title: "At the cafe",
          body: "You can already survive a Bulgarian cafe. Order: **Кафе, моля.** Ask a question: **Искаш ли чай?** When you're done: **Сметка, моля.** (сметка = the bill)\n\nThat's not a toy sentence - that's what people actually say.",
          speak: ["Кафе, моля.", "Сметка, моля."],
        },
        {
          type: "exercise",
          prompt: "Ask for the bill at a cafe.",
          answer: "Сметка, моля",
          hint: "сметка = bill, моля = please.",
          after: "Сметка, моля. You just ordered and paid at a Bulgarian cafe using real sentences.",
        },
      ],
    },
    {
      id: "m2l2",
      title: "Having and not having",
      subtitle: "имам, нямам, and more articles",
      items: [
        {
          type: "note",
          title: "To have - a real verb",
          body: "**Имам** = I have. It follows the same а-family pattern as искам, so you already know all its forms: **имам, имаш, има, имаме, имате, имат**.\n\nSee it? Same endings. Learn one а-family verb, you've learned them all.",
          he: "Hebrew has no verb 'to have' - you say יש לי ('there is to me'). Bulgarian went the English way: a real verb, имам.",
          ru: "Same relief for Russian speakers: no у меня есть construction. Bulgarian just says имам - subject, verb, done.",
          speak: ["имам", "имаш", "има"],
        },
        {
          type: "exercise",
          prompt: "**I have a problem.**",
          answer: "Имам проблем",
          accept: ["аз имам проблем"],
          hint: "имам = I have, same family as искам.",
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you have a phone?**",
          answer: "Имаш ли телефон?",
          hint: "имаш + ли + телефон?",
        },
        {
          type: "note",
          title: "нямам - the fused 'don't have'",
          body: "'Not have' fused into its own verb: **нямам** (never 'не имам'). Same endings - just swap им- for ням-.\n\n**Нямам кола.** - I don't have a car. (**кола** = car)",
          speak: ["Нямам кола.", "Тя няма кола."],
        },
        {
          type: "exercise",
          prompt: "**I don't have a car.**",
          answer: "Нямам кола",
          hint: "Use the fused нямам, not 'не имам'.",
        },
        {
          type: "exercise",
          prompt: "**She doesn't have a car.**",
          answer: "Тя няма кола",
          accept: ["няма кола"],
          hint: "She-form: няма (bare stem, no ending).",
        },
        {
          type: "exercise",
          prompt: "**The car is there.**",
          answer: "Колата е там",
          hint: "Add 'the' to кола. This time the ending is -та: колата.",
          after: "Кола**та** - a different article ending from кафе**то**. Just notice it for now.",
        },
        {
          type: "note",
          title: "There is / there isn't",
          body: "Bare **има** also means 'there is'; **няма** - 'there isn't':\n\n- **Има кафе.** - There's coffee.\n- **Има вино.** - There's wine. (**вино** = wine)\n- **Няма проблем!** - No problem! (You'll hear this ten times a day.)",
          speak: ["Има кафе.", "Има вино.", "Няма проблем!"],
        },
        {
          type: "exercise",
          prompt: "**There is no coffee.**",
          answer: "Няма кафе",
          hint: "Bare няма = 'there isn't'.",
        },
        {
          type: "exercise",
          prompt: "**I want the water.**",
          answer: "Искам водата",
          hint: "вода + -та = водата.",
          after: "Вода**та** - same -та ending as кола**та**.",
        },
        {
          type: "exercise",
          prompt: "How would you say **the wine**?",
          answer: "виното",
          hint: "вино is like кафе...",
          after: "Same ending as кафето. You already see the pattern.",
        },
        {
          type: "exercise",
          prompt: "**I want the wine.**",
          answer: "Искам виното",
          hint: "вино + -то = виното.",
          after: "Three articles and counting: кафе**то**, кола**та**, вино**то**. The pattern is building itself.",
        },
      ],
    },
    {
      id: "m2l3",
      title: "Speaking and understanding",
      subtitle: "говоря, разбирам, уча, работя",
      items: [
        {
          type: "note",
          title: "The и-family: говоря",
          body: "Second verb family. Same person markers, different linking vowel:\n\n- **говоря** (-я = I)\n- **говориш** (-иш = you)\n- **говори** (bare = he/she)\n\nThe -ш is still 'you' - just a different vowel gluing it to the stem.\n\nPlural: говорим, говорите, говорят.\n\nLanguages need no preposition: **Говоря английски** = I speak English.",
          speak: ["Говоря английски.", "говориш", "говори"],
        },
        {
          type: "exercise",
          prompt: "**I speak English.** (английски)",
          answer: "Говоря английски",
          hint: "говоря + английски, no preposition needed.",
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you speak Bulgarian?** (български)",
          answer: "Говориш ли български?",
          hint: "говориш + ли + български?",
        },
        {
          type: "exercise",
          prompt: "**She speaks English.**",
          answer: "Тя говори английски",
          accept: ["говори английски"],
          hint: "She-form: говори (bare stem).",
        },
        {
          type: "note",
          title: "The most useful sentence",
          body: "**Разбирам** = I understand - an а-family verb, so you already know all its forms from искам.\n\n**Не разбирам** may be the most useful sentence in this whole course. Say it without shame.",
          speak: ["Разбирам.", "Не разбирам."],
        },
        {
          type: "exercise",
          prompt: "**I don't understand.**",
          answer: "Не разбирам",
          hint: "не + разбирам.",
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you understand?**",
          answer: "Разбираш ли?",
          hint: "разбираш + ли?",
        },
        {
          type: "note",
          title: "Three small measuring words",
          body: "Three words you'll use constantly:\n\n- **малко** - a little\n- **много** - a lot / very\n- **добре** - well\n\n**Говоря малко български.** - the honest sentence of every learner.",
          speak: ["Говоря малко български.", "Говориш много добре!"],
        },
        {
          type: "exercise",
          prompt: "**I speak a little Bulgarian.**",
          answer: "Говоря малко български",
          hint: "говоря + малко + български.",
          after: "This one sentence will earn you so much goodwill in Bulgaria.",
        },
        {
          type: "note",
          title: "Two more и-family verbs",
          body: "Same drill, new words:\n\n- **уча** = I learn / I study (учиш, учи...)\n- **работя** = I work (работиш, работи...)\n\nAnd two connectors: **но** = but (comma before it), **днес** = today.",
          speak: ["Уча български.", "Работя днес.", "Разбирам, но не говоря."],
        },
        {
          type: "exercise",
          prompt: "**I'm learning Bulgarian.**",
          answer: "Уча български",
          hint: "Bulgarian present tense covers '-ing' too.",
        },
        {
          type: "exercise",
          prompt: "**I understand, but I don't speak.**",
          answer: "Разбирам, но не говоря",
          hint: "..., но не говоря. Comma before но.",
        },
        {
          type: "exercise",
          prompt: "**I'm working today.**",
          answer: "Работя днес",
          hint: "работя + днес.",
          after: "Present tense does double duty for 'I work' and 'I'm working'. One form, both jobs.",
        },
        {
          type: "exercise",
          prompt: "**Where is the hotel?** (where = къде)",
          answer: "Къде е хотелът?",
          hint: "къде = where. хотел + -ът = хотелът.",
          after: "Хотел**ът** - a third article ending, alongside кафе**то** and кола**та**. No need to sort them out yet. Just notice them.",
        },
        {
          type: "exercise",
          prompt: "**The restaurant is there.**",
          answer: "Ресторантът е там",
          hint: "ресторант + -ът = ресторантът.",
          after: "Same -ът as хотелът. These endings are choosing themselves.",
        },
        {
          type: "note",
          title: "Two verb families",
          body: "- **а-family**: искам, имам, разбирам - stem + -ам, -аш, -а...\n- **и-family**: говоря, уча, работя - stem + -я, -иш, -и...\n\nAnd three article shapes: кафе**то**, кола**та**, хотел**ът**. You haven't been told why each word gets a different one. But you're starting to feel it.",
        },
      ],
    },
    {
      id: "m2l4",
      title: "The missing 'to'",
      subtitle: "искам да говоря",
      items: [
        {
          type: "note",
          title: "Bulgarian threw away the infinitive",
          body: "There's no word for 'to' before a verb. Where English says 'I want **to speak**', Bulgarian says 'I want **that I-speak**':\n\n**Искам да говоря.**\n\n**Да** + a conjugated verb replaces every English 'to ___'. And both verbs agree with the subject - watch:\n\n- Иск**ам** да говор**я** (I want to speak)\n- Иска**ш** да говори**ш** (you want to speak)\n- Иска да говори (she wants to speak)\n\nThe verbs rhyme with each other. Let that rhythm guide you.",
          he: "Hebrew doesn't have infinitives either - אני רוצה לדבר uses a different approach (ל + verb). The idea of 'I want that-I-speak' should feel familiar.",
          ru: "Russian хочу говорить uses an infinitive - Bulgarian lost it entirely (a Balkan family trait shared with Greek and Romanian). Every инфинитив becomes да + conjugated verb.",
          speak: [
            "Искам да говоря.",
            "Искаш да говориш.",
            "Тя иска да говори.",
          ],
        },
        {
          type: "exercise",
          prompt: "**I want to speak Bulgarian.**",
          answer: "Искам да говоря български",
          hint: "искам + да + говоря.",
          after: "Both verbs in the I-form: иск**ам**, говор**я**. They have to match.",
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you want to speak English?**",
          answer: "Искаш ли да говориш английски?",
          hint: "Искаш ли + да + говориш...",
        },
        {
          type: "exercise",
          prompt: "**She wants to learn Bulgarian.**",
          answer: "Тя иска да учи български",
          accept: ["иска да учи български"],
          hint: "Both verbs in the she-form: иска, учи.",
        },
        {
          type: "choice",
          prompt: "**Искам да говоря** literally means...",
          options: [
            "I want that I-speak",
            "I want to speaking",
            "I want the speech",
          ],
          correct: 0,
          after:
            "Literally 'I want that I-speak'. The second verb is always conjugated, never frozen.",
        },
        {
          type: "note",
          title: "обичам and пътувам",
          body: "**Обичам** = I love - а-family, works for things, activities, and people.\n**Пътувам** = I travel - also а-family.\n\n- **Обичам кафе.**\n- **Обичам да пътувам.** - I love to travel.",
          speak: ["Обичам кафе.", "Обичам да пътувам."],
        },
        {
          type: "exercise",
          prompt: "**I love coffee.**",
          answer: "Обичам кафе",
          hint: "обичам + кафе - no да for a noun.",
        },
        {
          type: "exercise",
          prompt: "**I love to travel.**",
          answer: "Обичам да пътувам",
          hint: "обичам + да + пътувам.",
        },
        {
          type: "exercise",
          prompt: "**I want to understand.**",
          answer: "Искам да разбирам",
          hint: "искам + да + разбирам.",
          after: "Every а-family verb works the same way with да. And every и-family verb too.",
        },
        {
          type: "exercise",
          prompt: "**They want to work today.**",
          answer: "Те искат да работят днес",
          accept: ["искат да работят днес"],
          hint: "They-forms: искат, работят.",
        },
        {
          type: "exercise",
          prompt: "**I don't want the water.**",
          answer: "Не искам водата",
          accept: ["аз не искам водата"],
          hint: "вода + -та = водата.",
          after: "The articles keep showing up. You're handling them without thinking about it now.",
        },
        {
          type: "note",
          title: "Да is the glue",
          body: "From now on, whenever English hands you a 'to ___', your brain should output **да** + the verb, conjugated to match the subject. Искам **да** говоря. Обичам **да** пътувам.\n\nTwo verb families, three article shapes, and the да-construction. You're thinking in Bulgarian.",
        },
      ],
    },
  ],
};
