import type { Module } from "./types";

export const module5: Module = {
  id: "m5",
  title: "6. Time travel: future and past",
  blurb:
    "One little word for the future, one little sound for the past - and suddenly you can talk about yesterday and tomorrow.",
  lessons: [
    {
      id: "m5l1",
      title: "The future: ќе",
      subtitle: "Put ќе in front and you're done",
      items: [
        {
          type: "note",
          title: "The easiest future tense in Europe",
          body:
            "The Macedonian future is wonderfully simple. Put **ќе** before the present tense verb and you're done:\n\n- **Ќе одам.** - I will go.\n- **Ќе учам македонски.** - I will learn Macedonian.\n- **Ќе имам.** - I will have.\n\n**Ќе** never changes. It doesn't care who's speaking, how many people, anything. One word, one job - and it is perfectly happy to start a sentence.",
          speak: ["Ќе одам.", "Ќе учам македонски.", "Ќе имам."],
          introduces: ["future-ќе"],
          he: "Hebrew builds the future from scratch with new verb forms - אדבר, תדבר, ידבר. Macedonian just puts ќе in front of the present tense you already know. No new conjugation to learn.",
          ru: "Russian needs буду + infinitive or a perfective verb for the future. Macedonian has one particle for everything: ќе + the present you already own.",
          bg: "Bulgarian ще becomes ќе here (щ → ќ, one of the regular correspondences). Same job, same position: ще говоря → ќе зборувам.",
        },
        {
          type: "note",
          title: "утре - tomorrow",
          body:
            "New word: **утре** = tomorrow. You'll use it constantly with **ќе**.\n\n**Утре ќе одам.** - Tomorrow I will go.",
          speak: ["Утре.", "Утре ќе одам."],
          ru: "Утре is Russian утро (morning) with a twist: in Macedonian it means tomorrow. 'Morning' is утро - one letter apart.",
        },
        {
          type: "exercise",
          prompt: "How would you say: **I will go tomorrow**?",
          answer: "Ќе одам утре",
          accept: ["утре ќе одам", "јас ќе одам утре"],
          hint: "ќе + одам (I go) + утре (tomorrow).",
          after: "**Ќе одам утре.** Same verb form as the present - just ќе in front. Nothing else moved.",
          reviews: ["одам", "verb-и-group", "утре", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**You will speak Macedonian.**",
          answer: "Ќе зборуваш македонски",
          accept: ["ти ќе зборуваш македонски"],
          hint: "ќе + зборуваш (you speak).",
          after: "You kept the -ш that says 'you' and let ќе do the time travel. That is the whole trick.",
          reviews: ["зборувам", "verb-а-group", "македонски", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**Tomorrow we will learn Macedonian.**",
          answer: "Утре ќе учиме македонски",
          accept: ["ќе учиме македонски утре", "утре ние ќе учиме македонски"],
          hint: "утре + ќе + учиме (we learn).",
          reviews: ["учам", "verb-и-group", "македонски", "утре", "pronoun-drop"],
        },
        {
          type: "note",
          title: "The future of 'is': ќе биде",
          body:
            "**Сум** is the one verb that changes shape for the future. Instead of ќе + е, it borrows a special stem, **бид-**:\n\n- **Таа ќе биде тука.** - She will be here.\n- **Јас ќе бидам во Скопје.** - I will be in Skopje.\n\nThe endings are the ones you know: **ќе бидам**, **ќе бидеш**, **ќе биде**. For now, ќе биде (he / she / it) and ќе бидам (I) will carry you a long way.",
          speak: ["Таа ќе биде тука.", "Јас ќе бидам во Скопје."],
          ru: "Бид- is the same root as Russian буд- in буду, будет. The Macedonian version keeps ќе in front of it anyway.",
          bg: "Bulgarian lets you say ще е or ще бъде; the Macedonian standard is ќе биде (you will hear ќе е on the street, but write ќе биде).",
        },
        {
          type: "exercise",
          prompt: "**She will be here tomorrow.**",
          answer: "Таа ќе биде тука утре",
          accept: ["утре таа ќе биде тука", "ќе биде тука утре", "таа ќе биде утре тука"],
          hint: "таа + ќе биде + тука + утре.",
          after: "**Таа ќе биде тука утре.** You reached for биде instead of е - that is the only special case in the whole future tense.",
          reviews: ["pronoun-subject", "сум", "сум-present", "тука", "утре"],
        },
        {
          type: "exercise",
          prompt: "**Tomorrow I will be in Ohrid.**",
          answer: "Утре ќе бидам во Охрид",
          accept: ["ќе бидам во охрид утре", "утре јас ќе бидам во охрид"],
          hint: "утре + ќе бидам (I will be) + во Охрид.",
          after: "Бидам ends in -м like every I-form you know. The stem is new; the ending is an old friend.",
          reviews: ["сум", "во-in", "утре", "verb-м-first-person", "pronoun-drop"],
        },
        {
          type: "note",
          title: "The negative future: нема да",
          body:
            "'Won't' is **нема да** + present tense verb. Not 'не ќе' - forget that combination exists.\n\n- **Нема да одам.** - I won't go.\n- **Нема да работам утре.** - I won't work tomorrow.\n\n**Нема** already means 'there isn't' and 'doesn't have'. Here it takes a third job: 'won't'. It stays frozen as нема whoever is speaking - the verb after **да** does the changing.",
          speak: ["Нема да одам.", "Нема да работам утре."],
          introduces: ["future-neg"],
          he: "Think of it as 'there is no (that) I go' - the verb after да still carries the person, exactly like the verb after ש in Hebrew's אין ש.",
          bg: "Bulgarian няма да is нема да here (я → е). Same construction, same frozen нема.",
        },
        {
          type: "exercise",
          prompt: "**I won't work tomorrow.**",
          answer: "Нема да работам утре",
          accept: ["утре нема да работам"],
          hint: "won't = нема да + работам (I work) + утре.",
          after: "Нема stayed frozen and работам told us who. That division of labour never changes.",
          reviews: ["работам", "verb-и-group", "утре", "да-subjunctive"],
        },
        {
          type: "exercise",
          prompt: "**We won't have time.**",
          answer: "Нема да имаме време",
          accept: ["ние нема да имаме време"],
          hint: "нема да + имаме (we have) + време.",
          reviews: ["имам", "време", "future-neg", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Will you work tomorrow?**",
          answer: "Дали ќе работиш утре?",
          accept: ["ќе работиш ли утре"],
          hint: "дали up front, then the future sentence as it is.",
          after:
            "Questions work the same way as always: **Дали ќе работиш утре?** If you prefer ли, it sits right after the verb: Ќе работиш **ли** утре?",
          reviews: ["работам", "verb-и-group", "дали-question", "ли-question", "утре", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**They won't be here.**",
          answer: "Тие нема да бидат тука",
          accept: ["нема да бидат тука"],
          hint: "нема да + бидат (they will be - бид- with the they-ending -ат) + тука.",
          after: "Бидат: the бид- stem with the -ат you know from учат and работат. You built a form you had never seen.",
          reviews: ["pronoun-subject", "сум", "future-neg", "тука"],
        },
        {
          type: "note",
          title: "ќе and the little pronouns",
          body:
            "You know that **те**, **го**, **ја** and friends go before the verb. With **ќе**, the order is **ќе + pronoun + verb**:\n\n- **Ќе те чекам.** - I will wait for you.\n- **Ќе го гледам филмот.** - I will watch the film.\n\nAnd with нема да: **Нема да те чекам.** - I won't wait for you. The pronoun hugs the verb; ќе and нема да stand in front of the pair.",
          speak: ["Ќе те чекам.", "Ќе го гледам филмот.", "Нема да те чекам."],
          requires: ["clitic-proclitic", "clitic-doubling"],
          bg: "Bulgarian Ще те чакам looks identical - but note that the Macedonian pronoun still sits before the verb when there is no ќе: Те чекам, where Bulgarian says Чакам те.",
        },
        {
          type: "exercise",
          prompt: "**I will wait for you tomorrow.**",
          answer: "Ќе те чекам утре",
          accept: ["утре ќе те чекам"],
          hint: "ќе + те (you) + чекам (I wait) + утре.",
          after: "Те slipped between ќе and the verb - exactly where it belongs.",
          reviews: ["object-pronoun-sg", "clitic-proclitic", "чекам", "verb-а-group", "утре", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**She will wait for us.**",
          answer: "Таа ќе нѐ чека",
          accept: ["ќе нѐ чека"],
          hint: "таа + ќе + нѐ (us) + чека (she waits).",
          after: "Нѐ with its little accent - the one that keeps 'us' apart from 'not'.",
          reviews: ["pronoun-subject", "чекам", "verb-а-group", "object-pronoun-pl"],
        },
        {
          type: "exercise",
          prompt: "**I won't wait for him.**",
          answer: "Нема да го чекам",
          hint: "нема да + го (him) + чекам.",
          after: "Same slot as with ќе: the pronoun stays glued to the verb, нема да in front.",
          reviews: ["чекам", "verb-а-group", "object-pronoun-sg", "clitic-placement", "future-neg"],
        },
        {
          type: "exercise",
          prompt: "**I will watch the film.** (филм = film)",
          answer: "Ќе го гледам филмот",
          accept: ["ќе гледам филмот"],
          hint: "The film is definite - so go for the double: ќе + го + гледам + филмот.",
          after: "Doubling survives the trip into the future: definite object, so го shows up as well. If you skipped го, that is understood too - but the doubled version is the Macedonian one.",
          reviews: ["clitic-doubling", "гледам", "definite-masc", "object-pronoun-sg"],
        },
        {
          type: "exercise",
          prompt: "**I will wait for Marija tomorrow.**",
          answer: "Утре ќе ја чекам Марија",
          accept: ["ќе ја чекам марија утре", "утре ќе ја чекам марија"],
          hint: "A name is definite - double it with ја.",
          reviews: ["clitic-doubling", "чекам", "object-pronoun-sg", "утре"],
        },
        {
          type: "exercise",
          prompt: "**She won't be able to work tomorrow.**",
          answer: "Таа нема да може да работи утре",
          accept: ["нема да може да работи утре", "утре таа нема да може да работи"],
          hint: "нема да (won't) + може да работи (can work).",
          after: "Two да's in a row and it still reads naturally: нема да + може да + работи. Each verb after да carries 'she'.",
          reviews: ["pronoun-subject", "можам-word", "можам-conjugation", "да-subjunctive", "работам", "verb-и-group", "утре"],
        },
        {
          type: "exercise",
          prompt: "**I will have time.**",
          answer: "Ќе имам време",
          accept: ["јас ќе имам време"],
          hint: "ќе + имам + време (time).",
          after:
            "That's the entire future tense. **Ќе** for 'will', **нема да** for 'won't', **ќе биде** for 'will be', and the little pronouns between ќе and the verb.",
          reviews: ["имам", "време", "future-ќе", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**Will you have time tomorrow?**",
          answer: "Дали ќе имаш време утре?",
          accept: ["ќе имаш ли време утре", "дали утре ќе имаш време"],
          hint: "дали + ќе имаш + време + утре.",
          reviews: ["имам", "дали-question", "време", "утре", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**My father will be in Skopje tomorrow.**",
          answer: "Татко ми ќе биде во Скопје утре",
          accept: ["утре татко ми ќе биде во скопје", "татко ми утре ќе биде во скопје"],
          hint: "татко ми (no article on family words) + ќе биде + во Скопје + утре.",
          after: "Family word without an article, ми after it, then ќе биде. Module 4 and module 5 shaking hands.",
          reviews: ["татко", "family-article-drop", "dative-ми", "future-ќе", "во-in", "утре"],
        },
      ],
    },
    {
      id: "m5l2",
      title: "The past: -в",
      subtitle: "бев, имав, зборував, работев",
      items: [
        {
          type: "note",
          title: "I was: бев",
          body:
            "Your first past tense word: јас **бев** - I was.\n\nNew word: **вчера** = yesterday. You'll need it to talk about the past.\n\n**Бев таму вчера.** - I was there yesterday.",
          speak: ["Бев таму вчера."],
          introduces: ["past-бев"],
          he: "Hebrew הייתי - one word for 'I was', no pronoun needed. Бев works the same way.",
          ru: "Russian был/была changes for gender; Macedonian бев does not. One form for 'I was', whoever you are.",
          bg: "Bulgarian бях is бев here: я → е and the past-tense х → в. Keep that х → в in mind - it runs through the whole lesson.",
        },
        {
          type: "exercise",
          prompt: "**I was there yesterday.**",
          answer: "Бев таму вчера",
          accept: ["вчера бев таму", "јас бев таму вчера"],
          hint: "I was = бев; there = таму; yesterday = вчера.",
          after:
            "**Бев таму вчера.** The pronoun јас is optional - бев can only mean 'I was'.",
          reviews: ["таму", "вчера", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**I wasn't here.**",
          answer: "Не бев тука",
          accept: ["јас не бев тука"],
          hint: "не + бев + тука.",
          after: "Не goes straight in front, as always. No surprises in the past.",
          reviews: ["не-negation", "тука", "past-бев"],
        },
        {
          type: "exercise",
          prompt: "**I was here, right?**",
          answer: "Бев тука, нели?",
          accept: ["јас бев тука, нели"],
          hint: "бев + тука + нели.",
          reviews: ["тука", "нели-tag", "past-бев"],
        },
        {
          type: "note",
          title: "You / he / she was: беше",
          body:
            "For you, he, or she, 'was' is **беше**:\n\n- ти **беше** - you were\n- тој **беше** - he was\n- таа **беше** - she was\n\nOne form covers all three. **Таа беше тука.** - She was here.",
          speak: ["Таа беше тука."],
          bg: "Same as Bulgarian беше - one of the places the two languages simply agree.",
        },
        {
          type: "exercise",
          prompt: "**She was here.**",
          answer: "Таа беше тука",
          hint: "she was = таа беше.",
          reviews: ["pronoun-subject", "тука", "past-бев"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Were you there?**",
          answer: "Дали беше таму?",
          accept: ["беше ли таму", "дали ти беше таму", "ти беше ли таму"],
          hint: "дали + беше + таму.",
          after: "Because беше also means 'he was', the ти is welcome here if you want to be clear: Дали ти беше таму?",
          reviews: ["дали-question", "таму", "past-бев", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**My mother was here yesterday.**",
          answer: "Мајка ми беше тука вчера",
          accept: ["вчера мајка ми беше тука"],
          hint: "мајка ми (my mother) + беше (was) + тука вчера.",
          after: "Мајка ми - no article, ми right after. Then беше, because 'my mother' is a 'she'.",
          reviews: ["мајка", "family-article-drop", "dative-ми", "тука", "вчера"],
        },
        {
          type: "exercise",
          prompt: "**The weather was nice yesterday.**",
          answer: "Времето беше убаво вчера",
          accept: ["вчера времето беше убаво"],
          hint: "времето + беше + the neuter form of убав.",
          after: "Времето is an 'it', so убав took its -о ending - agreement doesn't switch off in the past.",
          reviews: ["време", "definite-neuter", "убав", "adj-agreement", "past-бев", "вчера"],
        },
        {
          type: "note",
          title: "The -в pattern: имав",
          body:
            "Every I-form in the present ends in **-м**: имам, сакам, зборувам. To go into the past, swap that **-м** for **-в**. Your first one: имам → **имав** (I had).\n\n**Имав проблем.** - I had a problem.\n\nHear the **в** at the end? That's the past tense signature. You'll hear it in every past form from now on.",
          speak: ["Имав.", "Имав проблем."],
          introduces: ["past-в"],
          he: "Like Hebrew, the ending does the work: היה לי is 'I had', with the 'I' baked in. Имав carries 'I' inside the -в.",
          ru: "Russian marks the past with -л: имел, имела. Macedonian uses -в for 'I': имав. Different ending, same idea - one sound marks the past.",
          bg: "Bulgarian имах, Macedonian имав. Every Bulgarian -х past ending you know turns into -в here.",
        },
        {
          type: "exercise",
          prompt: "**I had a problem.**",
          answer: "Имав проблем",
          accept: ["јас имав проблем"],
          hint: "had (I) = имав.",
          after:
            "**Имав** - you already knew имам. The -в just pushes it into the past.",
          reviews: ["имам", "past-в", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**I didn't have coffee.**",
          answer: "Немав кафе",
          hint: "didn't have (I) = немав. Fused, like немам.",
          after: "Немам → немав. The fused negative keeps its shape and just takes the -в.",
          reviews: ["немам", "немам-fused", "past-в"],
        },
        {
          type: "exercise",
          prompt: "**I had time yesterday.**",
          answer: "Вчера имав време",
          accept: ["имав време вчера"],
          hint: "имав + време (time); вчера (yesterday).",
          reviews: ["вчера", "имам", "време", "past-в"],
        },
        {
          type: "note",
          title: "Same swap: сакав, зборував",
          body:
            "The swap works on any verb whose I-form ends in -ам:\n\n- сакам → **сакав** - I wanted\n- зборувам → **зборував** - I spoke\n\n**Сакав кафе.** - I wanted coffee. **Зборував македонски.** - I spoke Macedonian.",
          speak: ["Сакав кафе.", "Зборував македонски."],
          bg: "Bulgarian исках / говорих; Macedonian сакав / зборував. Different verbs, and the -х is -в.",
        },
        {
          type: "exercise",
          prompt: "**I wanted coffee.**",
          answer: "Сакав кафе",
          hint: "wanted (I) = сакав.",
          reviews: ["сакам", "past-в"],
        },
        {
          type: "exercise",
          prompt: "**I wanted to go.**",
          answer: "Сакав да одам",
          hint: "сакав + да + одам.",
          after: "Only the first verb went into the past. After да, одам stays in the present - Macedonian says 'I wanted that I go'.",
          reviews: ["сакам", "да-subjunctive", "одам", "past-в"],
        },
        {
          type: "exercise",
          prompt: "**I spoke Macedonian yesterday.**",
          answer: "Вчера зборував македонски",
          accept: ["зборував македонски вчера"],
          hint: "spoke (I) = зборував; вчера = yesterday.",
          reviews: ["вчера", "зборувам", "македонски", "past-в"],
        },
        {
          type: "exercise",
          prompt: "**I waited for you.**",
          answer: "Те чекав",
          accept: ["јас те чекав"],
          hint: "те (you) + чекав (I waited). The pronoun keeps its place in front.",
          after: "Те чекав. The little pronoun sits before the verb in the past too - and it can still open the sentence.",
          reviews: ["чекам", "object-pronoun-sg", "clitic-proclitic", "past-в"],
          bg: "Bulgarian Чаках те; Macedonian Те чекав - pronoun first, even at the start of the sentence.",
        },
        {
          type: "note",
          title: "You / he / she in the past: -ше",
          body:
            "For ти, тој and таа, the past ending is **-ше** - the same sound you met in **беше**:\n\n- имам → **имаше** - you / he / she had\n- сакам → **сакаше** - you / he / she wanted\n\n**Таа сакаше кафе.** - She wanted coffee.",
          speak: ["Имаше.", "Таа сакаше кафе."],
          bg: "Same as Bulgarian имаше / искаше - the -ше form is shared.",
        },
        {
          type: "exercise",
          prompt: "**She wanted coffee.**",
          answer: "Таа сакаше кафе",
          accept: ["сакаше кафе"],
          hint: "таа + сакаше (she wanted) + кафе.",
          after: "Сакаше - the -ше you already trusted from беше, now on a different verb.",
          reviews: ["сакам", "pronoun-subject", "past-в"],
        },
        {
          type: "exercise",
          prompt: "**The tourist spoke English.** (турист = tourist, -ist → -ист)",
          answer: "Туристот зборуваше англиски",
          hint: "турист + -от = туристот. Then зборуваше (he spoke).",
          reviews: ["cognate-ист", "definite-masc", "зборувам", "past-в", "англиски"],
        },
        {
          type: "exercise",
          prompt: "**There was no water.**",
          answer: "Немаше вода",
          hint: "нема → немаше (past, he/she/it form). 'There wasn't.'",
          after: "Нема (there isn't) → немаше (there wasn't). The existential rides the same -ше.",
          reviews: ["има-existential", "немам", "вода", "past-в"],
        },
        {
          type: "note",
          title: "И-group and е-group verbs: работев",
          body:
            "Verbs whose you-form ends in **-иш** or **-еш** (работиш, учиш, можеш) take an **-е-** before the past endings:\n\n- работам → **работев** - I worked\n- учам → **учев** - I studied\n\nAnd for you / he / she: **работеше**, **учеше**. The -в and -ше are the same as before - only the vowel before them is е.",
          speak: ["Работев.", "Учев.", "Таа работеше тука."],
          introduces: ["past-и-е-group"],
          ru: "Russian работал keeps the -а- of работать; Macedonian работев switches to е. Watch that vowel.",
          bg: "Bulgarian работих / учих; Macedonian работев / учев. The и becomes е and the х becomes в.",
        },
        {
          type: "exercise",
          prompt: "**I worked a lot yesterday.**",
          answer: "Вчера работев многу",
          accept: ["работев многу вчера"],
          hint: "worked (I) = работев; многу = a lot.",
          after: "Работев - е before the в, because работам is an и-group verb (работиш).",
          reviews: ["вчера", "работам", "многу", "past-и-е-group"],
        },
        {
          type: "exercise",
          prompt: "**I didn't work yesterday.**",
          answer: "Не работев вчера",
          accept: ["вчера не работев"],
          hint: "не + работев + вчера.",
          reviews: ["не-negation", "работам", "вчера", "past-и-е-group"],
        },
        {
          type: "exercise",
          prompt: "**I studied Macedonian.**",
          answer: "Учев македонски",
          accept: ["јас учев македонски"],
          hint: "учам → учиш → so the past takes е: учев.",
          reviews: ["учам", "македонски", "past-и-е-group"],
        },
        {
          type: "exercise",
          prompt: "**She worked here.**",
          answer: "Таа работеше тука",
          accept: ["работеше тука"],
          hint: "работеше (she worked) - е before the -ше.",
          reviews: ["работам", "pronoun-subject", "тука", "past-и-е-group"],
        },
        {
          type: "note",
          title: "More е-past: одев, можев, живеев",
          body:
            "Every verb with -иш / -еш goes the same way:\n\n- одам → **одев** - I went\n- можам → **можев** - I could\n- живеам → **живеев** - I lived\n\n**Живеев во Охрид.** - I lived in Ohrid. **Не можев да работам.** - I couldn't work.",
          speak: ["Живеев во Охрид.", "Не можев да работам."],
        },
        {
          type: "exercise",
          prompt: "**I lived in Ohrid.**",
          answer: "Живеев во Охрид",
          accept: ["јас живеев во охрид"],
          hint: "живеам → живееш → живеев.",
          after: "Живеев: two е's in a row, and both are pronounced. No vowel goes quiet in Macedonian.",
          reviews: ["живеам", "во-in", "past-и-е-group", "verb-е-group"],
        },
        {
          type: "exercise",
          prompt: "**I couldn't work yesterday.**",
          answer: "Не можев да работам вчера",
          accept: ["вчера не можев да работам"],
          hint: "не + можев + да работам + вчера.",
          after: "Можев went into the past; работам after да stayed present. Same rule as сакав да одам.",
          reviews: ["можам-word", "можам-conjugation", "да-subjunctive", "работам", "вчера", "past-и-е-group"],
        },
        {
          type: "exercise",
          prompt: "**I was going to the city.**",
          answer: "Одев во градот",
          accept: ["јас одев во градот"],
          hint: "одам → одиш → одев; the city = градот.",
          reviews: ["одам", "град", "definite-masc", "во-in", "past-и-е-group"],
        },
        {
          type: "note",
          title: "We in the past: -вме",
          body:
            "For 'we', the ending is **-вме**: **имавме**, **бевме**, **работевме**. Same в, then the -ме you know from имаме and работиме.\n\n**Бевме во Охрид.** - We were in Ohrid. **Немавме време.** - We didn't have time.",
          speak: ["Бевме во Охрид.", "Немавме време."],
          introduces: ["past-вме"],
          bg: "Bulgarian -хме is -вме here: имахме → имавме, бяхме → бевме.",
        },
        {
          type: "exercise",
          prompt: "**We worked a lot.**",
          answer: "Работевме многу",
          accept: ["ние работевме многу", "многу работевме"],
          hint: "worked (we) = работевме; многу = a lot.",
          after: "Работев + ме. The е stayed, because работам is still an и-group verb whoever is doing it.",
          reviews: ["работам", "многу", "past-вме", "past-и-е-group"],
        },
        {
          type: "exercise",
          prompt: "**We didn't have time.**",
          answer: "Немавме време",
          hint: "didn't have (we) = немавме (-вме for 'we').",
          reviews: ["немам", "време", "past-вме"],
        },
        {
          type: "exercise",
          prompt: "**Yesterday we were in Ohrid.**",
          answer: "Вчера бевме во Охрид",
          accept: ["бевме во охрид вчера", "вчера ние бевме во охрид"],
          hint: "бев + ме = we were.",
          reviews: ["сум", "past-бев", "во-in", "вчера", "past-вме"],
        },
        {
          type: "exercise",
          prompt: "**We spoke Macedonian.**",
          answer: "Зборувавме македонски",
          accept: ["ние зборувавме македонски"],
          hint: "spoke (we) = зборувавме; -вме for 'we'.",
          reviews: ["зборувам", "македонски", "past-вме"],
        },
        {
          type: "exercise",
          prompt: "**I worked a lot, but we didn't have time.**",
          answer: "Работев многу, но немавме време",
          accept: ["работев многу, ама немавме време"],
          hint: "-в for I, -вме for we.",
          after: "Two past forms in one breath, and но stitching them together.",
          reviews: ["работам", "многу", "но-but", "немам", "време", "past-вме"],
        },
        {
          type: "note",
          title: "You all in the past: -вте",
          body:
            "For вие, the past ending is **-вте**: **бевте**, **имавте**, **работевте**. The -те is the one from имате and работите.\n\n**Дали бевте таму?** - Were you (all) there?",
          speak: ["Дали бевте таму?"],
          bg: "Bulgarian -хте → Macedonian -вте: бяхте → бевте.",
        },
        {
          type: "exercise",
          prompt: "Ask a group: **Were you there yesterday?**",
          answer: "Дали бевте таму вчера?",
          accept: ["бевте ли таму вчера", "дали вие бевте таму вчера", "вчера дали бевте таму"],
          hint: "дали + бевте + таму + вчера.",
          reviews: ["сум", "past-бев", "дали-question", "таму", "вчера", "past-вме"],
        },
        {
          type: "exercise",
          prompt: "**Did you (all) have a problem?**",
          answer: "Дали имавте проблем?",
          accept: ["имавте ли проблем", "дали вие имавте проблем"],
          hint: "имав + те.",
          reviews: ["имам", "дали-question", "past-вме"],
        },
        {
          type: "note",
          title: "They in the past: -а",
          body:
            "For тие, the past ending is just **-а**: **беа**, **имаа**, **сакаа**, **работеа**.\n\nLook at **сакаа**: it's the present сакаат with the т gone. Double а, and both are pronounced.\n\n**Тие беа тука.** - They were here.",
          speak: ["Тие беа тука.", "Сакаа кафе."],
          bg: "Bulgarian бяха / имаха; Macedonian беа / имаа - the х simply drops for 'they'.",
        },
        {
          type: "exercise",
          prompt: "**They were here.**",
          answer: "Тие беа тука",
          accept: ["беа тука"],
          hint: "they were = тие беа.",
          reviews: ["сум", "past-бев", "pronoun-subject", "тука"],
        },
        {
          type: "exercise",
          prompt: "**They wanted coffee.**",
          answer: "Тие сакаа кафе",
          accept: ["сакаа кафе"],
          hint: "сакаат minus the т.",
          after: "Сакаа. If you said сакаат, you stayed in the present - drop the т to step back in time.",
          reviews: ["сакам", "verb-а-group", "past-вме", "pronoun-subject"],
        },
        {
          type: "note",
          title: "сега - now",
          body:
            "One more time word: **сега** = now. Useful for contrasting past and present.\n\n**Сега сум тука.** - Now I am here.",
          speak: ["Сега сум тука."],
          ru: "Сега is not Russian сейчас - different word, same meaning. Don't reach for сейчас; nobody will understand it.",
        },
        {
          type: "exercise",
          prompt: "**Now he is here. Yesterday he was there.**",
          answer: "Сега тој е тука. Вчера тој беше таму.",
          accept: [
            "сега тој е тука, вчера беше таму",
            "сега тој е тука, вчера тој беше таму",
            "сега тој е тука. вчера беше таму.",
          ],
          hint: "сега = now (present tense), вчера = yesterday (past tense).",
          after:
            "Present and past side by side - сега... е, вчера... беше. You're already travelling in time.",
          reviews: ["сега", "pronoun-subject", "сум-present", "тука", "вчера", "таму", "past-бев"],
        },
        {
          type: "exercise",
          prompt: "**Now I am here.**",
          answer: "Сега сум тука",
          accept: ["сега јас сум тука", "јас сум тука сега", "сум тука сега"],
          hint: "сега (now) + сум (I am) + тука (here).",
          after: "Back to the present - no бев, no -в. Сега is your cue.",
          reviews: ["сега", "сум-present", "сум-position", "тука"],
        },
        {
          type: "exercise",
          prompt: "**I felt well yesterday.**",
          answer: "Вчера се чувствував добро",
          accept: ["се чувствував добро вчера"],
          hint: "се чувствувам → се чувствував (past). Се stays in front of the verb.",
          after: "Се kept its place before the verb, and the verb took its -в. Two rules, no conflict.",
          reviews: ["чувствувам", "reflexive-се", "verb-а-group", "вчера", "добро", "past-в"],
        },
        {
          type: "exercise",
          prompt: "**I didn't have bread.**",
          answer: "Немав леб",
          hint: "немам → немав (past). Fused negation - not 'не имав'.",
          reviews: ["немам-fused", "леб", "past-в", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**We traveled a lot.**",
          answer: "Патувавме многу",
          accept: ["ние патувавме многу"],
          hint: "Same -в as патував, but for 'we'.",
          reviews: ["past-вме", "патувам", "многу", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**She was waiting for me.**",
          answer: "Таа ме чекаше",
          accept: ["ме чекаше"],
          hint: "ме (me) before чекаше (she waited).",
          after: "Ме чекаше - pronoun, then the -ше verb. The past changed nothing about where the little words live.",
          reviews: ["чекам", "object-pronoun-sg", "clitic-proclitic", "past-в", "pronoun-subject"],
        },
        {
          type: "exercise",
          prompt: "**I watched the film yesterday.**",
          answer: "Вчера го гледав филмот",
          accept: ["го гледав филмот вчера", "вчера гледав филмот"],
          hint: "Definite film - double it: го + гледав + филмот.",
          after: "Го гледав филмот. Doubling in the past, doubling in the future, doubling in the present. It is one rule, not three.",
          reviews: ["гледам", "clitic-doubling", "definite-masc", "вчера", "past-в"],
        },
        {
          type: "note",
          title: "You now travel in time",
          body:
            "Present, future (**ќе**), past (**-в**). Here is the whole past tense you just built, now that you have used every piece of it:\n\n- јас -**в** (имав, работев)\n- ти / тој / таа -**ше** (имаше, работеше)\n- ние -**вме** (имавме, работевме)\n- вие -**вте** (имавте, работевте)\n- тие -**а** (имаа, работеа)\n\nAnd **бев, беше, бевме, бевте, беа** for 'was'. Every new verb you learn from now on comes with a free past tense. That's compounding knowledge, and it's why this gets easier, not harder.",
          speak: ["Имав, имаше, имавме, имавте, имаа."],
          reviews: ["past-в", "past-и-е-group", "past-вме", "past-бев"],
        },
      ],
    },
    {
      id: "m5l3",
      title: "Time mixing",
      subtitle: "Past, present, future - choosing the right one",
      items: [
        {
          type: "note",
          title: "No new grammar",
          body:
            "This lesson starts with nothing new. Every word, every verb form - you know it all already. The challenge is picking the right tense when all three are on the table at once.\n\nListen for the cues: **вчера** points back, **сега** and **денес** stay put, **утре** points ahead.\n\nThis is deliberately harder than the previous two lessons. When you only had one tense to practise, you couldn't pick the wrong one. Now you can. That's the point.",
        },
        {
          type: "exercise",
          prompt: "**I speak Macedonian.**",
          answer: "Зборувам македонски",
          accept: ["јас зборувам македонски"],
          hint: "Plain present tense - no ќе, no -в.",
          reviews: ["зборувам", "verb-а-group", "македонски", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**I spoke Macedonian yesterday.**",
          answer: "Вчера зборував македонски",
          accept: ["зборував македонски вчера"],
          hint: "Past - зборував (not зборувам).",
          reviews: ["past-в", "вчера", "зборувам", "македонски", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**I will speak Macedonian tomorrow.**",
          answer: "Утре ќе зборувам македонски",
          accept: ["ќе зборувам македонски утре"],
          hint: "Future - ќе + present verb.",
          after:
            "Three sentences, three tenses, same verb. You didn't hesitate on the verb itself - only on the time frame. That's the whole game now.",
          reviews: ["утре", "future-ќе", "зборувам", "verb-а-group", "македонски", "pronoun-drop"],
        },
        {
          type: "choice",
          prompt: "**Таа беше тука** means...",
          options: [
            "She was here.",
            "She is here.",
            "She will be here.",
          ],
          correct: 0,
          after:
            "**Беше** is past - 'was'. Present would be **е**, future would be **ќе биде**.",
          reviews: ["past-бев", "сум-present", "future-ќе"],
        },
        {
          type: "exercise",
          prompt: "**She is here now.**",
          answer: "Таа е тука сега",
          accept: ["сега таа е тука"],
          hint: "Present tense. сега = now.",
          reviews: ["pronoun-subject", "сум-present", "тука", "сега"],
        },
        {
          type: "exercise",
          prompt: "**She will be here tomorrow.**",
          answer: "Таа ќе биде тука утре",
          accept: ["утре таа ќе биде тука", "ќе биде тука утре"],
          hint: "Future - ќе биде.",
          reviews: ["pronoun-subject", "future-ќе", "сум", "тука", "утре"],
        },
        {
          type: "note",
          title: "Saying goodbye: довидување",
          body:
            "**Довидување** - goodbye. It is built from **до** (until) + **видување** (seeing) - 'until seeing'. Same logic as French *au revoir*.",
          speak: ["Довидување."],
          ru: "Exactly the idea of до свидания - 'until the seeing'. The Macedonian word just packs it into one.",
          bg: "Bulgarian довиждане; Macedonian довидување. Same 'until seeing', different suffix - and no жд.",
        },
        {
          type: "exercise",
          prompt: "**Goodbye! I'm going.**",
          answer: "Довидување! Одам.",
          accept: ["довидување, одам", "довидување! јас одам."],
          hint: "The farewell, then the plain present of одам.",
          after: "Одам - present tense, because you're going right now. No ќе needed.",
          reviews: ["довидување", "одам", "verb-и-group", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**Goodbye, I will be here tomorrow.**",
          answer: "Довидување, утре ќе бидам тука",
          accept: ["довидување, ќе бидам тука утре"],
          hint: "довидување + утре + ќе бидам + тука.",
          reviews: ["довидување", "future-ќе", "сум", "тука", "утре"],
        },
        {
          type: "note",
          title: "Good evening: добра вечер",
          body:
            "**Добра вечер** - good evening. **Вечер** (evening) is feminine, so the adjective is **добра**, the same form you'd use with кола or куќа.\n\nCompare **добар ден** (masculine) and **добро утро** (neuter): three greetings, three genders, one adjective doing what adjectives do.",
          speak: ["Добра вечер."],
          he: "In Hebrew ערב is masculine (ערב טוב). Here вечер is feminine, so добра - the -а you know from feminine adjectives.",
          ru: "Russian вечер is masculine (добрый вечер). Macedonian вечер is feminine - hence добра. A trap for Russian speakers.",
          bg: "Bulgarian добър вечер treats вечер as masculine; Macedonian вечер is feminine, so it is добра вечер.",
        },
        {
          type: "exercise",
          prompt: "**Good evening! How are you?**",
          answer: "Добра вечер! Како си?",
          accept: ["добра вечер, како си"],
          hint: "The greeting, then the question from module 4.",
          reviews: ["добра вечер", "како-how", "сум-present"],
        },
        {
          type: "exercise",
          prompt: "**Good evening. I am Marko.**",
          answer: "Добра вечер. Јас сум Марко.",
          accept: ["добра вечер, јас сум марко", "добра вечер. марко сум.", "добра вечер, марко сум"],
          hint: "добра вечер + јас сум + Марко.",
          reviews: ["добра вечер", "сум-present", "сум-position", "pronoun-subject"],
        },
        {
          type: "choice",
          prompt: "Why is it **добра** вечер, not добар вечер?",
          options: [
            "Because вечер is feminine.",
            "Because it is a greeting.",
            "Because вечер is plural.",
          ],
          correct: 0,
          after:
            "Вечер is feminine, so the adjective ends in -а. The greeting simply follows the rule you learned with нова кола.",
          reviews: ["добра вечер", "adj-agreement", "noun-gender"],
        },
        {
          type: "note",
          title: "Good night: добра ноќ",
          body:
            "**Добра ноќ** - good night. **Ноќ** (night) is feminine too, so again **добра**. Notice the **ќ** at the end - one of the four Macedonian letters from module 0.",
          speak: ["Добра ноќ."],
          ru: "Russian ночь is feminine as well, so добра feels right. Only the wording differs: спокойной ночи there, добра ноќ here.",
          bg: "Bulgarian says лека нощ; Macedonian says добра ноќ (щ → ќ). Different adjective, same feminine agreement.",
        },
        {
          type: "exercise",
          prompt: "**Good night! Goodbye!**",
          answer: "Добра ноќ! Довидување!",
          accept: ["добра ноќ, довидување"],
          hint: "Two farewells.",
          reviews: ["добра ноќ", "довидување"],
        },
        {
          type: "exercise",
          prompt: "**Good night. Tomorrow I will work.**",
          answer: "Добра ноќ. Утре ќе работам.",
          accept: ["добра ноќ, утре ќе работам", "добра ноќ. ќе работам утре."],
          hint: "добра ноќ + утре + ќе работам.",
          reviews: ["добра ноќ", "future-ќе", "работам", "утре"],
        },
        {
          type: "exercise",
          prompt:
            "**Yesterday I worked, now I am studying, and tomorrow I will speak Macedonian.**",
          answer:
            "Вчера работев, сега учам и утре ќе зборувам македонски",
          accept: [
            "вчера работев, сега учам, и утре ќе зборувам македонски",
          ],
          hint: "Three clauses: вчера + past, сега + present, утре + future.",
          after:
            "That sentence used three tenses. Read it again - you built that.",
          reviews: ["вчера", "работам", "past-и-е-group", "сега", "учам", "verb-и-group", "и-conjunction", "утре", "future-ќе", "зборувам", "македонски", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**The weather is nice today.**",
          answer: "Времето е убаво денес",
          accept: ["денес времето е убаво"],
          hint: "времето + е + the neuter form of убав.",
          reviews: ["убав", "adj-agreement", "време", "definite-neuter", "сум-present", "денес"],
        },
        {
          type: "exercise",
          prompt: "**Yesterday the weather was nice, and tomorrow it will be nice.**",
          answer: "Вчера времето беше убаво, и утре ќе биде убаво",
          accept: ["вчера времето беше убаво и утре ќе биде убаво", "времето беше убаво вчера, и утре ќе биде убаво"],
          hint: "беше for yesterday, ќе биде for tomorrow.",
          after: "Беше... ќе биде. The same 'it' verb, wearing two different times.",
          reviews: ["past-бев", "future-ќе", "време", "убав", "вчера", "утре", "и-conjunction"],
        },
        {
          type: "exercise",
          prompt: "**I waited for you yesterday. Tomorrow you will wait for me.**",
          answer: "Вчера те чекав. Утре ти ќе ме чекаш.",
          accept: ["вчера те чекав. утре ќе ме чекаш.", "вчера те чекав, утре ќе ме чекаш", "те чекав вчера. утре ти ќе ме чекаш."],
          hint: "те чекав (I waited for you); ќе ме чекаш (you will wait for me).",
          after: "Те before чекав, ме between ќе and чекаш. The little pronouns never leave the verb's side.",
          reviews: ["чекам", "object-pronoun-sg", "clitic-proclitic", "past-в", "future-ќе", "вчера", "утре"],
        },
        {
          type: "exercise",
          prompt: "**Yesterday we were in Ohrid, today we are in Skopje.**",
          answer: "Вчера бевме во Охрид, денес сме во Скопје",
          accept: ["вчера бевме во охрид, а денес сме во скопје", "вчера бевме во охрид, денес ние сме во скопје"],
          hint: "бевме (we were), сме (we are).",
          reviews: ["past-бев", "past-вме", "сум-present", "во-in", "вчера", "денес"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you have time now?**",
          answer: "Дали имаш време сега?",
          accept: ["имаш ли време сега", "дали сега имаш време", "сега дали имаш време"],
          hint: "дали + имаш + време + сега.",
          reviews: ["дали-question", "имам", "време", "сега"],
        },
        {
          type: "exercise",
          prompt: "**My mother will be here tomorrow, right?**",
          answer: "Мајка ми ќе биде тука утре, нели?",
          accept: ["утре мајка ми ќе биде тука, нели"],
          hint: "мајка ми + ќе биде + тука + утре + нели.",
          reviews: ["мајка", "family-article-drop", "future-ќе", "сум", "нели-tag", "утре"],
        },
        {
          type: "exercise",
          prompt: "**Good evening! Do you want coffee?**",
          answer: "Добра вечер! Дали сакаш кафе?",
          accept: ["добра вечер! сакаш ли кафе?", "добра вечер, дали сакаш кафе", "добра вечер, сакаш ли кафе"],
          hint: "The greeting, then a дали question.",
          reviews: ["добра вечер", "дали-question", "сакам", "verb-а-group"],
        },
        {
          type: "note",
          title: "Three times, one you",
          body:
            "Yesterday, today, tomorrow - **вчера**, **денес**, **утре** - and you can put a verb into each of them. From here on, every verb you meet arrives with its past and its future already attached: swap the ending for the past, put **ќе** in front for the future.\n\n**Добра ноќ. Довидување.**",
          speak: ["Добра ноќ. Довидување."],
        },
      ],
    },
  ],
};
