import type { Module } from "./types";

export const module0: Module = {
  id: "m0",
  title: "1. Reading Macedonian",
  blurb:
    "Learn to read Cyrillic in five lessons. You already know more letters than you think - and four of them exist in no other alphabet.",
  lessons: [
    {
      id: "m0l1",
      title: "The letters you recognize",
      subtitle: "Nine letters in ten minutes",
      items: [
        {
          type: "note",
          title: "You've done this before",
          body:
            "Half of Cyrillic looks like Latin letters. The other half you can learn in an evening. Five short lessons and you'll be reading Macedonian - the last lesson is for four letters that only Macedonian has.\n\nThis module is optional if you already read Cyrillic (Russian or Bulgarian speakers, for example) - but do look at the last lesson.",
          he: "You already read one non-Latin script fluently. Cyrillic will come quickly.",
          bg: "If you read Bulgarian, skim lessons 1-4 and do lesson 5 properly: that is where the letters you have never seen live (ќ ѓ ѕ џ, plus ј љ њ in lessons 3 and 4).",
        },
        {
          type: "note",
          title: "Six letters you already know",
          body:
            "These six Cyrillic letters look and sound exactly like their English counterparts:\n\n**А** = a, **Е** = e, **К** = k, **М** = m, **О** = o, **Т** = t\n\nThat's enough to read real words.",
          introduces: ["cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "What does **МАМА** say?",
          options: ["mama", "nana", "tama"],
          correct: 0,
          after: "Мама - same word, same letters. You already read Cyrillic.",
          speak: "мама",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "Read this word: **АТОМ**",
          options: ["atom", "aton", "atok"],
          correct: 0,
          after: "Атом - four letters, all ones you know.",
          speak: "атом",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "And **ТЕМА**?",
          options: ["tema", "teka", "mota"],
          correct: 0,
          after: "Тема - theme, topic. Four letters, all ones you know.",
          speak: "тема",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "note",
          title: "Now type it",
          body:
            "You can read these words. Now let's write them. When you type Latin letters, they convert to Cyrillic automatically:\n\nm → м, a → а, t → т, o → о, e → е, k → к\n\nFor these six letters, typing is trivial - the Latin letter IS the Cyrillic letter.",
          introduces: ["cyrillic-typing"],
        },
        {
          type: "exercise",
          prompt: "Type **мама** (mama).",
          answer: "мама",
          hint: "Type m-a-m-a. Each letter converts as you type.",
          after: "You just wrote your first word in Cyrillic.",
          reviews: ["cyrillic-typing"],
        },
        {
          type: "exercise",
          prompt: "Type **атом** (atom).",
          answer: "атом",
          hint: "a-t-o-m.",
          reviews: ["cyrillic-typing", "cyrillic-reading"],
        },
        {
          type: "note",
          title: "Three more easy ones",
          body:
            "These three look slightly different but are easy to remember:\n\n**С** = s (looks like C but sounds like S) - type **s**\n**И** = i (looks like a backwards N) - type **i**\n**У** = u (looks like Y but sounds like 'oo') - type **u**\n\nThat gives you 9 letters - almost a third of the alphabet.",
        },
        {
          type: "choice",
          prompt: "Read this: **ТАКСИ**",
          options: ["takni", "taksi", "takci"],
          correct: 1,
          after: "Такси - taxi. С sounds like S (even though it looks like C), and И sounds like I (even though it looks like N).",
          speak: "такси",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "Read: **МАСКА**",
          options: ["macka", "maska", "naska"],
          correct: 1,
          after: "Маска - mask. С is S not C, and И is I not N.",
          speak: "маска",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "A harder one: **КОСМОС**",
          options: ["kosmos", "kocmoc", "kosmoc"],
          correct: 0,
          after: "Космос - cosmos. Nine letters and you're reading real words.",
          speak: "космос",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "exercise",
          prompt: "Type **такси** (taxi).",
          answer: "такси",
          hint: "t-a-k-s-i. Remember С is typed as 's'.",
          after: "С looks like C but you type 's'. That's the only twist so far.",
          reviews: ["cyrillic-typing"],
        },
        {
          type: "exercise",
          prompt: "Type **сума** (sum, amount).",
          answer: "сума",
          hint: "s-u-m-a. У is typed as 'u', not 'y'.",
          after: "You typed the sound, not the shape: 'u' for the letter that looks like Y.",
          reviews: ["cyrillic-typing"],
        },
        {
          type: "exercise",
          prompt: "Type **космос** (cosmos).",
          answer: "космос",
          hint: "k-o-s-m-o-s.",
          after: "Six letters, typed as fast as English. Reading and writing - both working.",
          reviews: ["cyrillic-typing", "cyrillic-reading"],
        },
        {
          type: "note",
          body:
            "Nine letters down, and you can already read and type маска, такси, космос, тим (team). The next lesson covers the tricky ones - letters that look like Latin letters but have different sounds.",
          speak: ["маска", "такси", "космос", "тим"],
        },
      ],
    },
    {
      id: "m0l2",
      title: "The imposters",
      subtitle: "Letters that look familiar but aren't",
      items: [
        {
          type: "note",
          title: "The hard part",
          body:
            "Three Cyrillic letters look like Latin letters but make completely different sounds. This is the hardest part of learning to read Cyrillic - you'll misread them for about a week, then it becomes automatic.\n\n**В** = v (looks like B, sounds like V) - type **v** (or **w**)\n**Н** = n (looks like H, sounds like N) - type **n**\n**Р** = r (looks like P, sounds like R) - type **r**\n\nThe typing actually helps here - you type the SOUND, not the SHAPE. Type 'v' even though it looks like B.",
          ru: "For Russian speakers these are obvious - this is the main lesson you can skip.",
        },
        {
          type: "choice",
          prompt: "The letter **В** in Cyrillic sounds like...",
          options: ["b", "v", "w"],
          correct: 1,
          after: "В = v. It looks like B but it's V. This is the biggest imposter.",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "Read **ВИНО**. What does it say?",
          options: ["bino", "vino", "biho"],
          correct: 1,
          after: "Вино - wine. В is V, not B. Н is N, not H.",
          speak: "вино",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "exercise",
          prompt: "Type **вино** (wine).",
          answer: "вино",
          hint: "v-i-n-o. Type 'v' for В (not 'b'!) and 'n' for Н (not 'h'!).",
          after: "Your fingers learn the sound, not the shape. That's why typing helps beat the imposters.",
          reviews: ["cyrillic-typing"],
        },
        {
          type: "choice",
          prompt: "The letter **Н** sounds like...",
          options: ["h", "n", "m"],
          correct: 1,
          after: "Н = n. It looks like H but it's N.",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "Read **НОТА**.",
          options: ["hota", "nota", "noma"],
          correct: 1,
          after: "Нота - a musical note. Н is N (not H).",
          speak: "нота",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "The letter **Р** sounds like...",
          options: ["p", "r", "d"],
          correct: 1,
          after: "Р = r. Looks like P, sounds like R.",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "Read **МОРЕ**.",
          options: ["mope", "more", "mora"],
          correct: 1,
          after: "Море - sea. Р is R, not P. Your first everyday Macedonian word that isn't international.",
          speak: "море",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "Now all three at once. Read **НОРМА**.",
          options: ["horma", "norma", "hopma"],
          correct: 1,
          after: "Норма - norm. Н is N (not H), Р is R (not P), and the М is just M.",
          speak: "норма",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "exercise",
          prompt: "Type **метро** (metro).",
          answer: "метро",
          hint: "m-e-t-r-o. Р is typed as 'r' - type the sound.",
          after: "Р looks like P, but your fingers typed 'r'. That is the habit we want.",
          reviews: ["cyrillic-typing"],
        },
        {
          type: "exercise",
          prompt: "Type **рака** (hand).",
          answer: "рака",
          hint: "r-a-k-a.",
          after: "Рака - hand. A short, real word, and the imposter Р at the front didn't fool you.",
          reviews: ["cyrillic-typing", "cyrillic-reading"],
        },
        {
          type: "note",
          title: "One more: Х",
          body:
            "**Х** = h (a soft sound, like clearing your throat gently) - type **h** (or **x**)\n\nThis one doesn't have a Latin lookalike problem - it looks like X, but nothing in Macedonian sounds like 'ks', so it's just a new letter for a familiar sound.",
          he: "Х sounds like כ in כל. Same gentle throat sound.",
        },
        {
          type: "choice",
          prompt: "Read: **ЕХО**",
          options: ["eho", "exo", "eko"],
          correct: 0,
          after: "Ехо - echo. Х is H.",
          speak: "ехо",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "Read: **ХОР**",
          options: ["hop", "hor", "xor"],
          correct: 1,
          after: "Хор - choir. Х is H, and the Р at the end is R (not P!).",
          speak: "хор",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "Putting it all together: read **СЕРВИС**.",
          options: ["sepvis", "sepbic", "servis"],
          correct: 2,
          after: "Сервис - service. С=s, Е=e, Р=r (not P!), В=v (not B!), И=i, С=s.",
          speak: "сервис",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "Read: **ИНТЕРНЕТ**",
          options: ["ihtepnet", "internet", "intepnet"],
          correct: 1,
          after: "Интернет - internet. Both Н letters are N, and the Р is R. Getting easier.",
          speak: "интернет",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "exercise",
          prompt: "Type **сервис** (service).",
          answer: "сервис",
          hint: "s-e-r-v-i-s. Every imposter is here: Р='r', В='v'.",
          after: "All the imposters in one word, typed by sound. The keyboard reinforces what your eyes are still learning.",
          reviews: ["cyrillic-typing", "cyrillic-reading"],
        },
        {
          type: "note",
          body:
            "Thirteen letters. You can now read вино, море, метро and интернет - and хотел is one letter away. Next lesson: six letters with brand-new shapes but sounds you already know, and the letter that makes the 'y' sound.",
          speak: ["вино", "море", "метро", "интернет"],
        },
      ],
    },
    {
      id: "m0l3",
      title: "New shapes",
      subtitle: "Six letters with familiar sounds, and Ј",
      items: [
        {
          type: "note",
          title: "New shapes, familiar sounds",
          body:
            "The next six letters make sounds you already know from English. The shapes are new, but you'll pick them up fast because the sounds are familiar. Then one more, for the 'y' in 'yes'.\n\nWe'll take them one at a time.",
        },
        {
          type: "note",
          title: "П = p",
          body:
            "**П** looks like a doorframe (or Greek pi). Since Р already took the P-shape for the R sound, Cyrillic uses П for the actual P sound.\n\nП = p, every time.",
        },
        {
          type: "choice",
          prompt: "Read: **ПАРК**",
          options: ["park", "papk", "rark"],
          correct: 0,
          after: "Парк - park. П is P, and remember Р is R (not P).",
          speak: "парк",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "exercise",
          prompt: "Type **парк** (park).",
          answer: "парк",
          hint: "p-a-r-k. П is 'p', Р is 'r'.",
          after: "П='p' and Р='r' - the keyboard helps keep them separate.",
          reviews: ["cyrillic-typing"],
        },
        {
          type: "note",
          title: "Б = b",
          body:
            "**Б** is the real B sound. Remember, В *looks* like B but sounds like V - so Cyrillic needed a different letter for the actual B sound. That's Б.\n\nБ = b.",
        },
        {
          type: "choice",
          prompt: "Read: **БАНКА**",
          options: ["banka", "vanka", "bahka"],
          correct: 0,
          after: "Банка - bank. Б is the real B (В is V, not B), and Н is N.",
          speak: "банка",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "note",
          title: "Д = d",
          body:
            "**Д** looks like a little tent or triangle. It's simply the D sound.\n\nД = d.",
        },
        {
          type: "choice",
          prompt: "Read: **ДОКТОР**",
          options: ["doktop", "doktor", "roktod"],
          correct: 1,
          after: "Доктор - doctor. Д is D, and the Р at the end is R (not P).",
          speak: "доктор",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "note",
          title: "Г = g",
          body:
            "**Г** looks like an upside-down L (or Greek gamma). It's always a hard G, as in 'go' - never soft like in 'gem'.\n\nГ = g (hard).",
        },
        {
          type: "choice",
          prompt: "Read: **ГРАД**",
          options: ["grad", "gpad", "darg"],
          correct: 0,
          after: "Град - city (the '-grad' in Belgrade). Г is hard G, Д is D. One thing to know once: at the very end of a word, Macedonian un-voices the consonant, so град is *said* 'grat' and леб (bread) is said 'lep'. You write д and б; you hear т and п.",
          speak: "град",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "exercise",
          prompt: "Type **град** (city).",
          answer: "град",
          hint: "g-r-a-d. Spell it as written, with д - even though you hear a 't'.",
          after: "Written град, said 'grat'. Spelling follows the word's family (градови, cities, has a clear д), not the last sound.",
          reviews: ["cyrillic-typing"],
        },
        {
          type: "note",
          title: "Л = l",
          body:
            "**Л** looks like Д's sibling - similar triangular shape (or think of Greek lambda). It's the L sound.\n\nЛ = l.",
        },
        {
          type: "choice",
          prompt: "Read: **ЛИМОН**",
          options: ["limon", "dimon", "limoh"],
          correct: 0,
          after: "Лимон - lemon. Л is L (not Д), and Н is N (not H).",
          speak: "лимон",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "Read: **ХОТЕЛ**",
          options: ["hotel", "xoted", "kotel"],
          correct: 0,
          after: "Хотел - hotel. Х is H, and the Л at the end is L. Last lesson this word was one letter out of reach; not any more.",
          speak: "хотел",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "note",
          title: "Ф = f",
          body:
            "**Ф** is a circle with a vertical line through it (like Greek phi). Simple - it's the F sound.\n\nФ = f.",
        },
        {
          type: "choice",
          prompt: "Read: **ФУДБАЛ**",
          options: ["fudbal", "futvol", "pudbal"],
          correct: 0,
          after: "Фудбал - football. Ф=f, У=u, Д=d, Б=b (not В!), Л=l. Macedonian spells it with д, the way it's said.",
          speak: "фудбал",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "exercise",
          prompt: "Type **фудбал** (football).",
          answer: "фудбал",
          hint: "f-u-d-b-a-l.",
          after: "Four of this lesson's new letters in one word: Ф, Д, Б, Л. Typed by sound.",
          reviews: ["cyrillic-typing", "cyrillic-reading"],
        },
        {
          type: "note",
          title: "Ј = y",
          body:
            "**Ј** is the Latin J, borrowed into the Macedonian alphabet - but it sounds like the 'y' in 'yes', never like the 'j' in 'jam'.\n\nIt also does the job of two letters: **ја** = ya, **ју** = yu, **је** = ye. So 'Yulia' is Јулија and 'yogurt' is јогурт.\n\nЈ = y (as in yes). Type **j** (or **y**) to get it.",
          speak: ["јогурт", "Јулија"],
          introduces: ["ј-letter"],
          he: "Ј is the consonant י, as in יש or יום - never a vowel.",
          ru: "Ј replaces Russian's short i, and also the iotated vowel letters: Russian Ya-po-ni-ya is Јапонија here, written with ј + а. There are no yu/ya letters at all.",
          bg: "Bulgarian's й is ј here, and я/ю are written out as ја/ју: йогурт → јогурт, Юлия → Јулија, България → Бугарија (with no л, too).",
        },
        {
          type: "choice",
          prompt: "Read: **ЈОГУРТ**",
          options: ["yogurt", "iogurt", "jogurt"],
          correct: 0,
          after: "Јогурт - yogurt. Ј at the start makes the Y sound, and the Р near the end is R.",
          speak: "јогурт",
          reviews: ["ј-letter", "cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "Read: **ЈАС**",
          options: ["yas", "jas", "ias"],
          correct: 0,
          after: "Јас - 'I'. Ј + А together say 'ya'. You'll use this word in almost every lesson from module 2 on.",
          speak: "јас",
          reviews: ["ј-letter"],
        },
        {
          type: "choice",
          prompt: "Read the name of a country: **БУГАРИЈА**",
          options: ["bugariya", "bulgariya", "bugarija"],
          correct: 0,
          after: "Бугарија - Bulgaria. No Л in the Macedonian name, and the ending -ија is how Cyrillic writes '-ia'. Србија, Германија, Англија work the same way.",
          speak: "Бугарија",
          reviews: ["ј-letter", "cyrillic-reading"],
        },
        {
          type: "exercise",
          prompt: "Type **јас** (I).",
          answer: "јас",
          hint: "j-a-s. Type 'j' for Ј.",
          after: "Ј is 'j' on the keyboard, even though it sounds like 'y'. (Typing 'y' works too.)",
          reviews: ["cyrillic-typing", "ј-letter"],
        },
        {
          type: "exercise",
          prompt: "Type **Германија** (Germany).",
          answer: "Германија",
          hint: "G-e-r-m-a-n-i-j-a. Capital G, and 'j' for the Ј before the last а.",
          after: "Германија - you typed a country name in its own alphabet, with the -ија ending you'll see on Србија, Англија, Македонија.",
          reviews: ["cyrillic-typing", "ј-letter", "cyrillic-reading"],
        },
        {
          type: "note",
          body:
            "Seven new letters down. You now know 20 of 31 - two thirds of the Macedonian alphabet. Every one of these makes a sound you already knew; only the shapes were new.\n\nNext lesson: letters for sounds that English spells with two letters (sh, zh, ch, ts) - and the two soft letters.",
        },
      ],
    },
    {
      id: "m0l4",
      title: "New sounds",
      subtitle: "One letter for sh, zh, ch, ts - and the soft pair",
      items: [
        {
          type: "note",
          title: "One letter, two-letter sounds",
          body:
            "English needs two letters to write 'sh', 'ch', 'zh', 'ts'. Macedonian gives each of these a single letter. More efficient.\n\nTo type these, you'll use the same two-letter combos: type **sh** to get Ш, **zh** for Ж, **ch** for Ч. The keyboard converts them as you type.\n\nWe'll take them one at a time, then meet the soft pair Љ and Њ.",
        },
        {
          type: "note",
          title: "Ш = sh",
          body:
            "**Ш** looks like a comb with three teeth pointing up. It's the 'sh' in 'ship' - one letter instead of two.\n\nШ = sh.",
          he: "Ш is ש (shin), sound and shape both: three teeth pointing up.",
        },
        {
          type: "choice",
          prompt: "Read: **ШОК**",
          options: ["shok", "chok", "sok"],
          correct: 0,
          after: "Шок - shock. Ш is 'sh'. One letter for the whole sound.",
          speak: "шок",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "exercise",
          prompt: "Type **машина** (machine).",
          answer: "машина",
          hint: "m-a-sh-i-n-a. Type 'sh' for Ш.",
          after: "Type 'sh' and the keyboard gives you Ш. One keystroke combo, one letter.",
          reviews: ["cyrillic-typing"],
        },
        {
          type: "note",
          title: "Ж = zh",
          body:
            "**Ж** looks like a bug or snowflake. It's the sound in the middle of 'plea**s**ure' or 'vi**s**ion' - the voiced version of 'sh'. French writes it as 'j'.\n\nЖ = zh.",
          he: "Ж is like ז׳ in ז׳קט.",
        },
        {
          type: "choice",
          prompt: "Read: **ЖЕНА**",
          options: ["zhena", "shena", "zena"],
          correct: 0,
          after: "Жена - woman, and also wife. Ж is 'zh' - that buzzing 'sh' sound. Your first everyday word with it.",
          speak: "жена",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "Read: **ЖУРНАЛИСТ**",
          options: ["shurnalist", "zhurnalist", "zurnalist"],
          correct: 1,
          after: "Журналист - journalist. Ж is 'zh', just like the French 'j' in 'journal'.",
          speak: "журналист",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "note",
          title: "Ч = ch",
          body:
            "**Ч** looks like a reversed 4. It's the 'ch' in 'church' or 'chess'.\n\nЧ = ch.",
          he: "Ч is צ׳ as in צ׳יפס.",
        },
        {
          type: "choice",
          prompt: "Read: **ЧАЈ**",
          options: ["chay", "shay", "tsay"],
          correct: 0,
          after: "Чај - tea. Ч is 'ch', Ј is 'y'. Чај is 'chai' - the word half the world uses for tea.",
          speak: "чај",
          reviews: ["cyrillic-reading", "ј-letter"],
        },
        {
          type: "choice",
          prompt: "Read: **ЧОКОЛАДО**",
          options: ["chokolado", "shokolado", "chokolabo"],
          correct: 0,
          after: "Чоколадо - chocolate. Macedonian starts it with 'ch', and the Д in the middle is D.",
          speak: "чоколадо",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "exercise",
          prompt: "Type **чај** (tea).",
          answer: "чај",
          hint: "ch-a-j. Type 'ch' for Ч and 'j' for Ј.",
          after: "Ч='ch', Ј='j'. Two typing combos in one short word.",
          reviews: ["cyrillic-typing", "ј-letter"],
        },
        {
          type: "exercise",
          prompt: "Type **чоколадо** (chocolate).",
          answer: "чоколадо",
          hint: "ch-o-k-o-l-a-d-o.",
          after: "Eight letters, and the only combo was 'ch' at the start. The rest you've typed for three lessons.",
          reviews: ["cyrillic-typing", "cyrillic-reading"],
        },
        {
          type: "note",
          title: "З = z",
          body:
            "**З** looks like the number 3. Easy mnemonic: 3 → З → z.\n\nЗ = z.",
        },
        {
          type: "choice",
          prompt: "Read: **ЗОНА**",
          options: ["zona", "sona", "tsona"],
          correct: 0,
          after: "Зона - zone. З (looks like 3) is Z.",
          speak: "зона",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "Read: **МУЗЕЈ**",
          options: ["muzey", "musey", "muzeu"],
          correct: 0,
          after: "Музеј - museum. З is Z, and the Ј at the end is the 'y' sound: mu-ZEY.",
          speak: "музеј",
          reviews: ["cyrillic-reading", "ј-letter"],
        },
        {
          type: "exercise",
          prompt: "Type **Израел** (Israel).",
          answer: "Израел",
          hint: "I-z-r-a-e-l. Capital I, then 'z' for З.",
          after: "Израел - Israel in Macedonian. З is 'z', Р is 'r', Л is 'l'.",
          he: "ישראל, spelled the Macedonian way: Из-ра-ел.",
          reviews: ["cyrillic-typing", "cyrillic-reading"],
        },
        {
          type: "note",
          title: "Ц = ts",
          body:
            "**Ц** looks like a shorter Ш with a little tail hanging off the right side. It's the 'ts' sound - like the end of 'ca**ts**'.\n\nЦ = ts. Type **c** to get it.",
          he: "Ц is exactly צ (tsadi).",
        },
        {
          type: "choice",
          prompt: "Read: **ЦИРК**",
          options: ["tsirk", "sirk", "chirk"],
          correct: 0,
          after: "Цирк - circus. Ц is 'ts', and the Р is R (not P!).",
          speak: "цирк",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "Read: **СТАНИЦА**",
          options: ["stanitsa", "stanisa", "stanicha"],
          correct: 0,
          after: "Станица - station (bus, train, metro). Ц is 'ts'.",
          speak: "станица",
          reviews: ["cyrillic-reading"],
        },
        {
          type: "exercise",
          prompt: "Type **концерт** (concert).",
          answer: "концерт",
          hint: "k-o-n-c-e-r-t. Type 'c' for Ц.",
          after: "Ц is just 'c' on the keyboard. One letter for the 'ts' sound.",
          reviews: ["cyrillic-typing"],
        },
        {
          type: "choice",
          prompt: "You can now read the capital. Read: **СКОПЈЕ**",
          options: ["skopye", "skopje", "skorye"],
          correct: 0,
          after: "Скопје - Skopje. П is P, and ЈЕ says 'ye': SKOP-ye.",
          speak: "Скопје",
          reviews: ["cyrillic-reading", "ј-letter"],
        },
        {
          type: "exercise",
          prompt: "Type the name of the country: **Македонија** (Macedonia).",
          answer: "Македонија",
          hint: "M-a-k-e-d-o-n-i-j-a. Capital M, 'j' for Ј.",
          after: "Македонија - you just typed the name of the country in its own alphabet. Reading AND writing - both working.",
          reviews: ["cyrillic-typing", "ј-letter", "cyrillic-reading"],
        },
        {
          type: "note",
          title: "The soft pair: Љ and Њ",
          body:
            "Look at **Љ** and **Њ**: each is Л or Н with a small soft sign glued to its right. That's exactly what they are - a soft L and a soft N.\n\n**Љ** is the 'll' in Spanish or the 'gl' in Italian 'famiglia': say 'l' and 'y' at the same time. **Њ** is the Spanish 'ñ' or the 'ni' in 'onion'.\n\nType **lj** for Љ and **nj** for Њ.",
          speak: ["љубов", "бања"],
          introduces: ["љ-њ-letters"],
          ru: "Љ and Њ are Russian's l + soft sign and n + soft sign written as one letter each: lyubov → љубов, banya → бања.",
          bg: "Where Bulgarian softens with ь, ю or я after л/н (Любляна, баня, кон), Macedonian gives the soft consonant its own letter: Љубљана, бања, коњ.",
        },
        {
          type: "choice",
          prompt: "Read: **ЉУБОВ**",
          options: ["lyubov", "lubov", "lyudov"],
          correct: 0,
          after: "Љубов - love. Љ + У says 'lyu', and the В at the end is V.",
          speak: "љубов",
          reviews: ["љ-њ-letters", "cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "Read: **БАЊА**",
          options: ["banya", "bana", "bahya"],
          correct: 0,
          after: "Бања - bathroom, and also a spa. Њ + А says 'nya', like the ña in 'España'.",
          speak: "бања",
          reviews: ["љ-њ-letters"],
        },
        {
          type: "choice",
          prompt: "Read: **КОЊ**",
          options: ["kony", "kon", "kohy"],
          correct: 0,
          after: "Коњ - horse. The soft Њ sits at the very end: 'kony', with the 'y' barely there.",
          speak: "коњ",
          reviews: ["љ-њ-letters", "cyrillic-reading"],
        },
        {
          type: "exercise",
          prompt: "Type **Љубљана** (Ljubljana).",
          answer: "Љубљана",
          hint: "Lj-u-b-lj-a-n-a. Type 'lj' for Љ - twice.",
          after: "Two Љ letters, each typed as 'lj'. The keyboard waits after you type 'l' to see whether a 'j' follows.",
          reviews: ["cyrillic-typing", "љ-њ-letters"],
        },
        {
          type: "exercise",
          prompt: "Type **бања** (bathroom).",
          answer: "бања",
          hint: "b-a-nj-a. Type 'nj' for Њ.",
          after: "Њ is 'nj' on the keyboard. Same idea as Љ: the plain letter plus 'j' makes it soft.",
          reviews: ["cyrillic-typing", "љ-њ-letters"],
        },
        {
          type: "note",
          body:
            "Twenty-seven letters. You can read Скопје, Македонија, чај, жена, љубов - and type them.\n\nFour letters remain, and they are the reason this module has a fifth lesson: no other alphabet has them.",
          speak: ["Скопје", "Македонија", "чај", "жена", "љубов"],
        },
      ],
    },
    {
      id: "m0l5",
      title: "The Macedonian four",
      subtitle: "Ќ, Ѓ, Ѕ, Џ - and the whole alphabet",
      items: [
        {
          type: "note",
          title: "Four letters nobody else has",
          body:
            "You know 27 letters, and 24 of them exist in other Cyrillic alphabets too. The last four - **Ќ Ѓ Ѕ Џ** - are what makes a page look Macedonian at a glance.\n\nTwo are soft sounds (Ќ, Ѓ), two are sounds English writes with two letters (Ѕ, Џ). Same approach as before: one at a time, read first, then type.",
        },
        {
          type: "note",
          title: "Ќ = soft k",
          body:
            "**Ќ** is К with an accent. It's a soft 'k' - the 'ky' at the start of 'cute', said quickly, so it lands somewhere between 'k' and 'ch'.\n\nThe most common word with it is tiny: **ќе**, which means 'will'. You'll meet it constantly.\n\nЌ = ky. Type **kj** to get it.",
          speak: ["ќе", "куќа"],
          introduces: ["ќ-ѓ-letters"],
          ru: "Ќ has no Russian letter; think of к with a soft sign, halfway to ч.",
          bg: "Where Bulgarian has щ in a shared word, Macedonian usually has ќ: нощ → ноќ, къща → куќа, свещ → свеќа. And Bulgarian ъ does not exist here at all: къща → куќа, път → пат.",
        },
        {
          type: "choice",
          prompt: "Read: **КУЌА**",
          options: ["kukya", "kucha", "kuka"],
          correct: 0,
          after: "Куќа - house. The first К is a plain 'k'; the Ќ with the accent is the soft 'ky'.",
          speak: "куќа",
          reviews: ["ќ-ѓ-letters", "cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "Read: **НОЌ**",
          options: ["noky", "nok", "noch"],
          correct: 0,
          after: "Ноќ - night. A soft 'k' at the very end, the way коњ had a soft 'n'.",
          speak: "ноќ",
          reviews: ["ќ-ѓ-letters"],
        },
        {
          type: "choice",
          prompt: "Read: **СРЕЌА**",
          options: ["srekya", "srecha", "sreka"],
          correct: 0,
          after: "Среќа - luck, happiness. Р is R, and Ќ is the soft 'ky'. Со среќа! is 'good luck!'",
          speak: "среќа",
          reviews: ["ќ-ѓ-letters", "cyrillic-reading"],
        },
        {
          type: "exercise",
          prompt: "Type **куќа** (house).",
          answer: "куќа",
          hint: "k-u-kj-a. Plain 'k' first, then 'kj' for Ќ.",
          after: "Two k's, one plain and one soft. The 'j' after 'k' is what makes the keyboard produce Ќ.",
          reviews: ["cyrillic-typing", "ќ-ѓ-letters"],
        },
        {
          type: "exercise",
          prompt: "Type **ноќ** (night).",
          answer: "ноќ",
          hint: "n-o-kj.",
          after: "Ноќ - typed as n-o-kj. Добра ноќ, good night, is coming up in module 6.",
          reviews: ["cyrillic-typing", "ќ-ѓ-letters"],
        },
        {
          type: "note",
          title: "Ѓ = soft g",
          body:
            "**Ѓ** is Ќ's voiced twin: Г with an accent. It's a soft 'g' - the 'gy' in 'argue', said quickly, between 'g' and 'j'.\n\nThe name **Ѓорѓи** (George) has two of them.\n\nЃ = gy. Type **gj** to get it.",
          speak: ["Ѓорѓи", "меѓу"],
          ru: "Ѓ is the voiced partner of Ќ - г with a soft sign, halfway to дж.",
          bg: "Bulgarian жд in a shared word is ѓ here: между → меѓу. And Bulgarian Георги is Ѓорѓи, with both g's soft.",
        },
        {
          type: "choice",
          prompt: "Read: **ЃОРЃИ**",
          options: ["gyorgyi", "georgi", "dyordyi"],
          correct: 0,
          after: "Ѓорѓи - George. Both Ѓ letters are the soft 'gy'; the Р between them is R.",
          speak: "Ѓорѓи",
          reviews: ["ќ-ѓ-letters", "cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "Read: **МЕЃУ**",
          options: ["megyu", "mezhu", "megu"],
          correct: 0,
          after: "Меѓу - between. Ѓ + У says 'gyu'.",
          speak: "меѓу",
          reviews: ["ќ-ѓ-letters"],
        },
        {
          type: "exercise",
          prompt: "Type **меѓу** (between).",
          answer: "меѓу",
          hint: "m-e-gj-u. Type 'gj' for Ѓ.",
          after: "Ѓ is 'gj', the same trick as 'kj' for Ќ: the base letter plus 'j' makes it soft.",
          reviews: ["cyrillic-typing", "ќ-ѓ-letters"],
        },
        {
          type: "exercise",
          prompt: "Type **Ѓорѓи** (George).",
          answer: "Ѓорѓи",
          hint: "Gj-o-r-gj-i. Capital G then j for the first Ѓ, plain 'r' for Р.",
          after: "Two soft g's and an imposter Р, all typed by sound. You are past the hard part.",
          reviews: ["cyrillic-typing", "ќ-ѓ-letters", "cyrillic-reading"],
        },
        {
          type: "note",
          title: "Ѕ = dz",
          body:
            "**Ѕ** looks exactly like a Latin S - but it is not С, and it does not say 's'. It says 'dz', the sound at the end of 'a**dds**' or 'ki**ds**'.\n\nIt lives in only a handful of words, and you'll see it mostly at the start: **ѕвезда** (star), **ѕвоно** (bell), **ѕид** (wall).\n\nЅ = dz. Type **dz** to get it.",
          speak: ["ѕвезда", "ѕвоно"],
          introduces: ["ѕ-џ-letters"],
          ru: "Russian звезда and звонок start with a plain з; Macedonian starts them with the single letter ѕ, said 'dz'.",
        },
        {
          type: "choice",
          prompt: "Read: **ЅВЕЗДА**",
          options: ["dzvezda", "svezda", "zvezda"],
          correct: 0,
          after: "Ѕвезда - star. The S-shaped letter at the front is 'dz'; the З in the middle is a plain 'z'.",
          speak: "ѕвезда",
          reviews: ["ѕ-џ-letters", "cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "Read: **ЅВОНО**",
          options: ["dzvono", "svono", "zvono"],
          correct: 0,
          after: "Ѕвоно - bell. Same 'dz' at the front, and В is V.",
          speak: "ѕвоно",
          reviews: ["ѕ-џ-letters"],
        },
        {
          type: "exercise",
          prompt: "Type **ѕвезда** (star).",
          answer: "ѕвезда",
          hint: "dz-v-e-z-d-a. Type 'dz' for Ѕ, then 'v'. The З in the middle is a plain 'z'.",
          after: "Ѕ is 'dz' on the keyboard. Notice you typed two different letters for the two z-like sounds: 'dz' for Ѕ, 'z' for З.",
          reviews: ["cyrillic-typing", "ѕ-џ-letters"],
        },
        {
          type: "note",
          title: "Џ = j",
          body:
            "**Џ** is Ц with its tail moved to the middle. It says 'j' as in 'jazz' or 'jam' - the sound Ј does NOT make.\n\nIt shows up in borrowed words: **џез** (jazz), **џем** (jam), **џип** (jeep), **буџет** (budget), **џамија** (mosque).\n\nЏ = j (as in jazz). Type **dzh** to get it - 'd' plus the 'zh' you already know.",
          speak: ["џез", "џем", "џамија"],
          he: "Џ is ג׳ as in ג׳ינס. Ј, on the other hand, is י.",
          ru: "Russian writes this sound with two letters, дж (джаз, джем); Macedonian has one, џ.",
        },
        {
          type: "choice",
          prompt: "Read: **ЏЕЗ**",
          options: ["jez", "zhez", "dzez"],
          correct: 0,
          after: "Џез - jazz. Џ is the 'j' of 'jazz'; З at the end is 'z'.",
          speak: "џез",
          reviews: ["ѕ-џ-letters", "cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "Read: **ЏАМИЈА**",
          options: ["jamiya", "zhamiya", "dzamiya"],
          correct: 0,
          after: "Џамија - mosque. Џ at the start is the 'j' in 'jazz'; Ј near the end is the 'y' in 'yes'. Two letters, two different sounds.",
          speak: "џамија",
          reviews: ["ѕ-џ-letters", "ј-letter"],
        },
        {
          type: "choice",
          prompt: "Read: **БУЏЕТ**",
          options: ["bujet", "buzhet", "budzet"],
          correct: 0,
          after: "Буџет - budget. Б is the real B, Џ is 'j'.",
          speak: "буџет",
          reviews: ["ѕ-џ-letters", "cyrillic-reading"],
        },
        {
          type: "exercise",
          prompt: "Type **џем** (jam).",
          answer: "џем",
          hint: "dzh-e-m. Type 'dzh' for Џ.",
          after: "Three keystrokes, one letter: 'dzh' becomes Џ.",
          reviews: ["cyrillic-typing", "ѕ-џ-letters"],
        },
        {
          type: "exercise",
          prompt: "Type **пиџама** (pyjamas).",
          answer: "пиџама",
          hint: "p-i-dzh-a-m-a.",
          after: "Пиџама - a word with Џ in the middle, typed as smoothly as the rest.",
          reviews: ["cyrillic-typing", "ѕ-џ-letters", "cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "Now the other way round. Which of these is **night**?",
          options: ["ноч", "ноќ", "нок"],
          correct: 1,
          after: "Ноќ, with the soft Ќ. Ноч would be 'noch', and нок a hard 'nok'.",
          speak: "ноќ",
          reviews: ["ќ-ѓ-letters", "cyrillic-reading"],
        },
        {
          type: "choice",
          prompt: "And which is **star**?",
          options: ["свезда", "звезда", "ѕвезда"],
          correct: 2,
          after: "Ѕвезда - the letter that looks like S but says 'dz'. Now you can tell С and Ѕ apart at a glance.",
          speak: "ѕвезда",
          reviews: ["ѕ-џ-letters", "cyrillic-reading"],
        },
        {
          type: "note",
          title: "The whole alphabet",
          body:
            "That's all 31. You have read and typed every one of them, so here is the full list, in alphabetical order - a map, not homework:\n\n**А Б В Г Д Ѓ Е Ж З Ѕ И Ј К Л Љ М Н Њ О П Р С Т Ќ У Ф Х Ц Ч Џ Ш**\n\nTyping cheat sheet for the ones that aren't just the Latin letter: ж = zh, ц = c, ч = ch, ш = sh, ј = j, љ = lj, њ = nj, ќ = kj, ѓ = gj, ѕ = dz, џ = dzh.\n\nEvery lesson from here on reinforces these letters through real words and sentences. The imposters (В, Н, Р) take about a week to feel automatic. Reading gets faster the more you do it.\n\nNext: words you already know.",
          ru: "None of the Russian-only letters exist here - no hard or soft sign, no yery, no shcha, no yo/yu/ya - and there are seven letters Russian lacks: ѓ ѕ ј љ њ ќ џ.",
          bg: "Six Bulgarian letters are gone (ъ щ ь ю я й) and seven are new (ѓ ѕ ј љ њ ќ џ). The conversions: й → ј, я/ю → ја/ју, ъ → а or о, щ → ќ or шт, жд → ѓ.",
        },
      ],
    },
  ],
};
