import type { Module } from "./types";

export const module4: Module = {
  id: "m4",
  title: "5. People",
  blurb:
    "Introduce yourself, ask where someone lives, and pick up the tiny pronouns that make conversations personal - me, you, mine, yours - and the habit of saying them twice.",
  lessons: [
    {
      id: "m4l1",
      title: "What's your name?",
      subtitle: "Се викам, како, Мило ми е",
      items: [
        {
          type: "note",
          title: "Warm-up",
          body: "Before we learn to introduce ourselves, let's make sure everything from the last module is still running. No new words here - just three sentences from things you already own.",
        },
        {
          type: "exercise",
          prompt: "**The new car is good.**",
          answer: "Новата кола е добра",
          hint: "новата (the article rides the adjective) + кола + е + добра (feminine).",
          after: "Adjective agreement, article on the adjective, feminine forms. All working together.",
          reviews: ["adj-definite", "adj-agreement", "нов", "кола", "добар", "сум"],
        },
        {
          type: "exercise",
          prompt: "**He must work today.**",
          answer: "Тој треба да работи денес",
          accept: ["треба да работи денес"],
          hint: "треба (frozen) + да + работи (и-group, he-form) + денес.",
          reviews: ["треба-да", "verb-и-group", "pronoun-subject", "работам", "денес"],
        },
        {
          type: "exercise",
          prompt: "**Can I have the coffee, please?**",
          answer: "Може ли кафето, Ве молам?",
          accept: ["Може ли кафето, молам?"],
          hint: "Може ли + кафето (neuter article) + Ве молам.",
          after: "Three for three. You're ready for new ground.",
          reviews: ["може-ли-polite", "definite-neuter", "ве молам"],
        },
        {
          type: "note",
          title: "Calling yourself",
          body: "**Викам** = *I call* - a regular а-group verb, so you already know the endings: викам, викаш, вика...\n\n**Се** = *oneself*. And here is the thing to notice: **се** goes **in front of** the verb.\n\n**Се викам Марко.** = literally 'myself I-call Marko' = *My name is Marko.*\n\nThe little word leads, the verb follows. Even at the very start of a sentence - that's where it lives.",
          speak: ["Се викам Марко."],
          introduces: ["reflexive-се"],
          he: "**Се** does the job of Hebrew's reflexive hitpa'el - except it's a separate little word that sits in front of the verb rather than a pattern inside it.",
          ru: "Same idea as Russian -ся (называюсь), but detached and moved to the front: **се викам**. The verb itself is different - Russian звать, Macedonian викам.",
          bg: "Bulgarian says Казвам се Петър, with се after the verb; Macedonian says Се викам Петар, with се in front - even at the very start of a sentence, a position Bulgarian never allows.",
        },
        {
          type: "exercise",
          prompt: "How would you say: **My name is Marija.**",
          answer: "Се викам Марија",
          accept: ["јас се викам Марија"],
          hint: "се first, then викам, then the name.",
          after: "**Се викам Марија.** You put се in front without hesitating. Keep that instinct - it runs the whole module.",
          reviews: ["викам", "reflexive-се", "verb-а-group"],
        },
        {
          type: "exercise",
          prompt: "Say: **You call yourself Marko.** (conjugate викам to the ти-form)",
          answer: "Се викаш Марко",
          accept: ["ти се викаш Марко"],
          hint: "викам → викаш (you-form, а-group). се stays in front.",
          after: "Just a conjugation change. **Се викам** → **се викаш**. The се didn't move an inch.",
          reviews: ["викам", "verb-а-group", "reflexive-се"],
        },
        {
          type: "note",
          title: "How",
          body: "One new word: **како** = *how*.\n\nPut it in front and you get the question: **Како се викаш?** - literally 'how yourself you-call?' = *What's your name?*\n\nNotice that се didn't go anywhere. Како opens the sentence, and се stays glued to the front of its verb.",
          speak: ["Како се викаш?"],
          introduces: ["како-how"],
          ru: "Russian как → Macedonian **како**. Same word with an extra syllable.",
          bg: "Bulgarian как → Macedonian како.",
        },
        {
          type: "exercise",
          prompt: "Ask: **What's your name?** (literally: 'How do you call yourself?')",
          answer: "Како се викаш?",
          hint: "како + се + викаш.",
          after: "**Како се викаш?** - your first question that can start a real conversation.",
          reviews: ["како-how", "викам", "reflexive-се"],
        },
        {
          type: "exercise",
          prompt: "**His name is Petar.**",
          answer: "Се вика Петар",
          accept: ["тој се вика Петар"],
          hint: "викам → вика (he-form). се still in front.",
          after: "The he-form is the bare stem, вика - and се stays in front of it just like before.",
          reviews: ["викам", "verb-а-group", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "Ask: **What is her name?**",
          answer: "Како се вика?",
          accept: ["Како се вика таа?"],
          hint: "како + се + вика (he/she form).",
          reviews: ["како-how", "викам", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**Her name is Elena. She is a doctor.**",
          answer: "Се вика Елена. Таа е докторка.",
          accept: ["Таа се вика Елена. Таа е докторка.", "Се вика Елена. Докторка е."],
          hint: "се вика + name. Then таа е + докторка (feminine -ка).",
          reviews: ["pronoun-subject", "сум", "feminine-ка"],
        },
        {
          type: "note",
          title: "Nice to meet you",
          body: "**Мило ми е.** = *Nice to meet you.* Literally something like 'dear to-me it-is'.\n\nYou'll also hear **Драго ми е** - same meaning, same shape. Learn either as a chunk for now. That little **ми** inside will make full sense at the end of this module.",
          speak: ["Мило ми е.", "Драго ми е."],
          he: "Same logic as נעים מאוד - a fixed phrase you say back, not a sentence you build.",
          bg: "Bulgarian says Приятно ми е; here it's Мило ми е or Драго ми е - same ми, different first word.",
        },
        {
          type: "exercise",
          prompt: "Someone says: Се викам Петар. Respond with: **Nice to meet you.**",
          answer: "Мило ми е",
          accept: ["Драго ми е"],
          hint: "The set phrase: Мило ми е.",
          after: "You just had your first exchange in Macedonian. Say it out loud a few times - it sticks faster that way.",
          reviews: ["мило"],
        },
        {
          type: "exercise",
          prompt: "Respond: **Nice to meet you, Marija.**",
          answer: "Мило ми е, Марија",
          accept: ["Драго ми е, Марија"],
          hint: "The set phrase + a name.",
          reviews: ["мило"],
        },
        {
          type: "exercise",
          prompt: "Introduce yourself: **My name is Ana. Nice to meet you.**",
          answer: "Се викам Ана. Мило ми е.",
          accept: ["Се викам Ана. Драго ми е."],
          hint: "Се викам + name. Then Мило ми е.",
          reviews: ["викам", "reflexive-се", "мило"],
        },
        {
          type: "note",
          title: "This is...",
          body: "To introduce someone else, you need *this*: **ова**.\n\n- **Ова е Марко.** - This is Marko.\n- **Ова е Марија.** - This is Marija.\n\nOne form, no matter who you're pointing at. (For *that*, further away, it's **тоа** - but ова does most of the work.)",
          speak: ["Ова е Марко.", "Ова е Марија."],
          introduces: ["ова-this"],
          he: "Hebrew picks זה or זאת by gender; ова doesn't care - one word for introducing anyone.",
          bg: "Bulgarian това covers both 'this' and 'that'; Macedonian splits them: ова (this, near) and тоа (that).",
        },
        {
          type: "exercise",
          prompt: "**This is Marko.**",
          answer: "Ова е Марко",
          hint: "ова + е + the name.",
          reviews: ["ова-this", "сум", "сум-present"],
        },
        {
          type: "exercise",
          prompt: "**This is Marija. She is a student.**",
          answer: "Ова е Марија. Таа е студентка.",
          accept: ["Ова е Марија. Студентка е."],
          hint: "Ова е + name. Then таа е + студентка.",
          reviews: ["ова-this", "pronoun-subject", "сум", "feminine-ка"],
        },
        {
          type: "exercise",
          prompt: "**This is Petar. He is from Ohrid.**",
          answer: "Ова е Петар. Тој е од Охрид.",
          accept: ["Ова е Петар. Од Охрид е."],
          hint: "Ова е + name. Then тој е од + place.",
          after: "You introduced someone and said where he's from - two sentences that any host in Macedonia would say.",
          reviews: ["ова-this", "од-from", "сум", "pronoun-subject"],
        },
        {
          type: "note",
          title: "The question you'll use every day",
          body: "Point at anything and ask:\n\n**Како се вика ова на македонски?**\n*What is this called in Macedonian?*\n\n- **се вика** = is called\n- **ова** = this\n- **на македонски** = in Macedonian\n\nPeople love being asked this. Use it shamelessly - it turns every interaction into a free lesson.",
          speak: ["Како се вика ова на македонски?"],
          reviews: ["како-how", "ова-this", "викам"],
        },
        {
          type: "exercise",
          prompt: "Ask: **What is this called in Macedonian?**",
          answer: "Како се вика ова на македонски?",
          hint: "Како се вика + ова + на македонски?",
          after: "Memorize this one sentence and you have a skeleton key to learning outside this course.",
          reviews: ["македонски", "како-how", "ова-this"],
        },
        {
          type: "exercise",
          prompt: "Greet someone and introduce yourself: **Hello! My name is Marko.**",
          answer: "Здраво! Се викам Марко.",
          accept: ["здраво, се викам Марко"],
          hint: "здраво = hello. Се викам + name.",
          reviews: ["здраво", "викам", "reflexive-се", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "Someone asks: Како се викаш? Answer: **My name is Ana. I am from Canada.**",
          answer: "Се викам Ана. Јас сум од Канада.",
          accept: ["Се викам Ана. Од Канада сум."],
          hint: "Се викам + name. Јас сум од + country (or Од Канада сум).",
          reviews: ["pronoun-subject", "сум", "сум-position", "од-from"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Is your name Marko?**",
          answer: "Дали се викаш Марко?",
          accept: ["Се викаш ли Марко?", "Марко ли се викаш?"],
          hint: "дали in front, then the sentence unchanged: се викаш Марко.",
          after: "With дали nothing moves - се stays in front of викаш. That's the beauty of дали.",
          reviews: ["дали-question", "ли-question", "викам", "reflexive-се"],
        },
      ],
    },
    {
      id: "m4l2",
      title: "Where I live",
      subtitle: "живеам во Скопје, каде, Како си?",
      items: [
        {
          type: "note",
          title: "One more е-group verb",
          body: "**Живеам** = *I live*. It belongs to the е-group, like можам:\n\n- **живеам** - I live\n- **живееш** - you live\n- **живее** - he/she lives\n\nThe I-form ends in -м, as every verb does. The you-form ends in -ш with an е in front of it - that's what makes it е-group. For 'we', add -ме to живее: живееме. The rest of the family follows the same pattern, and you'll meet it as you need it.",
          speak: ["живеам", "живееш", "живее"],
          ru: "Same root as Russian жить / живу / живёшь. The Macedonian I-form just ends in -м like all the others.",
          bg: "Bulgarian живея / живееш / живеят; Macedonian живеам / живееш / живеат - the I-form in -м, as always.",
          reviews: ["verb-е-group", "verb-м-first-person"],
        },
        {
          type: "note",
          title: "In",
          body: "**Во** = *in*. One small word, one job:\n\n- **Живеам во Скопје.** - I live in Skopje.\n- **Живеам во Канада.** - I live in Canada.\n\nIt never changes shape, whatever comes after it.",
          speak: ["Живеам во Скопје.", "Живеам во Канада."],
          introduces: ["во-in"],
          he: "Hebrew glues ב onto the word (בסקופיה); Macedonian keeps во as a separate word in front.",
          ru: "Russian в → Macedonian во, always with the о. Russian во is the exception; here it's the only form.",
          bg: "Bulgarian в (and във before в/ф); Macedonian is always во - no doubled variant to think about.",
        },
        {
          type: "exercise",
          prompt: "**I live in Skopje.**",
          answer: "Живеам во Скопје",
          accept: ["јас живеам во Скопје"],
          hint: "живеам + во + Скопје.",
          reviews: ["живеам", "во-in", "pronoun-drop", "verb-е-group"],
        },
        {
          type: "exercise",
          prompt: "**She lives in Canada.**",
          answer: "Таа живее во Канада",
          accept: ["живее во Канада"],
          hint: "таа + живее (she-form) + во + Канада.",
          after: "живее - the е-group he/she form, same shape as може.",
          reviews: ["живеам", "pronoun-subject", "verb-е-group", "во-in"],
        },
        {
          type: "exercise",
          prompt: "**We live in a big city.**",
          answer: "Живееме во голем град",
          accept: ["ние живееме во голем град"],
          hint: "живееме (we-form) + во + голем (big, masculine) + град (city).",
          after: "голем stays in its bare form because град is masculine. The adjective agreement from last module keeps paying rent.",
          reviews: ["живеам", "verb-е-group", "голем", "adj-agreement", "град", "во-in"],
        },
        {
          type: "exercise",
          prompt: "**We are from Canada, but we live in Skopje.**",
          answer: "Ние сме од Канада, но живееме во Скопје",
          accept: ["сме од Канада, но живееме во Скопје", "Ние сме од Канада, ама живееме во Скопје"],
          hint: "сме (we are) + од + но (but) + живееме (we live) + во.",
          reviews: ["сум-present", "од-from", "но-but", "живеам", "verb-е-group"],
        },
        {
          type: "note",
          title: "How Macedonian actually sounds",
          body: "You've been hearing the voice for a while now, and one thing may have puzzled you: some words don't end the way they're spelled.\n\nVoiced consonants go quiet at the end of a word. Д sounds like Т, Б like П, Г like К. So **град** (city) sounds like 'grat', and **леб** (bread) like 'lep'. Add a suffix - **градот**, **лебот** - and the real consonant comes back, because it's no longer final.\n\nThe spelling shows the true consonant. Your ear just needs to expect the quiet version at the end. That's all - nothing to practice.",
          speak: ["град", "градот", "леб", "лебот"],
          introduces: ["final-devoicing"],
          he: "Hebrew doesn't do this. Russian does (друг sounds like друк) - if you know Russian, you already have the instinct.",
          ru: "Same rule as Russian: друг → друк, хлеб → хлеп. But no vowel reduction here - every Macedonian vowel is said exactly as written, молоко-style drift doesn't exist.",
          bg: "Bulgarian devoices too, but it also drifts its unstressed vowels (добра said like 'дубра'); Macedonian doesn't - every vowel is pronounced as written.",
          reviews: ["град", "леб"],
        },
        {
          type: "note",
          title: "Where?",
          body: "**Каде** = *where*. It leads the sentence:\n\n- **Каде живееш?** - Where do you live?\n- **Каде е хотелот?** - Where is the hotel?\n\nYou've had **тука** (here), **таму** (there), and **од** (from). Now you can ask the question that completes the set.",
          speak: ["Каде живееш?", "Каде е хотелот?"],
          introduces: ["каде-where"],
          ru: "Russian где → Macedonian каде. Different shape, same job.",
          bg: "Bulgarian къде → Macedonian каде (ъ → а).",
        },
        {
          type: "exercise",
          prompt: "Ask: **Where do you live?**",
          answer: "Каде живееш?",
          accept: ["Каде живееш ти?"],
          hint: "каде + живееш.",
          after: "**Каде живееш?** followed by **Живеам во...** - you now own the most universal small-talk exchange.",
          reviews: ["каде-where", "живеам", "verb-е-group", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Where is the restaurant?**",
          answer: "Каде е ресторанот?",
          hint: "каде + е + ресторанот (masculine article -от).",
          reviews: ["каде-where", "definite-masc", "сум-present"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Where does he live?**",
          answer: "Каде живее?",
          accept: ["Каде живее тој?", "Каде тој живее?"],
          hint: "каде + живее (he/she form of живеам).",
          reviews: ["каде-where", "живеам", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**Where is the bank?**",
          answer: "Каде е банката?",
          hint: "банка + -та = банката.",
          reviews: ["каде-where", "банка", "definite-fem", "сум-present"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Where are the students?**",
          answer: "Каде се студентите?",
          hint: "каде + се (they are) + студентите (plural with -те).",
          after: "се here is 'they are' - the same little се you met in Се викам wears two hats. Context tells you which.",
          reviews: ["каде-where", "сум-present", "plural-и"],
        },
        {
          type: "note",
          title: "How are you?",
          body: "Remember **како** from last lesson? Combine it with **си**:\n\n**Како си?** = *How are you?*\n\nAnswers you can already build: **Добро сум.** (I'm well.) **Добро, благодарам.** (Well, thanks.)\n\nAnd one more verb that carries **се** in front: **се чувствувам** = *I feel* (а-group, exactly like се викам).\n\n**Се чувствувам добро.** - I feel well.",
          speak: ["Како си?", "Добро сум.", "Се чувствувам добро."],
          he: "מה שלומך? works the same way - a fixed question with a fixed set of answers. Just remember Macedonian keeps сум: Добро сум, not just Добро.",
          ru: "Russian чувствую себя → се чувствувам: the себя has become се, and moved to the front.",
          bg: "Bulgarian Добре съм / Чувствам се добре; Macedonian Добро сум / Се чувствувам добро - добро means 'well', the verb has -ува-, and се goes first.",
          reviews: ["како-how", "чувствувам", "reflexive-се"],
        },
        {
          type: "exercise",
          prompt: "Ask: **How are you?**",
          answer: "Како си?",
          hint: "како + си.",
          reviews: ["како-how", "сум-present", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**I feel well.**",
          answer: "Се чувствувам добро",
          accept: ["Добро се чувствувам"],
          hint: "се + чувствувам + добро.",
          after: "Two verbs with се now - се викам and се чувствувам. Same се, same spot in front.",
          reviews: ["чувствувам", "reflexive-се", "verb-а-group", "добро"],
        },
        {
          type: "exercise",
          prompt: "Say: **I'm well, thanks.**",
          answer: "Добро сум, благодарам",
          accept: ["Добро, благодарам", "Добро сум, фала"],
          hint: "Добро + сум (I am) + благодарам (thanks).",
          reviews: ["добро", "сум-present", "сум-position", "благодарам"],
        },
        {
          type: "exercise",
          prompt: "**She doesn't feel well.**",
          answer: "Таа не се чувствува добро",
          accept: ["не се чувствува добро"],
          hint: "таа + не + се + чувствува (she-form) + добро.",
          after: "не goes in front of the whole се + verb pair. Remember that shape - you'll see it again very soon.",
          reviews: ["чувствувам", "не-negation", "reflexive-се", "pronoun-subject"],
        },
      ],
    },
    {
      id: "m4l3",
      title: "Me, you, him, her",
      subtitle: "Те гледам. Не те разбирам.",
      items: [
        {
          type: "note",
          title: "The other side of the verb",
          body: "So far you've been the one doing things - *I* want, *you* speak, *she* lives. Now: what about the person on the receiving end?\n\n**Гледам** = *I see / I watch* (а-group, predictable). To say *who* you see, you add a tiny pronoun - and it goes **in front of** the verb, exactly where се went. The first one:\n\n- **ме** - me\n\n**Ме гледаш.** - You see me.\n\nThe little word leads, even at the start of the sentence. You already do this with се; now the same slot gets more tenants.",
          speak: ["Ме гледаш."],
          introduces: ["clitic-proclitic", "object-pronoun-sg"],
          he: "Hebrew puts אותי after the verb (אתה רואה אותי); Macedonian puts its 'me' in front. Opposite order, same two pieces.",
          ru: "Russian says видишь меня, full pronoun after the verb; Macedonian uses a short form and puts it before: ме гледаш.",
          bg: "Bulgarian Виждаш ме puts the pronoun after the verb; Macedonian puts it before (Ме гледаш), even at the start of a sentence. And the verb for 'see' is гледам - which in Bulgarian means only 'watch'.",
        },
        {
          type: "exercise",
          prompt: "**You see me.**",
          answer: "Ме гледаш",
          accept: ["ти ме гледаш"],
          hint: "me = ме, in front. Then you see = гледаш (а-group, ти-form).",
          after: "Pronoun first, verb second. If you reached for the verb first, that's the English habit - it'll fade.",
          reviews: ["гледам", "verb-а-group", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you see me?**",
          answer: "Дали ме гледаш?",
          accept: ["Ме гледаш ли?"],
          hint: "дали in front, then ме гледаш unchanged.",
          after: "дали leaves the pair ме гледаш intact. With ли, the pair stays together too: Ме гледаш ли?",
          reviews: ["дали-question", "гледам", "object-pronoun-sg"],
        },
        {
          type: "note",
          title: "You",
          body: "The other side of ме:\n\n- **те** - you (as an object)\n\n**Те гледам.** - I see you.\n\nSame slot - right in front of the verb.",
          speak: ["Те гледам."],
        },
        {
          type: "exercise",
          prompt: "**I see you.**",
          answer: "Те гледам",
          accept: ["јас те гледам"],
          hint: "те first, then гледам.",
          reviews: ["гледам", "verb-а-group", "object-pronoun-sg"],
        },
        {
          type: "exercise",
          prompt: "**I love you.**",
          answer: "Те сакам",
          hint: "сакам does 'want' and 'love'. те in front.",
          after: "**Те сакам.** Two words. No decoration needed - and no second verb to learn, because сакам already covers love.",
          reviews: ["сакам", "verb-а-group", "object-pronoun-sg"],
          bg: "Bulgarian says Обичам те; Macedonian says Те сакам - сакам does both 'want' and 'love', and the pronoun leads.",
        },
        {
          type: "note",
          title: "Him",
          body: "Third person masculine:\n\n- **го** - him / it (masculine or neuter)\n\n**Го гледам.** - I see him.",
          speak: ["Го гледам."],
        },
        {
          type: "exercise",
          prompt: "**I see him.**",
          answer: "Го гледам",
          hint: "го + гледам.",
          reviews: ["гледам", "object-pronoun-sg", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you understand him?**",
          answer: "Дали го разбираш?",
          accept: ["Го разбираш ли?"],
          hint: "дали + го + разбираш.",
          after: "разбирам from module 2, го from this lesson. The slot in front of the verb works for any verb.",
          reviews: ["дали-question", "разбирам", "object-pronoun-sg"],
        },
        {
          type: "note",
          title: "Her",
          body: "Third person feminine:\n\n- **ја** - her / it (feminine)\n\n**Ја гледам.** - I see her.",
          speak: ["Ја гледам."],
          ru: "Watch out: **ја** means *her* - not 'I' like Russian я. 'I' is јас.",
          bg: "Bulgarian я → Macedonian ја, spelled with ј - and in front of the verb.",
        },
        {
          type: "exercise",
          prompt: "**I see her.**",
          answer: "Ја гледам",
          hint: "her = ја, in front of the verb.",
          reviews: ["гледам", "object-pronoun-sg", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**She sees him.**",
          answer: "Таа го гледа",
          accept: ["го гледа"],
          hint: "таа + го + гледа (she-form).",
          after: "Subject, then the little pronoun, then the verb. го still hugs the verb from the front - таа just stands before them.",
          reviews: ["pronoun-subject", "гледам", "verb-а-group", "object-pronoun-sg"],
        },
        {
          type: "note",
          title: "Saying no",
          body: "You already know **не** goes before the verb. Now there's a pronoun in front of the verb too. Where does не go?\n\nIn front of both. The pronoun stays glued to its verb:\n\n**Не те разбирам.** - I don't understand you.\n**Не го гледам.** - I don't see him.\n\nне, then the pronoun, then the verb. Always that order.",
          speak: ["Не те разбирам.", "Не го гледам."],
          introduces: ["clitic-placement"],
          he: "Hebrew: לא + verb + אותך. Macedonian: не + you + verb. The не lands in the same place; only the pronoun has crossed over.",
          bg: "In Bulgarian the pronoun jumps in front only when something like не leads (Разбирам те → Не те разбирам); in Macedonian it was already in front, so не simply goes before the pair. Same result, different logic.",
        },
        {
          type: "exercise",
          prompt: "**I don't understand you.**",
          answer: "Не те разбирам",
          hint: "не + те + разбирам.",
          after: "Say it kindly. People will slow down and love you for trying.",
          reviews: ["не-negation", "clitic-placement", "разбирам", "object-pronoun-sg"],
        },
        {
          type: "exercise",
          prompt: "**I don't see him.**",
          answer: "Не го гледам",
          hint: "не + го + гледам.",
          reviews: ["не-negation", "clitic-placement", "гледам", "object-pronoun-sg"],
        },
        {
          type: "exercise",
          prompt: "**She doesn't see me.**",
          answer: "Таа не ме гледа",
          accept: ["не ме гледа"],
          hint: "таа + не + ме + гледа.",
          after: "Subject, не, pronoun, verb. The pronoun never lets go of the verb.",
          reviews: ["clitic-placement", "object-pronoun-sg", "гледам", "pronoun-subject"],
        },
        {
          type: "note",
          title: "A second verb - and no 'for'",
          body: "**Чекам** = *I wait for* (а-group). Macedonian swallows the 'for' - you wait *someone* directly:\n\n**Те чекам.** - I'm waiting for you.",
          speak: ["Те чекам."],
          ru: "Not Russian ждать - чекам is the word Ukrainian has as чекати. Same family, different branch.",
          bg: "Bulgarian чакам → Macedonian чекам: the vowel changes, and the pronoun goes in front.",
        },
        {
          type: "exercise",
          prompt: "**I'm waiting for you.**",
          answer: "Те чекам",
          hint: "те + чекам. No word for 'for'.",
          reviews: ["чекам", "verb-а-group", "object-pronoun-sg"],
        },
        {
          type: "exercise",
          prompt: "**I'm waiting for her.**",
          answer: "Ја чекам",
          hint: "ја (her) + чекам.",
          reviews: ["чекам", "object-pronoun-sg", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**I'm not waiting for him.**",
          answer: "Не го чекам",
          hint: "не + го + чекам.",
          reviews: ["чекам", "не-negation", "clitic-placement", "object-pronoun-sg"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Are you waiting for me?**",
          answer: "Дали ме чекаш?",
          accept: ["Ме чекаш ли?"],
          hint: "дали + ме + чекаш.",
          reviews: ["дали-question", "чекам", "object-pronoun-sg"],
        },
        {
          type: "exercise",
          prompt: "**I'm watching a film.**",
          answer: "Гледам филм",
          accept: ["јас гледам филм"],
          hint: "гледам + филм. No little pronoun - there's no 'him' or 'it' here, just a film.",
          after: "With a plain noun like *a film*, no pronoun is needed. Hold that thought - it matters two lessons from now.",
          reviews: ["гледам", "verb-а-group", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**I'm waiting for a bus.**",
          answer: "Чекам автобус",
          accept: ["јас чекам автобус"],
          hint: "чекам + автобус (a cognate).",
          reviews: ["чекам", "verb-а-group", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**We're waiting for you.**",
          answer: "Те чекаме",
          accept: ["ние те чекаме"],
          hint: "те + чекаме (we-form).",
          after: "The pronoun doesn't care which form of the verb follows. It just wants to be in front.",
          reviews: ["чекам", "verb-а-group", "object-pronoun-sg"],
        },
        {
          type: "exercise",
          prompt: "**He doesn't understand me.**",
          answer: "Тој не ме разбира",
          accept: ["не ме разбира"],
          hint: "тој + не + ме + разбира.",
          reviews: ["clitic-placement", "разбирам", "object-pronoun-sg", "pronoun-subject"],
        },
        {
          type: "exercise",
          prompt: "**You must wait for me.**",
          answer: "Треба да ме чекаш",
          accept: ["ти треба да ме чекаш"],
          hint: "треба да + ме + чекаш.",
          after: "да, then the pronoun, then the verb. The pronoun stays glued to the front of *its* verb, whatever comes before.",
          reviews: ["треба-да", "да-subjunctive", "чекам", "object-pronoun-sg"],
        },
        {
          type: "note",
          title: "Four small words",
          body: "ме, те, го, ја - four tiny words that live in front of the verb. Nothing gets between them and it: не goes before the pair, да goes before the pair, a subject goes before the pair. Their placement will start to *feel* right long before you can explain it.\n\nNext: the plural set.",
          reviews: ["object-pronoun-sg", "clitic-proclitic", "clitic-placement"],
        },
      ],
    },
    {
      id: "m4l4",
      title: "Us, you all, them",
      subtitle: "нѐ, ве, ги",
      items: [
        {
          type: "note",
          title: "Warm-up",
          body: "Before the plural pronouns, let's make sure the singular ones are running.",
        },
        {
          type: "exercise",
          prompt: "**I see him.**",
          answer: "Го гледам",
          hint: "го in front, then гледам.",
          reviews: ["гледам", "object-pronoun-sg", "clitic-proclitic"],
        },
        {
          type: "exercise",
          prompt: "**I don't see her.**",
          answer: "Не ја гледам",
          hint: "не + ја + гледам.",
          after: "Good. Same order as always. Now the plural set.",
          reviews: ["не-negation", "object-pronoun-sg", "гледам", "clitic-placement"],
        },
        {
          type: "note",
          title: "Us",
          body: "The plural pronouns work exactly like the singular ones. Same slot, same rules. First:\n\n- **нѐ** - us\n\n**Нѐ гледаш.** - You see us.\n\nThat little accent mark is there for a reason: it tells **нѐ** (us) apart from **не** (not) on paper. In speech, the stress does the job. You can type it without the accent - the checker won't mind.",
          speak: ["Нѐ гледаш."],
          introduces: ["object-pronoun-pl"],
          he: "אותנו in Hebrew - one word for 'us' as an object, just like нѐ. The difference is only where it sits.",
          bg: "Bulgarian 'us' is ни; Macedonian is нѐ - and ни here means 'to us', which comes in a later lesson.",
        },
        {
          type: "exercise",
          prompt: "**She sees us.**",
          answer: "Таа нѐ гледа",
          accept: ["нѐ гледа"],
          hint: "таа + нѐ + гледа.",
          reviews: ["pronoun-subject", "гледам", "object-pronoun-pl"],
        },
        {
          type: "exercise",
          prompt: "**He doesn't see us.**",
          answer: "Тој не нѐ гледа",
          accept: ["не нѐ гледа"],
          hint: "тој + не (not) + нѐ (us) + гледа.",
          after: "**не нѐ** - 'not us'. Two words that look alike and mean different things. Said aloud, the second one carries the stress.",
          reviews: ["не-negation", "clitic-placement", "гледам", "object-pronoun-pl"],
        },
        {
          type: "exercise",
          prompt: "**He is waiting for us.**",
          answer: "Нѐ чека",
          accept: ["тој нѐ чека"],
          hint: "нѐ + чека (he-form of чекам).",
          reviews: ["чекам", "object-pronoun-pl", "pronoun-drop"],
        },
        {
          type: "note",
          title: "You all",
          body: "- **ве** - you all (plural object)\n\n**Ве чекам.** - I'm waiting for you (all).\n\nAnd now a phrase you've been using since module 2 finally makes sense: **Ве молам** is literally 'you I-beg' - *please*.",
          speak: ["Ве чекам.", "Ве молам."],
          reviews: ["ве молам"],
        },
        {
          type: "exercise",
          prompt: "**I don't understand you (all).**",
          answer: "Не ве разбирам",
          hint: "не + ве + разбирам.",
          reviews: ["не-negation", "разбирам", "clitic-placement", "object-pronoun-pl"],
        },
        {
          type: "exercise",
          prompt: "**I'm waiting for you (all).**",
          answer: "Ве чекам",
          hint: "ве + чекам. Same slot as те.",
          reviews: ["чекам", "object-pronoun-pl", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**She sees you (all).**",
          answer: "Таа ве гледа",
          accept: ["ве гледа"],
          hint: "таа + ве + гледа.",
          reviews: ["pronoun-subject", "гледам", "object-pronoun-pl"],
        },
        {
          type: "note",
          title: "Them",
          body: "- **ги** - them\n\n**Ги гледам.** - I see them.\n\nThat completes the set: ме, те, го, ја, нѐ, ве, ги. Seven tiny words, one slot in front of the verb.",
          speak: ["Ги гледам."],
        },
        {
          type: "exercise",
          prompt: "**I don't understand them.**",
          answer: "Не ги разбирам",
          hint: "не + ги + разбирам.",
          reviews: ["не-negation", "разбирам", "clitic-placement", "object-pronoun-pl"],
        },
        {
          type: "exercise",
          prompt: "**She sees them.**",
          answer: "Таа ги гледа",
          accept: ["ги гледа"],
          hint: "таа + ги + гледа.",
          after: "Same shape as Таа нѐ гледа. The plural pronouns behave exactly like the singular ones.",
          reviews: ["pronoun-subject", "гледам", "object-pronoun-pl"],
        },
        {
          type: "exercise",
          prompt: "**We're waiting for them.**",
          answer: "Ги чекаме",
          accept: ["ние ги чекаме"],
          hint: "ги + чекаме (we-form).",
          reviews: ["чекам", "verb-а-group", "object-pronoun-pl"],
        },
        {
          type: "exercise",
          prompt: "**They don't understand us.**",
          answer: "Не нѐ разбираат",
          accept: ["тие не нѐ разбираат"],
          hint: "не + нѐ + разбираат (they-form, double а).",
          after: "не нѐ again - and the а-group they-form with its double а. You matched two things at once.",
          reviews: ["не-negation", "clitic-placement", "разбирам", "verb-а-group", "object-pronoun-pl"],
        },
        {
          type: "exercise",
          prompt: "**I don't understand you.** (one person)",
          answer: "Не те разбирам",
          hint: "One person = те. не + те + разбирам.",
          reviews: ["не-negation", "object-pronoun-sg", "разбирам", "clitic-placement"],
        },
        {
          type: "exercise",
          prompt: "**She understands me.**",
          answer: "Таа ме разбира",
          accept: ["ме разбира"],
          hint: "таа + ме + разбира.",
          reviews: ["pronoun-subject", "object-pronoun-sg", "разбирам"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you (all) understand us?**",
          answer: "Дали нѐ разбирате?",
          accept: ["Нѐ разбирате ли?"],
          hint: "дали + нѐ + разбирате (you-all form).",
          reviews: ["дали-question", "разбирам", "verb-а-group", "object-pronoun-pl"],
        },
        {
          type: "note",
          title: "Seven small words, one habit",
          body: "ме, те, го, ја, нѐ, ве, ги - seven small words that sit in front of the verb and never let go of it. Their placement will start to *feel* right long before you can explain it. That's normal. It's how natives run it too.\n\nNext lesson: the thing that makes a sentence sound truly Macedonian - saying the object twice.",
          reviews: ["object-pronoun-sg", "object-pronoun-pl", "clitic-proclitic"],
        },
      ],
    },
    {
      id: "m4l5",
      title: "Saying it twice",
      subtitle: "Го чекам Марко. Ја сакам Марија.",
      items: [
        {
          type: "note",
          title: "Warm-up",
          body: "No new words in this lesson. Not one. Everything here is built from pronouns, verbs and nouns you already own - and one habit that will change how your sentences sound. First, two quick ones.",
        },
        {
          type: "exercise",
          prompt: "**I'm waiting for him.**",
          answer: "Го чекам",
          hint: "го + чекам.",
          reviews: ["чекам", "object-pronoun-sg", "clitic-proclitic"],
        },
        {
          type: "exercise",
          prompt: "**I'm waiting for a bus.**",
          answer: "Чекам автобус",
          hint: "чекам + автобус. No pronoun.",
          after: "No pronoun here - *a bus* is just any bus, nobody in particular. Keep that in mind.",
          reviews: ["чекам", "verb-а-group", "pronoun-drop"],
        },
        {
          type: "note",
          title: "Saying it twice",
          body: "Here's the habit. When the person you're waiting for is *specific* - a name - Macedonian says them twice: the little pronoun **and** the name.\n\n**Го чекам Марко.** - I'm waiting for Marko. (literally: 'him I-wait Marko')\n**Ја сакам Марија.** - I love Marija. ('her I-love Marija')\n\nThe pronoun goes where it always goes - in front of the verb - and the name comes after. Leave the pronoun out and the sentence sounds unfinished to a Macedonian ear.",
          speak: ["Го чекам Марко.", "Ја сакам Марија."],
          introduces: ["clitic-doubling"],
          he: "Hebrew's את appears only before a definite object (ראיתי את מרקו, but never את ילד). Macedonian's extra pronoun has the same trigger: definite gets the marker, indefinite doesn't.",
          ru: "Nothing like this in Russian - жду Марко, full stop. The doubled pronoun is a Balkan habit, not a Slavic one.",
          bg: "Bulgarian doubles only for emphasis or clarity (Чакам Петър is the neutral sentence); Macedonian doubles every definite object (Го чекам Петар) - leaving the pronoun out sounds unfinished.",
        },
        {
          type: "exercise",
          prompt: "**I see Marija.**",
          answer: "Ја гледам Марија",
          hint: "Marija is 'her' → ја. ја + гледам + Марија.",
          after: "You put ја in front for a name. That's the whole trick - a name is specific, so the pronoun comes along.",
          reviews: ["clitic-doubling", "гледам", "object-pronoun-sg"],
        },
        {
          type: "exercise",
          prompt: "**I'm waiting for Petar.**",
          answer: "Го чекам Петар",
          hint: "Petar is 'him' → го. го + чекам + Петар.",
          reviews: ["clitic-doubling", "чекам", "object-pronoun-sg"],
        },
        {
          type: "exercise",
          prompt: "**I love Ana.**",
          answer: "Ја сакам Ана",
          hint: "ја + сакам + Ана.",
          after: "Ја сакам Ана - the pronoun matches the name's gender. You checked that without being told.",
          reviews: ["clitic-doubling", "сакам", "object-pronoun-sg"],
        },
        {
          type: "note",
          title: "Nouns with 'the'",
          body: "Names aren't the only specific things. A noun wearing its article - *the* coffee, *the* woman - is specific too, so it gets the same treatment:\n\n**Го сакам кафето.** - I love the coffee.\n**Ја гледам жената.** - I see the woman.\n\nNeuter nouns take **го**, same as masculine. Feminine take **ја**. Match the pronoun to the noun's gender, and you're done.",
          speak: ["Го сакам кафето.", "Ја гледам жената."],
          reviews: ["clitic-doubling", "definite-neuter", "definite-fem", "noun-gender"],
        },
        {
          type: "exercise",
          prompt: "**I love the coffee.**",
          answer: "Го сакам кафето",
          hint: "кафето is neuter → го. го + сакам + кафето.",
          reviews: ["clitic-doubling", "сакам", "кафе", "definite-neuter"],
        },
        {
          type: "exercise",
          prompt: "**I see the woman.**",
          answer: "Ја гледам жената",
          hint: "жената is feminine → ја.",
          reviews: ["clitic-doubling", "гледам", "жена", "definite-fem"],
        },
        {
          type: "exercise",
          prompt: "**I'm waiting for the man.**",
          answer: "Го чекам мажот",
          hint: "маж + -от = мажот, masculine → го.",
          after: "Masculine article -от, pronoun го in front. Two agreements, one sentence.",
          reviews: ["clitic-doubling", "чекам", "маж", "definite-masc"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you see the sea?**",
          answer: "Дали го гледаш морето?",
          accept: ["Го гледаш ли морето?"],
          hint: "морето is neuter → го. дали + го + гледаш + морето.",
          reviews: ["clitic-doubling", "дали-question", "море", "definite-neuter"],
        },
        {
          type: "note",
          title: "And when it's not specific",
          body: "The other half of the rule, which you've been using all along without a name for it:\n\n**Чекам автобус.** - I'm waiting for a bus.\n**Сакам кафе.** - I want coffee.\n\nNo article, nobody in particular - no pronoun. So: *the* coffee → twice. *A* coffee → once. The article and the pronoun travel together.",
          speak: ["Чекам автобус.", "Сакам кафе."],
          reviews: ["clitic-doubling"],
        },
        {
          type: "exercise",
          prompt: "**I want coffee.**",
          answer: "Сакам кафе",
          hint: "No article, so no pronoun. Just сакам + кафе.",
          reviews: ["сакам", "кафе", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**I want the coffee.**",
          answer: "Го сакам кафето",
          hint: "The article is there → the pronoun comes too.",
          after: "Сакам кафе / Го сакам кафето. Same words, one article, one extra pronoun. You're hearing the difference now.",
          reviews: ["clitic-doubling", "сакам", "кафе", "definite-neuter"],
        },
        {
          type: "exercise",
          prompt: "**I'm watching a film.**",
          answer: "Гледам филм",
          hint: "a film - not specific.",
          reviews: ["гледам", "verb-а-group", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**I'm watching the film.**",
          answer: "Го гледам филмот",
          hint: "филм + -от = филмот, masculine → го.",
          reviews: ["clitic-doubling", "гледам", "definite-masc"],
        },
        {
          type: "note",
          title: "Plural things",
          body: "Specific plurals get **ги**, the 'them' from last lesson:\n\n**Ги гледам студентите.** - I see the students.\n\nSame rule, plural size.",
          speak: ["Ги гледам студентите."],
          reviews: ["clitic-doubling", "object-pronoun-pl", "plural-и"],
        },
        {
          type: "exercise",
          prompt: "**I see the students.**",
          answer: "Ги гледам студентите",
          hint: "ги + гледам + студентите.",
          reviews: ["clitic-doubling", "object-pronoun-pl", "гледам", "plural-и"],
        },
        {
          type: "exercise",
          prompt: "**I don't understand the tourists.**",
          answer: "Не ги разбирам туристите",
          hint: "не + ги + разбирам + туристите.",
          after: "не, then ги, then the verb, then the noun. Doubling doesn't change the order you already know - it just adds the noun at the end.",
          reviews: ["clitic-doubling", "clitic-placement", "разбирам", "object-pronoun-pl"],
        },
        {
          type: "exercise",
          prompt: "**She doesn't understand the students.**",
          answer: "Таа не ги разбира студентите",
          accept: ["не ги разбира студентите"],
          hint: "таа + не + ги + разбира + студентите.",
          reviews: ["clitic-doubling", "clitic-placement", "разбирам", "pronoun-subject"],
        },
        {
          type: "note",
          title: "Me, myself",
          body: "One more thing that counts as specific: you. When you want to stress *me* - not someone else - there's a long form, **мене**, and the short **ме** comes along with it:\n\n**Мене ме разбираш?** - Do you understand *me*?\n\nFor *you* it's **тебе**: **Тебе те сакам.** - It's *you* I love.\n\nYou don't need the long form in ordinary sentences. It's there for when the person matters.",
          speak: ["Мене ме разбираш?", "Тебе те сакам."],
          reviews: ["clitic-doubling", "object-pronoun-sg"],
          he: "Like adding דווקא: אותי אתה מבין? The long pronoun does the pointing; the short one is still required.",
        },
        {
          type: "exercise",
          prompt: "Ask, stressing *me*: **Do you understand me?**",
          answer: "Мене ме разбираш?",
          accept: ["Дали мене ме разбираш?", "Мене ли ме разбираш?"],
          hint: "мене (long) + ме (short) + разбираш.",
          reviews: ["clitic-doubling", "разбирам", "object-pronoun-sg"],
        },
        {
          type: "exercise",
          prompt: "Say, stressing *you*: **It's you I love.**",
          answer: "Тебе те сакам",
          hint: "тебе + те + сакам.",
          after: "Тебе те сакам. The long form points, the short form stays - that's doubling with a pronoun instead of a name.",
          reviews: ["clitic-doubling", "сакам", "object-pronoun-sg"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you see Marko?**",
          answer: "Дали го гледаш Марко?",
          accept: ["Го гледаш ли Марко?"],
          hint: "A name → doubled. дали + го + гледаш + Марко.",
          reviews: ["clitic-doubling", "дали-question", "гледам"],
        },
        {
          type: "exercise",
          prompt: "**We're waiting for Elena and Nikola.**",
          answer: "Ги чекаме Елена и Никола",
          accept: ["ние ги чекаме Елена и Никола"],
          hint: "Two people → them → ги. ги + чекаме + the names.",
          after: "Two names make a plural, so ги. You counted before you chose the pronoun - exactly the right order of thinking.",
          reviews: ["clitic-doubling", "object-pronoun-pl", "чекам", "и-conjunction"],
        },
        {
          type: "exercise",
          prompt: "**Marija is waiting for the doctor.**",
          answer: "Марија го чека докторот",
          hint: "Марија + го + чека + докторот.",
          after: "A full Macedonian sentence: subject, pronoun, verb, the doubled noun. Nothing in it is new - only the shape.",
          reviews: ["clitic-doubling", "чекам", "definite-masc", "verb-а-group"],
        },
        {
          type: "note",
          title: "Why twice?",
          body: "Specific object - a name, a noun with its article, a long pronoun - and the short pronoun shows up in front of the verb as well. Not specific - no pronoun.\n\nThat's the whole rule. It is the single habit that makes a sentence sound Macedonian rather than translated, and you've now used it a dozen times. From here on, every time you say *the* something after a verb, expect the little word in front.",
          reviews: ["clitic-doubling", "clitic-proclitic"],
        },
      ],
    },
    {
      id: "m4l6",
      title: "Mine and yours",
      subtitle: "колата ми, мајка ми, кафе со млеко",
      items: [
        {
          type: "note",
          title: "Warm-up",
          body: "Let's make sure those object pronouns are settling in before we move on to ownership.",
        },
        {
          type: "exercise",
          prompt: "**I'm waiting for her.**",
          answer: "Ја чекам",
          hint: "ја + чекам.",
          reviews: ["чекам", "object-pronoun-sg", "clitic-proclitic"],
        },
        {
          type: "exercise",
          prompt: "**I don't understand them.**",
          answer: "Не ги разбирам",
          hint: "не + ги + разбирам.",
          reviews: ["разбирам", "не-negation", "object-pronoun-pl", "clitic-placement"],
        },
        {
          type: "exercise",
          prompt: "**I'm waiting for Marija.**",
          answer: "Ја чекам Марија",
          hint: "A name → say it twice: ја + чекам + Марија.",
          after: "Good. Doubling is still running. Now - who owns what.",
          reviews: ["clitic-doubling", "чекам", "object-pronoun-sg"],
        },
        {
          type: "note",
          title: "'s and 'of' - both are на",
          body: "When one noun owns another, **на** does all the work:\n\n**колата на Марија** - Marija's car (literally 'the-car of Marija')\n\nNo apostrophe-s, no cases. Just на + the owner. The owned thing wears its article.",
          speak: ["колата на Марија"],
          he: "Same word order as של: האוטו **של מריה** = колата **на Марија**. Noun first, owner after.",
          ru: "This replaces the entire Russian genitive: машина Марии → колата на Марија. Preposition + unchanged noun. One less declension to carry.",
          introduces: ["на-possession"],
        },
        {
          type: "exercise",
          prompt: "**Petar's car**",
          answer: "колата на Петар",
          hint: "the-car + на + the name.",
          reviews: ["кола", "definite-fem", "на-possession"],
        },
        {
          type: "exercise",
          prompt: "**Marija's house**",
          answer: "куќата на Марија",
          hint: "the-house + на + the name.",
          reviews: ["куќа", "definite-fem", "на-possession"],
        },
        {
          type: "exercise",
          prompt: "**The coffee is Petar's.**",
          answer: "Кафето е на Петар",
          hint: "кафето (neuter article) + е + на + the name.",
          reviews: ["definite-neuter", "сум-present", "на-possession"],
        },
        {
          type: "note",
          title: "My",
          body: "For *your own* stuff, even shorter - a tiny word after the definite noun:\n\n- **ми** - my\n\n**колата ми** - my car (literally 'the-car to-me')\n\nThe same **ми** you've been saying in Мило ми е. It means 'to me', and after a noun that turns into 'my'.",
          speak: ["колата ми"],
          introduces: ["dative-ми"],
          he: "Hebrew has this too: הבית שלי - noun, then the owner-word after it. Same order, and Macedonian's version is even shorter.",
          ru: "Russian моя машина puts a possessive adjective in front; Macedonian hangs a tiny 'to me' off the back of the noun. Same job, opposite side.",
        },
        {
          type: "exercise",
          prompt: "**my car**",
          answer: "колата ми",
          hint: "Definite noun + ми: колата + ми.",
          reviews: ["кола", "definite-fem", "dative-ми"],
        },
        {
          type: "exercise",
          prompt: "**my house**",
          answer: "куќата ми",
          hint: "the-house + ми.",
          reviews: ["куќа", "definite-fem", "dative-ми"],
        },
        {
          type: "exercise",
          prompt: "**My coffee is good.**",
          answer: "Кафето ми е добро",
          hint: "кафето (neuter article) + ми + е + добро (neuter).",
          after: "Article on the noun, ми right after it, then the sentence carries on. The noun keeps its article - that's what ми hangs on.",
          reviews: ["definite-neuter", "dative-ми", "сум-present", "добар", "adj-agreement"],
        },
        {
          type: "note",
          title: "Your",
          body: "Same pattern, different person:\n\n- **ти** - your\n\n**куќата ти** - your house\n\nYes, it looks like the pronoun *you*. After a definite noun it can only mean 'your' - the position tells you.",
          speak: ["куќата ти"],
          he: "Same word order as של: הבית **שלך** = куќата **ти**. Noun first, owner after.",
        },
        {
          type: "exercise",
          prompt: "**your house**",
          answer: "куќата ти",
          hint: "Definite noun + ти: куќата + ти.",
          reviews: ["куќа", "definite-fem", "dative-ми"],
        },
        {
          type: "exercise",
          prompt: "**Your car is new.**",
          answer: "Колата ти е нова",
          hint: "колата + ти + е + нова (feminine).",
          reviews: ["adj-agreement", "кола", "definite-fem", "dative-ми", "нов"],
        },
        {
          type: "exercise",
          prompt: "**Your telephone is here.**",
          answer: "Телефонот ти е тука",
          accept: ["Телефонот ти е овде"],
          hint: "телефон + -от = телефонот, then ти.",
          after: "Masculine article -от, then ти. Works on any gender - the little word doesn't care.",
          reviews: ["телефон", "definite-masc", "dative-ми", "тука"],
        },
        {
          type: "note",
          title: "His",
          body: "One more owner:\n\n- **му** - his\n\n**куќата му** - his house",
          speak: ["куќата му"],
          introduces: ["dative-му-ѝ"],
        },
        {
          type: "exercise",
          prompt: "**his house**",
          answer: "куќата му",
          hint: "the-house + му.",
          reviews: ["куќа", "definite-fem", "dative-му-ѝ"],
        },
        {
          type: "exercise",
          prompt: "**His car is good.**",
          answer: "Колата му е добра",
          hint: "колата + му + е + добра (feminine).",
          reviews: ["кола", "definite-fem", "добар", "adj-agreement", "dative-му-ѝ"],
        },
        {
          type: "note",
          title: "Her",
          body: "- **ѝ** - her (as an owner)\n\n**колата ѝ** - her car\n\nThat accent mark separates it from **и** (and) in writing. Typing a plain и is fine - the checker knows.",
          speak: ["колата ѝ"],
          ru: "Russian её is a whole word; Macedonian 'her' as owner is a single letter with a hat on it.",
        },
        {
          type: "exercise",
          prompt: "**her car**",
          answer: "колата ѝ",
          hint: "the-car + ѝ.",
          reviews: ["кола", "definite-fem", "dative-му-ѝ"],
        },
        {
          type: "exercise",
          prompt: "**Her house is big.**",
          answer: "Куќата ѝ е голема",
          hint: "куќата + ѝ + е + голема (feminine of голем).",
          reviews: ["adj-agreement", "куќа", "definite-fem", "голем", "dative-му-ѝ"],
        },
        {
          type: "note",
          title: "Family drops the article",
          body: "With close family, the article disappears. One new noun to show this:\n\n**Мајка** = *mother* (feminine).\n\n- **мајка ми** - my mother (not *мајката ми*)\n\nOnly close family words do this - they skip 'the' before the owner-word.",
          speak: ["мајка ми"],
          ru: "**Мајка** = *mother*. In Russian, майка is an undershirt. Possibly the most important false friend in the language.",
          bg: "Bulgarian майка → мајка (й → ј); the article drops in both languages.",
          introduces: ["family-article-drop"],
        },
        {
          type: "exercise",
          prompt: "**my mother**",
          answer: "мајка ми",
          hint: "Close family drops 'the' - just мајка + ми.",
          reviews: ["мајка", "family-article-drop", "dative-ми"],
        },
        {
          type: "exercise",
          prompt: "**your mother**",
          answer: "мајка ти",
          hint: "Close family drops 'the' - мајка + ти.",
          reviews: ["мајка", "family-article-drop", "dative-ми"],
        },
        {
          type: "exercise",
          prompt: "**His mother is from Bitola.**",
          answer: "Мајка му е од Битола",
          hint: "мајка му (no article) + е + од + Битола.",
          after: "No article, му right after, then е од. Family words are the one place the article goes missing.",
          reviews: ["мајка", "family-article-drop", "dative-му-ѝ", "од-from"],
        },
        {
          type: "note",
          title: "Father",
          body: "One more family noun: **татко** = *father*.\n\nIt ends in -о but it's masculine - it's a person, and the ending doesn't get a vote.\n\n**татко ми** - my father (again, no article with close family).",
          speak: ["татко ми"],
          ru: "Not Russian отец or папа - татко is the ordinary, neutral word for father here.",
          bg: "Bulgarian баща; Macedonian татко is the normal word for father, not baby talk.",
        },
        {
          type: "exercise",
          prompt: "**My father lives in Skopje.**",
          answer: "Татко ми живее во Скопје",
          hint: "татко ми (no article) + живее + во + Скопје.",
          after: "No article on татко, живее from this module, во from this module. Everything connecting.",
          reviews: ["татко", "живеам", "во-in", "verb-е-group", "family-article-drop"],
        },
        {
          type: "exercise",
          prompt: "**His father is a doctor.**",
          answer: "Татко му е доктор",
          hint: "татко му (no article, family) + е + доктор.",
          reviews: ["татко", "сум-present", "family-article-drop", "dative-му-ѝ"],
        },
        {
          type: "exercise",
          prompt: "**Her father is waiting for us.**",
          answer: "Татко ѝ нѐ чека",
          hint: "татко ѝ (her father) + нѐ (us) + чека.",
          after: "ѝ after the noun means 'her'; нѐ in front of the verb means 'us'. Two tiny words, two different slots, no confusion.",
          reviews: ["татко", "dative-му-ѝ", "object-pronoun-pl", "чекам"],
        },
        {
          type: "note",
          title: "With",
          body: "**Со** = *with*. Another small word that never changes:\n\n- **кафе со млеко** - coffee with milk\n- **чај со млеко** - tea with milk\n\n**Млеко** = *milk* (neuter, ends in -о).",
          speak: ["кафе со млеко", "чај со млеко"],
          introduces: ["со-with"],
          ru: "Russian с → Macedonian со, always with the о - like во.",
          bg: "Bulgarian с (със before с/з); Macedonian is always со. And мляко → млеко (я → е).",
        },
        {
          type: "exercise",
          prompt: "**I want coffee with milk, please.**",
          answer: "Сакам кафе со млеко, Ве молам",
          accept: ["Сакам кафе со млеко, молам"],
          hint: "сакам + кафе со млеко + Ве молам.",
          after: "You can order coffee exactly how you want it now. No article on кафе, so no doubling - just as it should be.",
          reviews: ["сакам", "млеко", "со-with", "ве молам"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Can I have tea with milk?**",
          answer: "Може ли чај со млеко?",
          accept: ["Може ли чај со млеко, Ве молам?"],
          hint: "Може ли + чај + со + млеко.",
          reviews: ["може-ли-polite", "чај", "млеко", "со-with"],
        },
        {
          type: "exercise",
          prompt: "**I live with my mother.**",
          answer: "Живеам со мајка ми",
          accept: ["јас живеам со мајка ми"],
          hint: "живеам + со + мајка ми (no article for family).",
          reviews: ["живеам", "мајка", "со-with", "family-article-drop"],
        },
        {
          type: "exercise",
          prompt: "**My mother is from Germany.**",
          answer: "Мајка ми е од Германија",
          hint: "мајка ми (no article) + е + од + Германија.",
          reviews: ["мајка", "сум-present", "од-from", "family-article-drop"],
        },
        {
          type: "exercise",
          prompt: "**I see your car.**",
          answer: "Ја гледам колата ти",
          hint: "колата ти is specific → ја in front. Not те - that would mean 'I see you'.",
          after: "*Your car* has an article, so it's specific, so ја shows up. Last lesson's rule, this lesson's words.",
          reviews: ["clitic-doubling", "гледам", "кола", "dative-ми"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you see my car?**",
          answer: "Дали ја гледаш колата ми?",
          accept: ["Ја гледаш ли колата ми?"],
          hint: "дали + ја + гледаш + колата ми.",
          reviews: ["clitic-doubling", "дали-question", "гледам", "dative-ми"],
        },
        {
          type: "exercise",
          prompt: "**I'm waiting for your mother.**",
          answer: "Ја чекам мајка ти",
          hint: "мајка ти is a specific person → ја in front, even though the article is gone.",
          after: "No article on мајка, but she's still specific - so the doubling pronoun comes anyway. The rule is about who, not about the suffix.",
          reviews: ["clitic-doubling", "чекам", "мајка", "family-article-drop"],
        },
        {
          type: "exercise",
          prompt: "**Her mother lives in Ohrid.**",
          answer: "Мајка ѝ живее во Охрид",
          hint: "мајка ѝ + живее + во + Охрид.",
          reviews: ["мајка", "dative-му-ѝ", "живеам", "во-in"],
        },
        {
          type: "note",
          title: "People start belonging to each other",
          body: "на for someone else's things, ми/ти/му/ѝ after the noun for yours, family without 'the', со for company. Four small patterns - and every one of them uses a slot you already knew.\n\nLook back at where this module started: Се викам. You've now got introductions, where you live, who sees whom, saying it twice, and whose it is. That's a conversation.",
          reviews: ["на-possession", "dative-ми", "dative-му-ѝ", "family-article-drop", "со-with"],
        },
      ],
    },
  ],
};
