import type { Module } from "./types";

export const module2: Module = {
  id: "m2",
  title: "3. Wanting and having",
  blurb:
    "Your first action verbs, a 'the' that sticks to the end of the word, and the little glue that replaces every English 'to': да.",
  lessons: [
    {
      id: "m2l1",
      title: "I want",
      subtitle: "сакам, Ве молам, and the article -то",
      items: [
        {
          type: "note",
          title: "The I-form ends in -м",
          body:
            "Time for a verb that does something. **Сакам** = I want.\n\nHere is a gift. In Macedonian the I-form of *every* verb ends in **-м**. Сакам, and every verb you will ever meet. You already know one - **сум** - and even that odd little verb keeps the rule.\n\nSo a verb ending in -м means 'I', and you don't need the pronoun: **Сакам кафе.** - I want coffee.",
          he: "Like Hebrew's past tense, where the ending tells you who (הלכתי = I went), the -м alone tells you it's 'I'.",
          ru: "Russian хочу and Macedonian сакам share nothing but the job. Don't reach for хоч- here.",
          bg: "Bulgarian I-forms split between -м (искам) and -я (говоря, уча); Macedonian has only -м: сакам, зборувам, учам. And the verb itself is сакам, not искам.",
          speak: ["сакам", "Сакам кафе."],
          introduces: ["verb-м-first-person"],
        },
        {
          type: "exercise",
          prompt: "How would you say: **I want coffee.**",
          answer: "Сакам кафе",
          accept: ["јас сакам кафе"],
          hint: "сакам = I want. кафе = coffee, the same word as café.",
          after: "Two words, and the -м already told everyone who wants it.",
          reviews: ["verb-м-first-person", "pronoun-drop", "кафе"],
        },
        {
          type: "exercise",
          prompt: "**I want water.** (вода = water)",
          answer: "Сакам вода",
          accept: ["јас сакам вода"],
          hint: "сакам + вода.",
          reviews: ["verb-м-first-person", "pronoun-drop", "вода"],
        },
        {
          type: "exercise",
          prompt: "**I don't want tea.**",
          answer: "Не сакам чај",
          accept: ["јас не сакам чај"],
          hint: "не goes right before the verb, just as it did with сум.",
          after: "Не сакам. Same не, same spot. You will never need a second negation rule.",
          reviews: ["не-negation", "verb-м-first-person", "чај", "pronoun-drop"],
        },
        {
          type: "note",
          title: "You want: сакаш",
          body:
            "Change the ending, change the person. **Сакаш** = you want. The **-ш** means 'you', and the **а** in front of it is what makes сакам an *а-verb*. Most verbs you meet in this module belong to this group, so once you own сакам you own them all.\n\n**Дали сакаш кафе?** - Do you want coffee?",
          speak: ["сакаш", "Дали сакаш кафе?"],
          introduces: ["verb-а-group"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you want coffee?**",
          answer: "Дали сакаш кафе?",
          accept: ["сакаш ли кафе", "дали ти сакаш кафе"],
          hint: "дали at the front, then сакаш.",
          after: "Same дали you used with сум. It works with every verb, and ли still works too: Сакаш ли кафе?",
          reviews: ["дали-question", "verb-а-group", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you want water?**",
          answer: "Дали сакаш вода?",
          accept: ["сакаш ли вода"],
          hint: "дали + сакаш + вода?",
          reviews: ["дали-question", "verb-а-group", "вода"],
        },
        {
          type: "exercise",
          prompt: "**You don't want tea.**",
          answer: "Не сакаш чај",
          accept: ["ти не сакаш чај"],
          hint: "не + сакаш.",
          reviews: ["не-negation", "verb-а-group", "чај", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Don't you want coffee?**",
          answer: "Не сакаш ли кафе?",
          hint: "не + сакаш + ли - the negative-question shape from module 1.",
          after: "You put ли right after the thing you doubt: не сакаш ли. The pattern carried over from сум without a scratch.",
          reviews: ["neg-question", "ли-question", "не-negation", "verb-а-group"],
        },
        {
          type: "note",
          title: "He wants, she wants: сака",
          body:
            "Drop the -ш and you get the he/she form: **сака**. Nothing after the а.\n\n**Тој сака чај.** - He wants tea.\n**Таа сака вода.** - She wants water.",
          speak: ["сака", "Тој сака чај.", "Таа сака вода."],
        },
        {
          type: "exercise",
          prompt: "**He wants tea.**",
          answer: "Тој сака чај",
          accept: ["сака чај"],
          hint: "He-form: сака - the stem and nothing else.",
          reviews: ["pronoun-subject", "verb-а-group", "чај"],
        },
        {
          type: "exercise",
          prompt: "**She wants water.**",
          answer: "Таа сака вода",
          accept: ["сака вода"],
          hint: "Same form as for 'he': сака.",
          after: "Тој сака, таа сака - the verb doesn't care about gender. Only the pronoun does.",
          reviews: ["pronoun-subject", "verb-а-group", "вода"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Does she want coffee?**",
          answer: "Дали таа сака кафе?",
          accept: ["дали сака кафе", "сака ли кафе", "таа сака ли кафе"],
          hint: "дали first, then the rest of the sentence in its normal order.",
          after: "Дали simply sits in front of the statement. That is why it is the easiest question word you will ever learn.",
          reviews: ["дали-question", "pronoun-subject", "verb-а-group"],
        },
        {
          type: "note",
          title: "We want: сакаме",
          body:
            "**Сакаме** = we want. The **-ме** is the same 'we' marker you know from **сме**. Look: с**ме**, сака**ме**.",
          speak: ["сакаме", "Сакаме кафе."],
        },
        {
          type: "exercise",
          prompt: "**We want water.**",
          answer: "Сакаме вода",
          accept: ["ние сакаме вода"],
          hint: "We-form ends in -ме: сакаме.",
          reviews: ["verb-а-group", "вода", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**We don't want tea.**",
          answer: "Не сакаме чај",
          accept: ["ние не сакаме чај"],
          hint: "не + сакаме.",
          reviews: ["не-negation", "verb-а-group", "чај"],
        },
        {
          type: "exercise",
          prompt: "**We are from Skopje and we want coffee.**",
          answer: "Ние сме од Скопје и сакаме кафе",
          accept: ["од скопје сме и сакаме кафе", "ние сме од скопје и ние сакаме кафе"],
          hint: "сме од Скопје... и сакаме кафе.",
          after: "You just put сум and a real verb in one sentence, with од and и holding it together. That is module 1 and module 2 shaking hands.",
          reviews: ["сум-present", "од-from", "и-conjunction", "verb-а-group"],
        },
        {
          type: "note",
          title: "You all want: сакате",
          body:
            "**Сакате** = you all want. The **-те** is the 'you all' marker from **сте**. Same trick as before: с**те**, сака**те**.",
          speak: ["сакате", "Дали сакате чај?"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you all want coffee?**",
          answer: "Дали сакате кафе?",
          accept: ["сакате ли кафе", "дали вие сакате кафе"],
          hint: "дали + сакате + кафе?",
          reviews: ["дали-question", "verb-а-group", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**You all want tea.**",
          answer: "Сакате чај",
          accept: ["вие сакате чај"],
          hint: "You-all form: сакате.",
          reviews: ["verb-а-group", "чај", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**You all don't want water.**",
          answer: "Не сакате вода",
          accept: ["вие не сакате вода"],
          hint: "не + сакате.",
          after: "-ме for we, -те for you all. The same two syllables you learned with сме and сте are doing the work again.",
          reviews: ["не-negation", "verb-а-group", "вода"],
        },
        {
          type: "note",
          title: "They want: сакаат",
          body:
            "**Сакаат** = they want. The 'they' ending is **-ат**, and it goes onto сака-, so you get two а's in a row: сака + ат = **сакаат**. Say both of them: sa-ka-at.\n\n**Тие сакаат кафе.** - They want coffee.",
          bg: "Bulgarian искат has one а; Macedonian а-verbs double it in the they-form: сакаат, имаат, зборуваат.",
          speak: ["сакаат", "Тие сакаат кафе."],
        },
        {
          type: "exercise",
          prompt: "**They want coffee.**",
          answer: "Тие сакаат кафе",
          accept: ["сакаат кафе"],
          hint: "They-form: сака + ат. Two а's.",
          after: "Сакаат. If you wrote only one а, you wrote 'he wants' with a stray т. The double а is the whole difference.",
          reviews: ["pronoun-subject", "verb-а-group"],
        },
        {
          type: "exercise",
          prompt: "**He wants coffee and they want tea.**",
          answer: "Тој сака кафе и тие сакаат чај",
          accept: ["тој сака кафе и сакаат чај"],
          hint: "сака (he) versus сакаат (they). и = and.",
          reviews: ["pronoun-subject", "и-conjunction", "verb-а-group", "чај"],
        },
        {
          type: "exercise",
          prompt: "**They don't want coffee, they want tea.**",
          answer: "Тие не сакаат кафе, сакаат чај",
          accept: ["не сакаат кафе, сакаат чај", "тие не сакаат кафе, тие сакаат чај"],
          hint: "не сакаат... сакаат...",
          after: "Every form of сакам has now passed through your hands: сакам, сакаш, сака, сакаме, сакате, сакаат. Six endings, and they will fit every а-verb you meet.",
          reviews: ["не-negation", "pronoun-subject", "verb-а-group"],
        },
        {
          type: "note",
          title: "Please: Ве молам",
          body:
            "**Ве молам** = please. Two words that always travel together; write the В as a capital. At a cafe:\n\n**Кафе, Ве молам.** - Coffee, please.\n**Вода, Ве молам.** - Water, please.\n\nThat is a complete, polite order. No verb needed.",
          he: "Like בבקשה, it works on its own after the thing you want: קפה, בבקשה. Кафе, Ве молам.",
          bg: "Bulgarian's one-word моля is a two-word Ве молам here (literally 'I beg you'). On its own, Молам? means 'pardon?'.",
          speak: ["Ве молам", "Кафе, Ве молам.", "Вода, Ве молам."],
        },
        {
          type: "exercise",
          prompt: "**Water, please.**",
          answer: "Вода, Ве молам",
          hint: "вода = water, then Ве молам.",
          reviews: ["вода", "ве молам"],
        },
        {
          type: "exercise",
          prompt: "**Tea, please.**",
          answer: "Чај, Ве молам",
          hint: "чај = tea, then Ве молам.",
          reviews: ["чај", "ве молам"],
        },
        {
          type: "exercise",
          prompt: "**I want water, please.**",
          answer: "Сакам вода, Ве молам",
          accept: ["јас сакам вода, ве молам"],
          hint: "сакам вода, then the polite tail.",
          after: "Сакам вода, Ве молам. Direct and polite at the same time - that is how people actually order.",
          reviews: ["verb-а-group", "вода", "ве молам", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**We want coffee, please.**",
          answer: "Сакаме кафе, Ве молам",
          accept: ["ние сакаме кафе, ве молам"],
          hint: "сакаме = we want.",
          reviews: ["verb-а-group", "ве молам", "pronoun-drop"],
        },
        {
          type: "note",
          title: "'The' lives at the end",
          body:
            "Macedonian has no separate word for 'the'. It hangs 'the' on the end of the noun:\n\nкафе + **-то** = **кафето** (the coffee)\n\n**Кафето е тука.** - The coffee is here.",
          he: "Hebrew's ה goes on the front (הקפה); Macedonian's goes on the back: кафе**то**. Same idea, other end.",
          ru: "Russian has no article at all. Here 'the' is real, and it is a suffix.",
          speak: ["кафето", "Кафето е тука."],
          introduces: ["definite-neuter"],
        },
        {
          type: "exercise",
          prompt: "**The coffee is here.**",
          answer: "Кафето е тука",
          accept: ["кафето е овде"],
          hint: "кафе + -то = кафето.",
          after: "Кафето е тука. Your first Macedonian article, and you didn't need a new word for it.",
          reviews: ["definite-neuter", "сум-present", "тука"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Is the coffee here?**",
          answer: "Дали кафето е тука?",
          accept: ["дали е кафето тука", "кафето тука ли е", "тука ли е кафето", "дали кафето е овде"],
          hint: "дали + the statement 'the coffee is here'.",
          reviews: ["definite-neuter", "дали-question", "сум-present", "тука"],
        },
        {
          type: "exercise",
          prompt: "**The coffee is not here, it's there.**",
          answer: "Кафето не е тука, таму е",
          accept: ["кафето не е овде, таму е", "кафето не е тука, тоа е таму"],
          hint: "не е тука... then 'there' first, then е.",
          after: "Таму е - the description first, then е, the way you learned to say Студент сум. The article rode along without any fuss.",
          reviews: ["definite-neuter", "не-negation", "сум-position", "таму"],
        },
        {
          type: "note",
          title: "At the cafe",
          body:
            "You can already survive a Skopje cafe. Order: **Кафе, Ве молам.** Ask a question: **Дали сакаш чај?** When you're done: **Сметка, Ве молам.** (**сметка** = the bill)\n\nThose aren't toy sentences. That is what people say.",
          speak: ["Кафе, Ве молам.", "Дали сакаш чај?", "Сметка, Ве молам."],
        },
        {
          type: "exercise",
          prompt: "Ask for the bill.",
          answer: "Сметка, Ве молам",
          hint: "сметка = bill, then Ве молам.",
          after: "Сметка, Ве молам. Most people hang a 'the' on it - сметката - and you'll be able to do that yourself next lesson.",
          reviews: ["сметка", "ве молам"],
        },
      ],
    },
    {
      id: "m2l2",
      title: "Having and not having",
      subtitle: "имам, немам, and two more articles",
      items: [
        {
          type: "note",
          title: "To have: a real verb",
          body:
            "**Имам** = I have. It's an а-verb like сакам, so you already know its shape: **имам** (I), **имаш** (you), **има** (he/she). Same endings, new stem.\n\n**Имам проблем.** - I have a problem.",
          he: "Hebrew has no verb 'to have' - יש לי is 'there is to me'. Macedonian has a real verb, имам, and it goes exactly where English 'have' goes.",
          ru: "No у меня есть here. Macedonian says имам - subject, verb, done.",
          speak: ["имам", "имаш", "има", "Имам проблем."],
        },
        {
          type: "exercise",
          prompt: "**I have a problem.**",
          answer: "Имам проблем",
          accept: ["јас имам проблем"],
          hint: "имам = I have. Same -м as сакам.",
          reviews: ["verb-а-group", "verb-м-first-person", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you have a phone?**",
          answer: "Дали имаш телефон?",
          accept: ["имаш ли телефон"],
          hint: "дали + имаш + телефон?",
          after: "Имаш - the -ш you know from сакаш, on a new verb. The endings are a set of clothes any а-verb can wear.",
          reviews: ["verb-а-group", "дали-question", "телефон", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**They have a car.** (кола = car)",
          answer: "Тие имаат кола",
          accept: ["имаат кола"],
          hint: "They-form: има + ат. Two а's, just like сакаат.",
          after: "Имаат. The double а again - once you've seen it on one verb you'll see it on all of them.",
          reviews: ["verb-а-group", "pronoun-subject", "кола"],
        },
        {
          type: "note",
          title: "немам: the fused 'don't have'",
          body:
            "'Not have' fused into a verb of its own: **немам** (never 'не имам'). Same endings, just swap им- for нем-: немам, немаш, нема.\n\n**Немам кола.** - I don't have a car.\n**Таа нема кола.** - She doesn't have a car.",
          bg: "Bulgarian нямам becomes немам by the я→е rule; the fusion itself is the same.",
          speak: ["немам", "Немам кола.", "Таа нема кола."],
          introduces: ["немам-fused"],
        },
        {
          type: "exercise",
          prompt: "**I don't have a car.**",
          answer: "Немам кола",
          accept: ["јас немам кола"],
          hint: "The fused verb - немам - not 'не имам'.",
          reviews: ["немам-fused", "verb-а-group", "кола"],
        },
        {
          type: "exercise",
          prompt: "**He doesn't have a phone.**",
          answer: "Тој нема телефон",
          accept: ["нема телефон"],
          hint: "He-form: нема - nothing after the а.",
          after: "Нема. You built the he-form of a verb you met thirty seconds ago, because the endings are already yours.",
          reviews: ["немам-fused", "verb-а-group", "pronoun-subject"],
        },
        {
          type: "exercise",
          prompt: "**We don't have coffee.**",
          answer: "Немаме кафе",
          accept: ["ние немаме кафе"],
          hint: "We-form: -ме on нема-.",
          reviews: ["немам-fused", "verb-а-group", "pronoun-drop"],
        },
        {
          type: "note",
          title: "A second tail: -та",
          body:
            "Кола doesn't take -то. It takes **-та**:\n\nкола + **-та** = **колата** (the car)\n\nA different tail from кафе**то**. Don't sort them out yet - just notice that there is more than one.",
          speak: ["колата", "Колата е таму."],
          introduces: ["definite-fem"],
        },
        {
          type: "exercise",
          prompt: "**The car is there.**",
          answer: "Колата е таму",
          hint: "кола + -та.",
          reviews: ["definite-fem", "сум-present", "таму"],
        },
        {
          type: "exercise",
          prompt: "**The water is here.**",
          answer: "Водата е тука",
          accept: ["водата е овде"],
          hint: "вода ends the same way as кола, so it takes the same tail.",
          after: "Водата - you matched the tail to the ending of the word. That instinct is the whole trick, and it is already working.",
          reviews: ["definite-fem", "вода", "сум-present", "тука"],
        },
        {
          type: "note",
          title: "There is, there isn't",
          body:
            "Bare **има** also means 'there is'; bare **нема** - 'there isn't':\n\n**Има кафе.** - There's coffee.\n**Има вино.** - There's wine. (**вино** = wine)\n**Нема проблем!** - No problem! You will hear this ten times a day.",
          he: "Hebrew יש / אין do exactly this job, and they don't change for person either.",
          ru: "Russian нету as 'there isn't' is the job нема does here; if you know Ukrainian, нема is simply the same word.",
          speak: ["Има кафе.", "Има вино.", "Нема проблем!"],
          introduces: ["има-existential"],
        },
        {
          type: "exercise",
          prompt: "**There is no coffee.**",
          answer: "Нема кафе",
          hint: "Bare нема = there isn't.",
          reviews: ["има-existential", "немам-fused"],
        },
        {
          type: "exercise",
          prompt: "**There is coffee. Do you all want coffee?**",
          answer: "Има кафе. Дали сакате кафе?",
          accept: ["има кафе. сакате ли кафе?", "има кафе, дали сакате кафе"],
          hint: "има = there is. Then дали сакате...",
          after: "Има on its own means 'there is'; with a subject it means 'has'. The same word, two jobs, and context always tells you which.",
          reviews: ["има-existential", "verb-а-group", "дали-question", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Is there water?**",
          answer: "Дали има вода?",
          accept: ["има ли вода"],
          hint: "дали + има + вода?",
          reviews: ["има-existential", "дали-question", "вода"],
        },
        {
          type: "exercise",
          prompt: "Someone apologizes to you. Say: **No problem!**",
          answer: "Нема проблем",
          hint: "нема + проблем.",
          after: "Нема проблем. Say it with a wave of the hand. You'll get it back from everyone, all day long.",
          reviews: ["има-existential", "проблем"],
        },
        {
          type: "note",
          title: "The third tail: -от",
          body:
            "Телефон and хотел take a third tail, **-от**:\n\nтелефон + **-от** = **телефонот** (the phone)\nхотел + **-от** = **хотелот** (the hotel)\n\nOne form, always. That's it - three tails now: кафе**то**, кола**та**, телефон**от**.",
          bg: "Bulgarian juggles хотелът / хотела depending on the noun's role in the sentence. Macedonian has one masculine article, -от, and never shortens it.",
          speak: ["телефонот", "хотелот", "Телефонот е тука."],
          introduces: ["definite-masc"],
        },
        {
          type: "exercise",
          prompt: "**The phone is here.**",
          answer: "Телефонот е тука",
          accept: ["телефонот е овде"],
          hint: "телефон + -от.",
          reviews: ["definite-masc", "телефон", "сум-present", "тука"],
        },
        {
          type: "exercise",
          prompt: "**The restaurant is here and the hotel is there.**",
          answer: "Ресторанот е тука и хотелот е таму",
          accept: ["ресторанот е овде и хотелот е таму"],
          hint: "ресторан and хотел take the same tail as телефон.",
          after: "Ресторанот, хотелот - you gave both the -от tail without being told to. The endings are choosing themselves.",
          reviews: ["definite-masc", "и-conjunction", "сум-present", "таму"],
        },
        {
          type: "note",
          title: "Three tails",
          body:
            "кафе**то**, кола**та**, телефон**от**. Three ways of saying 'the', and nobody has told you why each word gets which one.\n\nYou're starting to feel it, though. Hold on to that feeling; a later lesson will turn it into a rule you already half know.",
        },
      ],
    },
    {
      id: "m2l3",
      title: "Speaking and understanding",
      subtitle: "зборувам, разбирам, малку, многу, добро",
      items: [
        {
          type: "note",
          title: "I speak: зборувам",
          body:
            "**Зборувам** = I speak. Another а-verb, so every ending you learned on сакам fits it: зборувам, зборуваш, зборува...\n\nLanguages need no 'in' and no 'the': **Зборувам англиски.** - I speak English.",
          he: "Same as Hebrew: אני מדבר אנגלית, no preposition before the language.",
          ru: "Not говорить. Зборувам comes from збор, 'a word' - literally 'I word'.",
          bg: "A different word entirely: Bulgarian говоря, Macedonian зборувам. It's an а-verb here, not an и-verb, so the you-form is зборуваш.",
          speak: ["зборувам", "Зборувам англиски."],
        },
        {
          type: "exercise",
          prompt: "**I speak English.**",
          answer: "Зборувам англиски",
          accept: ["јас зборувам англиски"],
          hint: "зборувам + англиски, nothing in between.",
          reviews: ["verb-а-group", "verb-м-first-person", "англиски", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**I speak Macedonian.** (македонски)",
          answer: "Зборувам македонски",
          accept: ["јас зборувам македонски"],
          hint: "зборувам + македонски.",
          after: "Зборувам македонски. Not yet quite true - but you're getting there faster than you think.",
          reviews: ["verb-а-group", "македонски", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**I don't speak English.**",
          answer: "Не зборувам англиски",
          accept: ["јас не зборувам англиски"],
          hint: "не + зборувам.",
          reviews: ["не-negation", "verb-а-group", "англиски"],
        },
        {
          type: "note",
          title: "You speak: зборуваш",
          body:
            "**Зборуваш** = you speak. The -аш of сакаш, on a longer stem.\n\nOne thing to hear: the stress moves. Зборувам is stressed ZBO-ru-vam, but зборуваме is zbo-RU-va-me - the stress stays three syllables from the end, exactly as the rule from module 1 says.",
          speak: ["зборуваш", "зборуваме", "Дали зборуваш македонски?"],
          reviews: ["stress-antepenult"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you speak Macedonian?**",
          answer: "Дали зборуваш македонски?",
          accept: ["зборуваш ли македонски"],
          hint: "дали + зборуваш + македонски?",
          after: "The single most useful question for a learner, and you built it from parts you already had.",
          reviews: ["дали-question", "verb-а-group", "македонски", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**You don't speak English.**",
          answer: "Не зборуваш англиски",
          accept: ["ти не зборуваш англиски"],
          hint: "не + зборуваш + англиски.",
          reviews: ["не-negation", "verb-а-group", "англиски"],
        },
        {
          type: "exercise",
          prompt: "**You speak Macedonian, right?**",
          answer: "Зборуваш македонски, нели?",
          accept: ["ти зборуваш македонски, нели"],
          hint: "The statement, then the tag: ..., нели?",
          after: "Нели attaches to any sentence, verb or no verb. You learned it with сум; it never changed.",
          reviews: ["нели-tag", "verb-а-group", "македонски"],
        },
        {
          type: "note",
          title: "He speaks, she speaks: зборува",
          body: "**Зборува** = he/she speaks. Drop the -ш, same as сака.",
          speak: ["зборува", "Таа зборува англиски."],
        },
        {
          type: "exercise",
          prompt: "**She speaks English.**",
          answer: "Таа зборува англиски",
          accept: ["зборува англиски"],
          hint: "She-form: зборува.",
          reviews: ["pronoun-subject", "verb-а-group", "англиски"],
        },
        {
          type: "exercise",
          prompt: "**He speaks Macedonian.**",
          answer: "Тој зборува македонски",
          accept: ["зборува македонски"],
          hint: "He-form is the same as she-form: зборува.",
          reviews: ["pronoun-subject", "verb-а-group", "македонски"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Does she speak English?**",
          answer: "Дали таа зборува англиски?",
          accept: ["дали зборува англиски", "зборува ли англиски", "таа зборува ли англиски"],
          hint: "дали in front of 'she speaks English'.",
          reviews: ["дали-question", "pronoun-subject", "verb-а-group"],
        },
        {
          type: "note",
          title: "The most useful sentence",
          body:
            "**Разбирам** = I understand. An а-verb, so you already own every form of it.\n\nStress: ra-ZBI-ram, three from the end, as always.\n\n**Не разбирам** may be the most useful sentence in this whole course. Say it without shame.",
          ru: "Russian разбираться means to figure something out; here разбирам is plain 'I understand'.",
          speak: ["Разбирам.", "Не разбирам."],
        },
        {
          type: "exercise",
          prompt: "**I don't understand.**",
          answer: "Не разбирам",
          accept: ["јас не разбирам"],
          hint: "не + разбирам.",
          after: "Не разбирам. Two words that will rescue you a hundred times.",
          reviews: ["не-negation", "verb-а-group", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**I understand Macedonian.**",
          answer: "Разбирам македонски",
          accept: ["јас разбирам македонски"],
          hint: "разбирам + македонски, just like зборувам македонски.",
          reviews: ["verb-а-group", "македонски", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you understand?**",
          answer: "Дали разбираш?",
          accept: ["разбираш ли"],
          hint: "The -аш of сакаш and имаш.",
          reviews: ["дали-question", "verb-а-group", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**You don't understand.**",
          answer: "Не разбираш",
          accept: ["ти не разбираш"],
          hint: "не + разбираш.",
          reviews: ["не-negation", "verb-а-group"],
        },
        {
          type: "exercise",
          prompt: "**She understands English.**",
          answer: "Таа разбира англиски",
          accept: ["разбира англиски"],
          hint: "She-form: разбира, like сака and зборува.",
          reviews: ["pronoun-subject", "verb-а-group", "англиски"],
        },
        {
          type: "exercise",
          prompt: "**They don't understand.**",
          answer: "Тие не разбираат",
          accept: ["не разбираат"],
          hint: "They-form: two а's, like сакаат.",
          after: "Разбираат. You reached for the double а on your own. That is the they-form settling in.",
          reviews: ["pronoun-subject", "не-negation", "verb-а-group"],
        },
        {
          type: "exercise",
          prompt: "**We understand Macedonian.**",
          answer: "Разбираме македонски",
          accept: ["ние разбираме македонски"],
          hint: "-ме for we.",
          reviews: ["verb-а-group", "македонски", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you all understand?**",
          answer: "Дали разбирате?",
          accept: ["разбирате ли", "дали вие разбирате"],
          hint: "-те for you all.",
          after: "Разбирате? A teacher's favourite question, and you can now ask it yourself.",
          reviews: ["дали-question", "verb-а-group", "pronoun-drop"],
        },
        {
          type: "note",
          title: "A little: малку",
          body:
            "**Малку** = a little. The honest sentence of every language learner:\n\n**Зборувам малку македонски.** - I speak a little Macedonian.",
          bg: "Bulgarian малко ends in -о; the Macedonian adverb is малку, with -у. Same for многу.",
          speak: ["малку", "Зборувам малку македонски."],
        },
        {
          type: "exercise",
          prompt: "**I speak a little Macedonian.**",
          answer: "Зборувам малку македонски",
          accept: ["јас зборувам малку македонски", "малку зборувам македонски"],
          hint: "зборувам + малку + македонски.",
          after: "This one sentence will earn you enormous goodwill anywhere from Skopje to Ohrid.",
          reviews: ["verb-а-group", "малку", "македонски", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**I understand a little.**",
          answer: "Разбирам малку",
          accept: ["малку разбирам"],
          hint: "разбирам + малку.",
          reviews: ["verb-а-group", "малку"],
        },
        {
          type: "exercise",
          prompt: "**She understands a little English.**",
          answer: "Таа разбира малку англиски",
          accept: ["разбира малку англиски"],
          hint: "разбира (she-form) + малку + англиски.",
          reviews: ["pronoun-subject", "verb-а-group", "малку", "англиски"],
        },
        {
          type: "note",
          title: "A lot, very: многу",
          body:
            "**Многу** = a lot. It also means 'very' - one word for both:\n\n**Зборувам многу.** - I speak a lot.\n**Многу малку.** - Very little.",
          he: "Hebrew keeps הרבה (a lot) and מאוד (very) apart. Многу is both.",
          ru: "Russian много, with -у on the end and stress on the first syllable: MNO-gu.",
          speak: ["многу", "Зборувам многу.", "Многу малку."],
        },
        {
          type: "exercise",
          prompt: "**She speaks a lot.**",
          answer: "Таа зборува многу",
          accept: ["зборува многу", "таа многу зборува"],
          hint: "зборува (she-form) + многу.",
          reviews: ["pronoun-subject", "verb-а-group", "многу"],
        },
        {
          type: "exercise",
          prompt: "**I understand very little.**",
          answer: "Разбирам многу малку",
          accept: ["многу малку разбирам", "јас разбирам многу малку"],
          hint: "разбирам + многу малку.",
          after: "Многу малку. The 'very' meaning of многу, doing its job in front of another adverb.",
          reviews: ["verb-а-group", "многу", "малку"],
        },
        {
          type: "note",
          title: "Well: добро",
          body:
            "**Добро** = well.\n\n**Зборувам добро.** - I speak well.\n**Многу добро.** - Very well.",
          he: "Like טוב, which is both 'good' and 'well', добро doubles as both. For now, use it for 'well'.",
          bg: "Bulgarian добре; Macedonian добро. The Bulgarian form does not exist here.",
          speak: ["добро", "Зборувам добро.", "Многу добро."],
        },
        {
          type: "exercise",
          prompt: "**He speaks well.**",
          answer: "Тој зборува добро",
          accept: ["зборува добро", "тој добро зборува"],
          hint: "зборува (he-form) + добро.",
          reviews: ["pronoun-subject", "verb-а-group", "добро"],
        },
        {
          type: "exercise",
          prompt: "**She understands very well.**",
          answer: "Таа разбира многу добро",
          accept: ["разбира многу добро", "таа многу добро разбира"],
          hint: "разбира + многу + добро.",
          reviews: ["pronoun-subject", "verb-а-group", "многу", "добро"],
        },
        {
          type: "exercise",
          prompt: "Compliment someone: **You speak Macedonian very well!**",
          answer: "Многу добро зборуваш македонски",
          accept: ["зборуваш многу добро македонски", "зборуваш македонски многу добро", "ти зборуваш македонски многу добро"],
          hint: "многу добро can go first or after the verb.",
          after: "Многу добро зборуваш македонски. Say this to a Macedonian and watch them light up. Say it to yourself in a few weeks.",
          reviews: ["verb-а-group", "многу", "добро", "македонски"],
        },
        {
          type: "exercise",
          prompt: "**They speak a little English.**",
          answer: "Тие зборуваат малку англиски",
          accept: ["зборуваат малку англиски"],
          hint: "They-form: зборува + ат.",
          reviews: ["pronoun-subject", "verb-а-group", "малку", "англиски"],
        },
        {
          type: "exercise",
          prompt: "**I understand well, I speak a little.**",
          answer: "Разбирам добро, зборувам малку",
          accept: ["добро разбирам, малку зборувам", "јас разбирам добро, зборувам малку"],
          hint: "Two short sentences, a comma between them.",
          after: "Разбирам добро, зборувам малку. That is most learners' honest state - and now you can say it in Macedonian.",
          reviews: ["verb-а-group", "добро", "малку", "pronoun-drop"],
        },
        {
          type: "note",
          body:
            "You can now say who speaks and who understands, and how well. Малку, многу, добро - three words that dress up any verb you know.\n\nNext: two verbs that don't quite follow сакам, and a word to connect your thoughts.",
        },
      ],
    },
    {
      id: "m2l4",
      title: "Learning and working",
      subtitle: "учам, работам, но, денес",
      items: [
        {
          type: "note",
          title: "I learn: учам",
          body:
            "**Учам** = I learn, I study. The I-form ends in -м, as always.\n\n**Учам македонски.** - I'm learning Macedonian.",
          ru: "Russian учу / учусь; Macedonian учам covers both 'learn' and 'study'.",
          bg: "Bulgarian уча, Macedonian учам - the 1sg -а becomes -м.",
          speak: ["учам", "Учам македонски."],
        },
        {
          type: "exercise",
          prompt: "**I'm learning Macedonian.**",
          answer: "Учам македонски",
          accept: ["јас учам македонски"],
          hint: "The present tense covers 'I learn' and 'I'm learning' - one form, both jobs.",
          reviews: ["verb-м-first-person", "македонски", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**I'm learning Macedonian and I understand a little.**",
          answer: "Учам македонски и разбирам малку",
          accept: ["јас учам македонски и разбирам малку", "учам македонски и малку разбирам"],
          hint: "учам... и разбирам малку.",
          after: "Two I-forms, both ending in -м. The rule holds for every verb you meet.",
          reviews: ["verb-м-first-person", "и-conjunction", "малку", "македонски"],
        },
        {
          type: "note",
          title: "The и-group: учиш, учи",
          body:
            "Here is where учам stops copying сакам. In the you-form the vowel before -ш is **и**, not а: **учиш** = you learn. Drop the -ш and you have he/she: **учи**.\n\nThat's the whole difference. Verbs with -иш are the *и-group*. The endings still say who; only the vowel changed.",
          he: "Think of Hebrew binyanim: a different vowel pattern, the same personal endings.",
          speak: ["учиш", "учи", "Дали учиш македонски?"],
          introduces: ["verb-и-group"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Are you studying Macedonian?**",
          answer: "Дали учиш македонски?",
          accept: ["учиш ли македонски"],
          hint: "учиш - the -ш with an и in front of it.",
          after: "Учиш. You swapped the vowel and kept the -ш. That is all the и-group ever asks of you.",
          reviews: ["verb-и-group", "дали-question", "македонски", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**She is studying English.**",
          answer: "Таа учи англиски",
          accept: ["учи англиски"],
          hint: "She-form: учи.",
          reviews: ["verb-и-group", "pronoun-subject", "англиски"],
        },
        {
          type: "note",
          title: "But: но",
          body:
            "**Но** = but. A comma before it:\n\n**Разбирам, но не зборувам.** - I understand, but I don't speak.",
          ru: "Same но as Russian.",
          speak: ["но", "Разбирам, но не зборувам."],
          introduces: ["но-but"],
        },
        {
          type: "exercise",
          prompt: "**I understand, but I don't speak.**",
          answer: "Разбирам, но не зборувам",
          accept: ["разбирам, ама не зборувам"],
          hint: "..., но не зборувам.",
          after: "In everyday speech you'll hear **ама** just as often as но - same meaning, more relaxed. Either is fine.",
          reviews: ["но-but", "не-negation", "verb-а-group", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**She studies, but she doesn't understand.**",
          answer: "Таа учи, но не разбира",
          accept: ["учи, но не разбира", "таа учи, ама не разбира"],
          hint: "учи (she-form), но не разбира (she-form of разбирам).",
          reviews: ["но-but", "verb-и-group", "verb-а-group", "pronoun-subject"],
        },
        {
          type: "exercise",
          prompt: "**She wants coffee, but there is no coffee.**",
          answer: "Таа сака кафе, но нема кафе",
          accept: ["сака кафе, но нема кафе", "таа сака кафе, ама нема кафе"],
          hint: "сака (she wants), но, нема (there isn't).",
          after: "A whole little story: a wish, a but, and a bare нема. You wove three lessons together without noticing.",
          reviews: ["но-but", "има-existential", "verb-а-group", "pronoun-subject"],
        },
        {
          type: "note",
          title: "I work: работам",
          body:
            "**Работам** = I work. Also и-group: **работиш** (you work), **работи** (he/she works).\n\n**Работам тука.** - I work here.",
          ru: "Russian работаю; Macedonian работам, and then the и-forms: работиш, работи.",
          bg: "Bulgarian работя → работам. The other forms match: работиш, работи.",
          speak: ["работам", "работиш", "работи", "Работам тука."],
        },
        {
          type: "exercise",
          prompt: "**I work, but I don't speak Macedonian.**",
          answer: "Работам, но не зборувам македонски",
          accept: ["јас работам, но не зборувам македонски", "работам, ама не зборувам македонски"],
          hint: "работам, но не зборувам...",
          reviews: ["но-but", "verb-м-first-person", "не-negation", "македонски"],
        },
        {
          type: "note",
          title: "We and you all: -име, -ите",
          body:
            "The и-group keeps its и right through: **учиме** (we learn), **учите** (you all learn); **работиме**, **работите**. Take сакаме and сакате, swap the а for и, and you're done.",
          speak: ["учиме", "учите", "работиме", "работите"],
        },
        {
          type: "exercise",
          prompt: "**We work here.**",
          answer: "Работиме тука",
          accept: ["ние работиме тука", "работиме овде"],
          hint: "сакаме → работиме: same -ме, и instead of а.",
          reviews: ["verb-и-group", "тука", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Are you all studying Macedonian?**",
          answer: "Дали учите македонски?",
          accept: ["учите ли македонски", "дали вие учите македонски"],
          hint: "сакате → учите.",
          after: "Учите. The -те still means 'you all'; only the vowel in front of it belongs to the group.",
          reviews: ["verb-и-group", "дали-question", "македонски"],
        },
        {
          type: "note",
          title: "They: учат, работат",
          body:
            "The they-form of the и-group is **-ат** with a single а: **учат**, **работат**. The а-group doubled it (сакаат, разбираат) because its stem already ended in а. The и-group has nothing to double.",
          bg: "Bulgarian учат, работят; Macedonian учат, работат - no -ят, ever.",
          speak: ["учат", "работат", "Тие работат тука."],
        },
        {
          type: "exercise",
          prompt: "**They work here.**",
          answer: "Тие работат тука",
          accept: ["работат тука", "тие работат овде"],
          hint: "One а: работат.",
          reviews: ["verb-и-group", "pronoun-subject", "тука"],
        },
        {
          type: "exercise",
          prompt: "**They study English, but they don't speak well.**",
          answer: "Тие учат англиски, но не зборуваат добро",
          accept: ["учат англиски, но не зборуваат добро", "тие учат англиски, ама не зборуваат добро"],
          hint: "учат (one а) versus зборуваат (two).",
          after: "Учат, зборуваат. Both are 'they'; the double а marks the а-group, the single а the и-group. You just told them apart in one sentence.",
          reviews: ["verb-и-group", "verb-а-group", "но-but", "добро"],
        },
        {
          type: "note",
          title: "Today: денес",
          body: "**Денес** = today.\n\n**Работам денес.** - I'm working today.",
          he: "Like היום, which is 'the day', денес is built on ден, 'day'.",
          ru: "Not сегодня. Macedonian денес keeps the word for 'day' - ден - in plain sight.",
          bg: "Bulgarian днес, Macedonian денес - an extra е.",
          speak: ["денес", "Работам денес."],
        },
        {
          type: "exercise",
          prompt: "**He is not working today.**",
          answer: "Тој не работи денес",
          accept: ["не работи денес", "тој денес не работи"],
          hint: "не + работи + денес.",
          reviews: ["verb-и-group", "не-negation", "pronoun-subject", "денес"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Are you working today?**",
          answer: "Дали работиш денес?",
          accept: ["работиш ли денес", "дали денес работиш"],
          hint: "дали + работиш + денес?",
          reviews: ["verb-и-group", "дали-question", "денес"],
        },
        {
          type: "note",
          title: "Two groups",
          body:
            "- **а-group**: сакам, имам, зборувам, разбирам - сакам, сакаш, сака, сакаме, сакате, сакаат\n- **и-group**: учам, работам - учам, учиш, учи, учиме, учите, учат\n\nThe I-form is -м in both. The endings are the same in both. The only thing that changes is the vowel in the middle, and whether the they-form doubles it.",
        },
      ],
    },
    {
      id: "m2l5",
      title: "The missing 'to'",
      subtitle: "сакам да зборувам",
      items: [
        {
          type: "note",
          title: "There is no 'to'",
          body:
            "Macedonian has no word for 'to' before a verb. Where English says 'I want **to speak**', Macedonian says 'I want **that I-speak**':\n\n**Сакам да зборувам.**\n\n**Да** + a conjugated verb replaces every English 'to ___'. Both verbs agree with the subject - watch them rhyme:\n\n- Сака**м** да зборува**м** (I want to speak)\n- Сака**ш** да зборува**ш** (you want to speak)\n- Сака да зборува (she wants to speak)",
          he: "Hebrew has an infinitive (לדבר), but it also knows the shape 'I want that you speak' - אני רוצה שתדבר. Macedonian uses that ש-shape for everything, even when the subject stays the same.",
          ru: "Russian хочу говорить keeps its infinitive. Macedonian, like the rest of the Balkans, threw it away: да + a conjugated verb, always. And yes, да also means 'yes' here - context keeps them apart.",
          bg: "Identical to Bulgarian искам да говоря; only the verbs are different: сакам да зборувам.",
          speak: ["Сакам да зборувам.", "Сакаш да зборуваш.", "Таа сака да зборува."],
          introduces: ["да-subjunctive"],
        },
        {
          type: "exercise",
          prompt: "**I want to speak Macedonian.**",
          answer: "Сакам да зборувам македонски",
          accept: ["јас сакам да зборувам македонски"],
          hint: "сакам + да + зборувам.",
          after: "Both verbs in the I-form: сакам, зборувам. They have to match.",
          reviews: ["да-subjunctive", "verb-а-group", "македонски", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you want to speak English?**",
          answer: "Дали сакаш да зборуваш англиски?",
          accept: ["сакаш ли да зборуваш англиски"],
          hint: "дали сакаш + да зборуваш...",
          after: "Сакаш да зборуваш - two -ш endings. When the subject is 'you', every verb in the chain is 'you'.",
          reviews: ["да-subjunctive", "дали-question", "verb-а-group", "англиски"],
        },
        {
          type: "exercise",
          prompt: "**She wants to learn Macedonian.**",
          answer: "Таа сака да учи македонски",
          accept: ["сака да учи македонски"],
          hint: "Both verbs in the she-form: сака, учи.",
          after: "Сака да учи. An а-verb and an и-verb, holding hands across да.",
          reviews: ["да-subjunctive", "verb-а-group", "verb-и-group", "pronoun-subject"],
        },
        {
          type: "choice",
          prompt: "**Сакам да зборувам** literally means...",
          options: ["I want that I-speak", "I want to speaking", "I want the speech"],
          correct: 0,
          after: "Literally 'I want that I-speak'. The second verb is always conjugated, never frozen.",
          reviews: ["да-subjunctive"],
        },
        {
          type: "note",
          title: "One verb, two feelings",
          body:
            "**Сакам** doesn't only mean 'want'. It also means 'love'. There is no second verb:\n\n**Сакам кафе.** - I want coffee. Or: I love coffee. Tone and context decide.\n**Многу сакам кафе.** - I love coffee a lot. Now there's no doubt.",
          he: "Hebrew keeps רוצה and אוהב apart; Macedonian folds both into сакам.",
          bg: "Bulgarian keeps искам (want) and обичам (love) apart. Macedonian has one verb for both, сакам. There is no обичам here.",
          speak: ["Сакам кафе.", "Многу сакам кафе."],
        },
        {
          type: "exercise",
          prompt: "**I really love coffee.**",
          answer: "Многу сакам кафе",
          accept: ["јас многу сакам кафе"],
          hint: "многу + сакам + кафе.",
          after: "Многу сакам кафе. The многу in front is what tips it from 'want' to 'love'.",
          reviews: ["verb-а-group", "многу", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**She loves wine.**",
          answer: "Таа сака вино",
          accept: ["сака вино", "таа многу сака вино"],
          hint: "The same сака you'd use for 'she wants'.",
          reviews: ["verb-а-group", "pronoun-subject", "вино"],
        },
        {
          type: "note",
          title: "I travel: патувам",
          body:
            "**Патувам** = I travel. An а-verb. And now the two ideas meet:\n\n**Сакам да патувам.** - I love to travel.",
          ru: "Russian путь, 'a road', hides inside патувам - ъ→а, and the verb means 'to be on the road'.",
          bg: "Bulgarian пътувам → патувам: ъ becomes а.",
          speak: ["патувам", "Сакам да патувам."],
        },
        {
          type: "exercise",
          prompt: "**I love to travel.**",
          answer: "Сакам да патувам",
          accept: ["јас сакам да патувам", "многу сакам да патувам"],
          hint: "сакам + да + патувам.",
          reviews: ["да-subjunctive", "verb-а-group", "патувам", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**She loves to travel.**",
          answer: "Таа сака да патува",
          accept: ["сака да патува"],
          hint: "She-forms: сака, патува.",
          after: "Сака да патува. Both verbs dropped their -ш at the same time. That is the rhyme да-sentences always have.",
          reviews: ["да-subjunctive", "verb-а-group", "патувам", "pronoun-subject"],
        },
        {
          type: "note",
          title: "I go: одам",
          body:
            "**Одам** = I go. It's и-group: **одиш**, **оди**, одиме, одите, одат.\n\n**Сакам да одам таму.** - I want to go there.",
          ru: "Russian ходить with the х fallen off: одам, одиш, оди.",
          bg: "Bulgarian отивам / ходя; Macedonian одам (и-group: одиш, оди).",
          speak: ["одам", "одиш", "Сакам да одам таму."],
        },
        {
          type: "exercise",
          prompt: "**I want to go there.**",
          answer: "Сакам да одам таму",
          accept: ["јас сакам да одам таму"],
          hint: "сакам + да + одам + таму.",
          reviews: ["да-subjunctive", "одам", "verb-и-group", "таму"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you want to go there?**",
          answer: "Дали сакаш да одиш таму?",
          accept: ["сакаш ли да одиш таму"],
          hint: "сакаш (а-group) + да + одиш (и-group).",
          after: "Сакаш да одиш - the а-group -аш and the и-group -иш, agreeing with the same 'you'.",
          reviews: ["да-subjunctive", "дали-question", "verb-и-group", "одам"],
        },
        {
          type: "exercise",
          prompt: "**They want to work today.**",
          answer: "Тие сакаат да работат денес",
          accept: ["сакаат да работат денес"],
          hint: "They-forms: сакаат (two а's), работат (one).",
          reviews: ["да-subjunctive", "verb-а-group", "verb-и-group", "денес"],
        },
        {
          type: "exercise",
          prompt: "**We want to learn Macedonian.**",
          answer: "Сакаме да учиме македонски",
          accept: ["ние сакаме да учиме македонски"],
          hint: "сакаме (we want) + да + учиме (we learn).",
          reviews: ["да-subjunctive", "verb-а-group", "verb-и-group", "македонски"],
        },
        {
          type: "exercise",
          prompt: "**I want to understand, but I don't understand.**",
          answer: "Сакам да разбирам, но не разбирам",
          accept: ["сакам да разбирам, ама не разбирам", "јас сакам да разбирам, но не разбирам"],
          hint: "сакам да разбирам, но...",
          after: "Every а-verb and every и-verb works the same way after да. You have the whole mechanism now.",
          reviews: ["да-subjunctive", "но-but", "не-negation", "verb-а-group"],
        },
        {
          type: "exercise",
          prompt: "You've finished. Ask for the bill, the way a local would: **The bill, please.**",
          answer: "Сметката, Ве молам",
          hint: "сметка + -та, then Ве молам.",
          after: "Сметката, Ве молам. The -та you learned on колата, on the word you needed it for most.",
          reviews: ["definite-fem", "сметка", "ве молам"],
        },
        {
          type: "note",
          title: "Да is the glue",
          body:
            "From now on, whenever English hands you a 'to ___', your brain should produce **да** + the verb, conjugated to match the subject. Сакам **да** зборувам. Сакам **да** патувам.\n\nTwo verb groups, three article tails, a verb that wants and loves at once, and the да-construction. You're thinking in Macedonian.",
        },
      ],
    },
  ],
};
