import type { Module } from "./types";

export const module1: Module = {
  id: "m1",
  title: "2. You already speak some Macedonian",
  blurb:
    "Steal hundreds of words you already own, get the stress rule as a gift, and build your first real sentences with 'to be'.",
  lessons: [
    {
      id: "m1l1",
      title: "Instant Macedonian",
      subtitle: "International words and where the stress goes",
      items: [
        {
          type: "note",
          title: "How this course works",
          body:
            "This course is about learning to think in Macedonian. Not memorizing phrases - thinking. Every lesson shows you how Macedonian works, then immediately asks you to build something with it. If you get something wrong, that's the method working: the correction is what makes it stick.\n\nYou already know how to think about language. You know what it means for a verb to change its form, for a word to have gender, for a sentence to have structure. That skill transfers directly.\n\nYou've been typing with the Latin-to-Cyrillic keyboard since Module 0 - same thing from here on. Tap the speaker on any Macedonian phrase to hear it.",
          he: "In Hebrew, verbs carry their subject (הלכתי vs הלכת), words have gender, and roots generate families. Macedonian works differently, but you already know these concepts from Hebrew.",
        },
        {
          type: "note",
          title: "You already own hundreds of Macedonian words",
          body:
            "English words ending in **-tion** usually exist in Macedonian ending in **-ција** (-tsiya):\n\n- information → **информација**\n- situation → **ситуација**\n- organization → **организација**\n\nSay the ending as *tsi-ya* - that ј is the y of 'yes'. One rebel to remember: 'station' is **станица**, not станција. Every other -tion word you try will usually land.",
          speak: ["информација", "ситуација", "организација"],
          introduces: ["cognate-ција"],
          ru: "Same words as in Russian - the only difference is the ending: Russian spells the final ya-sound with one letter, Macedonian spells it out as -ија.",
          bg: "Bulgarian -ция is written -ција here (the ј is spelled out), and Bulgarian станция is станица - the one -tion word that went its own way.",
        },
        {
          type: "exercise",
          prompt: "Turn **constitution** into Macedonian.",
          answer: "конституција",
          hint: "-tion becomes -ција. Start from 'constitu-'. Type the ending as cija.",
          after: "**Конституција.** You didn't learn this word - you converted it. The same thing works for hundreds of other words.",
          reviews: ["cyrillic-typing", "cognate-ција", "ј-letter"],
        },
        {
          type: "exercise",
          prompt: "And **revolution**?",
          answer: "револуција",
          hint: "revolu- + -ција. The English 'v' is в.",
          reviews: ["cyrillic-typing", "cognate-ција"],
        },
        {
          type: "exercise",
          prompt: "One more: **tradition**.",
          answer: "традиција",
          hint: "tradi- + -ција.",
          after: "Three words converted, zero memorized. Keep the -ција trick in your pocket - it will keep paying out.",
          reviews: ["cyrillic-typing", "cognate-ција"],
        },
        {
          type: "note",
          title: "Stress: a rule, not a memory item",
          body:
            "Here is a gift. In English you have to *learn* where the stress goes in every word (PHO-to, pho-TO-graph-er). Macedonian has a rule: the stress falls on the **third syllable from the end**. In two-syllable words, that means the first.\n\n- ин-фор-**МА**-ци-ја\n- ор-га-ни-**ЗА**-ци-ја\n- Ма-ке-**ДО**-ни-ја\n- **ХО**-тел, **ДОК**-тор, **ТУ**-рист\n\nTap the chips and listen for it. One more gift: every vowel is pronounced exactly as written - there is no mumbling of unstressed syllables. What you see is what you say.",
          speak: ["информација", "организација", "Македонија", "хотел", "доктор", "турист"],
          introduces: ["stress-antepenult"],
          ru: "Russian stress is unpredictable and swallows unstressed vowels (молоко = 'malako'). Macedonian stress is fixed, and every vowel keeps its full sound - no reduction at all.",
          bg: "Bulgarian stress can fall anywhere and unstressed vowels get reduced; Macedonian stress is fixed three syllables from the end, and nothing is reduced. So Bulgarian кафЕ, хотЕл become КАфе, ХОтел.",
        },
        {
          type: "choice",
          prompt: "Where is the stress in **Македонија**? (Count three syllables back from the end.)",
          options: ["Ма-ке-ДО-ни-ја", "Ма-КЕ-до-ни-ја", "Ма-ке-до-НИ-ја"],
          correct: 0,
          after: "Ма-ке-ДО-ни-ја. Third from the end - the rule did the work.",
          speak: "Македонија",
          reviews: ["stress-antepenult"],
        },
        {
          type: "choice",
          prompt: "**Хотел** has only two syllables. Where does the stress go?",
          options: ["ХО-тел", "хо-ТЕЛ"],
          correct: 0,
          after: "ХО-тел, not the English ho-TEL. Two syllables: stress the first.",
          speak: "хотел",
          reviews: ["stress-antepenult"],
        },
        {
          type: "note",
          title: "People words: турист and журналист",
          body:
            "Professions and 'people' words carry over too. Let's start with two:\n\n- tourist → **турист**\n- journalist → **журналист**\n\nNotice ж in журналист - it's the *s* in 'plea**s**ure' (type **zh**). And the stress? ТУ-рист, ЖУР-на-лист - the rule again.",
          speak: ["турист", "журналист"],
          introduces: ["cognate-ист"],
        },
        {
          type: "exercise",
          prompt: "Write **tourist** in Macedonian.",
          answer: "турист",
          hint: "Same word, new letters: т-у-р-и-с-т.",
          reviews: ["cyrillic-typing", "cognate-ист"],
        },
        {
          type: "exercise",
          prompt: "Write **journalist**.",
          answer: "журналист",
          hint: "The first sound is ж - type zh.",
          reviews: ["cyrillic-typing", "cognate-ист"],
        },
        {
          type: "exercise",
          prompt: "Guess one: **artist**.",
          answer: "артист",
          hint: "art- + -ист.",
          after: "**Артист.** Any -ist word is fair game: оптимист, турист, артист.",
          reviews: ["cyrillic-typing", "cognate-ист"],
        },
        {
          type: "note",
          title: "More people: доктор and професор",
          body:
            "Two more that come straight across:\n\n- doctor → **доктор**\n- professor → **професор** (one 's' in Macedonian)\n\nEnglish -or is Macedonian **-ор**.",
          speak: ["доктор", "професор"],
          introduces: ["cognate-ор"],
        },
        {
          type: "exercise",
          prompt: "Write **doctor**.",
          answer: "доктор",
          hint: "д-о-к-т-о-р. Remember р is R.",
          reviews: ["cyrillic-typing", "cognate-ор"],
        },
        {
          type: "exercise",
          prompt: "Write **professor**.",
          answer: "професор",
          hint: "Only one с in Macedonian: професор.",
          reviews: ["cyrillic-typing", "cognate-ор"],
        },
        {
          type: "exercise",
          prompt: "And **director**?",
          answer: "директор",
          hint: "direct- + -ор.",
          after: "ДИ-рек-тор. Third syllable from the end, as always.",
          reviews: ["cyrillic-typing", "cognate-ор", "stress-antepenult"],
        },
        {
          type: "note",
          title: "One more: студент",
          body:
            "And one more people word:\n\n- student → **студент**\n\nSTU-dent. Two syllables, first one stressed.",
          speak: ["студент"],
        },
        {
          type: "exercise",
          prompt: "Write **student**.",
          answer: "студент",
          hint: "с-т-у-д-е-н-т.",
          after: "Five profession words banked: турист, журналист, доктор, професор, студент.",
          reviews: ["cyrillic-typing"],
        },
        {
          type: "note",
          title: "Places: ресторан and хотел",
          body:
            "More words you already know:\n\n- restaurant → **ресторан**\n- hotel → **хотел**\n\nWatch the end of ресторан: it stops at н. No t.",
          speak: ["ресторан", "хотел"],
          bg: "Bulgarian ресторант keeps the т; Macedonian ресторан drops it.",
        },
        {
          type: "exercise",
          prompt: "Write **restaurant**.",
          answer: "ресторан",
          hint: "р=r, not 'п'. Think 'restoran' - and stop at н.",
          after: "Ресторан - no т at the end. And the stress? Ре-сто-РАН... no: РЕС-то-ран, three from the end.",
          reviews: ["cyrillic-typing", "stress-antepenult"],
        },
        {
          type: "exercise",
          prompt: "Write **hotel**.",
          answer: "хотел",
          hint: "х-о-т-е-л. The х is that soft throat sound.",
          reviews: ["cyrillic-typing"],
        },
        {
          type: "note",
          title: "Things: телефон and банка",
          body:
            "Two more everyday words:\n\n- telephone → **телефон**\n- bank → **банка**",
          speak: ["телефон", "банка"],
        },
        {
          type: "exercise",
          prompt: "Write **telephone**.",
          answer: "телефон",
          hint: "т-е-л-е-ф-о-н.",
          after: "Те-ЛЕ-фон. This is one of the few recent loanwords that keeps its foreign stress - listen to the chip and don't worry about it.",
          reviews: ["cyrillic-typing"],
        },
        {
          type: "exercise",
          prompt: "Write **bank**.",
          answer: "банка",
          hint: "банка - note the -а ending.",
          after: "The -а at the end? That's a grammatical ending (feminine gender). You'll learn more about that soon.",
          reviews: ["cyrillic-typing"],
        },
        {
          type: "note",
          title: "Food: кафе and чај",
          body:
            "A couple of freebies:\n\n- coffee / café → **кафе**\n- tea → **чај** (same word as English 'chai')\n\nЧај ends in ј - the y of 'yes'. Say it 'chai', in one syllable.",
          speak: ["кафе", "чај"],
          he: "**Чај** and תה both came from Chinese - via different trade routes.",
          bg: "Bulgarian чай ends in й; Macedonian writes the same sound with ј: чај. Every Bulgarian й is a Macedonian ј.",
        },
        {
          type: "exercise",
          prompt: "Write **coffee** (or café).",
          answer: "кафе",
          hint: "к-а-ф-е.",
          after: "КА-фе - stress on the first syllable. Not the French ca-FE.",
          reviews: ["cyrillic-typing", "stress-antepenult"],
        },
        {
          type: "exercise",
          prompt: "Write **tea** - think 'chai'.",
          answer: "чај",
          hint: "ч (ch) + а + ј (type j).",
          reviews: ["cyrillic-typing", "ј-letter"],
        },
        {
          type: "note",
          title: "More freebies: проблем and станица",
          body:
            "Two more:\n\n- problem → **проблем**\n- station → **станица** (bus or train)\n\nПро-БЛЕМ? No - PRO-blem, two syllables, first one stressed. And станица is the rebel from earlier: the -tion word that didn't take -ција.",
          speak: ["проблем", "станица"],
        },
        {
          type: "exercise",
          prompt: "Write **problem**.",
          answer: "проблем",
          hint: "про- + -блем.",
          reviews: ["cyrillic-typing"],
        },
        {
          type: "exercise",
          prompt: "Write **station**.",
          answer: "станица",
          hint: "стани- + -ца. No ј in this one.",
          after: "Станица. СТА-ни-ца, third from the end. The one -tion word that ignores the -ција pattern - now it's yours.",
          reviews: ["cyrillic-typing", "stress-antepenult"],
        },
        {
          type: "note",
          title: "And: и",
          body:
            "One letter, and it's a whole word: **и** = and.\n\n**кафе и чај** - *coffee and tea*\n**хотел и ресторан** - *a hotel and a restaurant*\n\nNo word for 'a', by the way. Macedonian just says 'hotel and restaurant'.",
          speak: ["кафе и чај", "хотел и ресторан"],
          introduces: ["и-conjunction"],
          he: "Hebrew glues 'and' onto the next word (וקפה). Macedonian и stands alone, like English 'and'.",
          ru: "Same и as Russian.",
        },
        {
          type: "exercise",
          prompt: "How would you say: **coffee and tea**?",
          answer: "кафе и чај",
          hint: "кафе + и + чај.",
          reviews: ["и-conjunction", "cyrillic-typing"],
        },
        {
          type: "exercise",
          prompt: "**A doctor and a student.**",
          answer: "доктор и студент",
          hint: "No word for 'a'. Just доктор и студент.",
          after: "Two nouns, one и, no articles. Your first Macedonian phrase built from parts.",
          reviews: ["и-conjunction", "cognate-ор"],
        },
        {
          type: "exercise",
          prompt: "**A tourist and a journalist.**",
          answer: "турист и журналист",
          hint: "турист + и + журналист (zh for ж).",
          reviews: ["и-conjunction", "cognate-ист"],
        },
        {
          type: "note",
          title: "What just happened",
          body:
            "In one lesson you collected a few hundred words (every -tion, -ist, -or word you know is now suspect - try it in Macedonian first, you'll usually be right), and you got the stress rule for free: third syllable from the end, first in two-syllable words.\n\nNext: your first real sentences.",
        },
      ],
    },
    {
      id: "m1l2",
      title: "I am: јас сум",
      subtitle: "Your first verb form",
      items: [
        {
          type: "note",
          title: "Your first verb: 'to be'",
          body:
            "Macedonian, like English, insists on the little verb 'to be':\n\n**Јас сум студент.** - *I am a student.*\n\n- **јас** = I (say 'yas')\n- **сум** = am\n\nPronoun first, then сум, then what you are. That's the natural order whenever the pronoun is there. And still no word for 'a': just 'I am student'.",
          speak: ["Јас сум студент."],
          introduces: ["сум-present", "pronoun-subject", "сум-position"],
          he: "Hebrew drops 'to be' in the present (אני סטודנט). Macedonian kept it: јас **сум** студент. You'll need to add it back.",
          ru: "Russian drops 'to be' in the present too (just 'I student'). Macedonian kept it alive: јас **сум** студент. This is the first big habit to change.",
          bg: "Bulgarian аз съм is Macedonian јас сум: the ъ of съм becomes у, and 'I' grows a ј at the front.",
        },
        {
          type: "exercise",
          prompt: "How would you say: **I am a tourist**?",
          answer: "Јас сум турист",
          accept: ["јас сум туристка"],
          hint: "јас сум + the word you learned for 'tourist'.",
          after: "**Јас сум турист.** A woman would usually say **туристка** - but more on that soon.",
          reviews: ["pronoun-subject", "сум-present"],
        },
        {
          type: "exercise",
          prompt: "**I am a journalist.**",
          answer: "Јас сум журналист",
          accept: ["јас сум журналистка"],
          hint: "Same pattern: јас сум + журналист (remember ж = zh).",
          after: "You matched 'I' to јас and 'am' to сум. Everything else is a word you already had.",
          reviews: ["pronoun-subject", "сум-present", "cognate-ист"],
        },
        {
          type: "note",
          title: "From: од",
          body:
            "Where you're from is the next thing anyone asks. The word is **од** = from:\n\n**Јас сум од Скопје.** - *I am from Skopje.*\n\nCountries and cities are just names: **Македонија**, **Скопје**, **Охрид**, **Израел**, **Германија**, **Англија**, **Америка**.",
          speak: ["Јас сум од Скопје.", "Јас сум од Македонија."],
          introduces: ["од-from"],
          ru: "Russian от is Macedonian од - and no case endings follow it. Од Македонија, done.",
          bg: "Bulgarian от is Macedonian од, with a д. Watch the end of the word.",
        },
        {
          type: "exercise",
          prompt: "**I am from Macedonia.**",
          answer: "Јас сум од Македонија",
          hint: "јас сум + од + Македонија.",
          reviews: ["од-from", "сум-present", "pronoun-subject"],
        },
        {
          type: "exercise",
          prompt: "**I am from Israel.**",
          answer: "Јас сум од Израел",
          hint: "од + Израел. Same sentence, different place.",
          after: "Од + a place. That's the whole recipe - you can now say where you're from.",
          reviews: ["од-from", "сум-present"],
        },
        {
          type: "note",
          title: "You are: ти си",
          body:
            "Now for 'you are' - talking to one person informally:\n\n**Ти си студент.** - *You are a student.*\n\n- **ти** = you\n- **си** = are\n\nNotice that 'to be' changes form: јас **сум**, but ти **си**. Each person gets its own form, like English 'am' vs. 'are'.",
          speak: ["Ти си студент."],
          ru: "Ти is Russian ты, and си is the form Russian lost. Keep saying it.",
        },
        {
          type: "exercise",
          prompt: "**You are a doctor.**",
          answer: "Ти си доктор",
          accept: ["ти си докторка"],
          hint: "ти си + доктор.",
          reviews: ["pronoun-subject", "сум-present"],
        },
        {
          type: "exercise",
          prompt: "**You are from Ohrid.**",
          answer: "Ти си од Охрид",
          hint: "ти си + од + Охрид.",
          after: "јас **сум**, ти **си** - two forms down. You're using the same pieces in new combinations, and that's the whole game.",
          reviews: ["pronoun-subject", "сум-present", "од-from"],
        },
        {
          type: "note",
          title: "He is: тој е",
          body:
            "Now for 'he is'. The verb form is **е** - just one letter, pronounced like the 'e' in 'bed':\n\n**Тој е доктор.** - *He is a doctor.*\n\n- **тој** = he (say 'toy')\n- **е** = is",
          speak: ["Тој е доктор."],
          bg: "Bulgarian той is written тој here - the й becomes ј. Same word, same sound.",
        },
        {
          type: "exercise",
          prompt: "**He is a student.**",
          answer: "Тој е студент",
          hint: "he = тој, is = е.",
          reviews: ["pronoun-subject", "сум-present"],
        },
        {
          type: "exercise",
          prompt: "**He is from Germany.**",
          answer: "Тој е од Германија",
          hint: "тој е + од + Германија.",
          after: "Тој е од Германија. You picked е for 'he' and од for 'from' - two decisions, both right.",
          reviews: ["pronoun-subject", "сум-present", "од-from"],
        },
        {
          type: "exercise",
          prompt: "**I am a tourist and he is a doctor.**",
          answer: "Јас сум турист и тој е доктор",
          accept: ["јас сум туристка и тој е доктор"],
          hint: "јас сум ... и тој е ...",
          after: "Three forms are in play now: сум, си, е. Each one belongs to its own pronoun.",
          reviews: ["pronoun-subject", "сум-present", "и-conjunction"],
        },
        {
          type: "note",
          title: "She is: таа е",
          body:
            "For 'she is', the verb stays **е** - same form as 'he is'. Only the pronoun changes:\n\n**Таа е од Скопје.** - *She is from Skopje.*\n\n- **таа** = she (two syllables: ta-a)",
          speak: ["Таа е од Скопје."],
          bg: "Bulgarian тя is Macedonian таа - a different word entirely, said as two clear а's.",
        },
        {
          type: "exercise",
          prompt: "**She is from England.**",
          answer: "Таа е од Англија",
          hint: "таа е + од + Англија.",
          reviews: ["pronoun-subject", "сум-present", "од-from"],
        },
        {
          type: "exercise",
          prompt: "**He is from Ohrid and she is from Skopje.**",
          answer: "Тој е од Охрид и таа е од Скопје",
          hint: "тој е ... и таа е ...",
          after: "Same е for both halves. Only тој and таа tell you who.",
          reviews: ["pronoun-subject", "сум-present", "од-from", "и-conjunction"],
        },
        {
          type: "note",
          title: "The feminine -ка",
          body:
            "When a woman says what she does, the profession word usually adds **-ка** at the end:\n\n- турист → **туристка**\n- студент → **студентка**\n- доктор → **докторка**\n\n**Таа е докторка.** - *She is a doctor.*",
          speak: ["Таа е докторка.", "туристка", "студентка"],
          introduces: ["feminine-ка"],
          he: "The -ка feminine ending works like Hebrew's ־ית: סטודנט → סטודנטית, студент → студентка.",
        },
        {
          type: "exercise",
          prompt: "**She is a journalist.**",
          answer: "Таа е журналистка",
          accept: ["таа е журналист"],
          hint: "she = таа, is = е, and add -ка for the feminine.",
          reviews: ["pronoun-subject", "сум-present", "feminine-ка"],
        },
        {
          type: "exercise",
          prompt: "**She is a student and he is a tourist.**",
          answer: "Таа е студентка и тој е турист",
          accept: ["таа е студент и тој е турист"],
          hint: "-ка on her word, nothing extra on his.",
          after: "Студентка for her, турист for him. The ending follows the person, not the sentence.",
          reviews: ["pronoun-subject", "сум-present", "feminine-ка", "и-conjunction"],
        },
        {
          type: "note",
          title: "It is: тоа е",
          body:
            "One more pronoun for now: **тоа** = it. Same verb form again, **е**:\n\n**Тоа е хотел.** - *It is a hotel.*\n**Тоа е проблем.** - *It is a problem.*\n\nSo тој, таа and тоа all take е. One verb form, three pronouns.",
          speak: ["Тоа е хотел.", "Тоа е проблем."],
          ru: "Russian это; Macedonian тоа - and, unlike Russian, followed by an actual verb: Тоа е проблем.",
        },
        {
          type: "exercise",
          prompt: "**It is a restaurant.**",
          answer: "Тоа е ресторан",
          hint: "тоа е + ресторан (no т at the end).",
          reviews: ["pronoun-subject", "сум-present"],
        },
        {
          type: "exercise",
          prompt: "**It is a bank and it is a problem.**",
          answer: "Тоа е банка и тоа е проблем",
          hint: "тоа е ... и тоа е ...",
          after: "Тоа е банка и тоа е проблем. Тој, таа, тоа - all three take е, so 'it' cost you nothing new. (You'll also hear тоа mean 'that' - later.)",
          reviews: ["pronoun-subject", "сум-present", "и-conjunction"],
        },
      ],
    },
    {
      id: "m1l3",
      title: "We, you all, they",
      subtitle: "Plural forms and dropping the pronoun",
      items: [
        {
          type: "note",
          title: "We are: ние сме",
          body:
            "You've got the singular: јас **сум**, ти **си**, тој/таа/тоа **е**. Now let's add the plural forms one at a time.\n\nFirst up - 'we are':\n\n- **ние** = we\n- **сме** = are (for 'we')\n\n**Ние сме од Македонија.** - *We are from Macedonia.*",
          speak: ["Ние сме од Македонија."],
          ru: "Ние is Russian мы in different clothes; сме is the form Russian dropped.",
        },
        {
          type: "note",
          title: "Making plurals with -и",
          body:
            "To make a person-word plural, add **-и** at the end:\n\n- турист → **туристи**\n- студент → **студенти**\n\nFull plural story later - for now, **-и** is all you need.",
          speak: ["туристи", "студенти"],
          introduces: ["plural-и"],
          he: "Hebrew adds ־ים (סטודנטים); Macedonian adds -и (студенти). A plural ending, same job.",
        },
        {
          type: "exercise",
          prompt: "**We are tourists.**",
          answer: "Ние сме туристи",
          hint: "we = ние сме; plural of турист is туристи.",
          reviews: ["pronoun-subject", "сум-present", "plural-и"],
        },
        {
          type: "exercise",
          prompt: "**We are students.**",
          answer: "Ние сме студенти",
          hint: "ние сме + студенти.",
          after: "студент → студент**и**. The -и plural works for most person-words.",
          reviews: ["pronoun-subject", "сум-present", "plural-и"],
        },
        {
          type: "exercise",
          prompt: "**We are from Ohrid.**",
          answer: "Ние сме од Охрид",
          hint: "ние сме + од + Охрид.",
          after: "Same од as before - it doesn't care how many of you there are.",
          reviews: ["pronoun-subject", "сум-present", "од-from"],
        },
        {
          type: "note",
          title: "You all are: вие сте",
          body:
            "Now 'you' for several people:\n\n- **вие** = you (plural)\n- **сте** = are (for 'you all')\n\n**Вие сте од Англија.** - *You (all) are from England.*\n\n**Вие сте** is also the polite 'you' for one person - like French *vous*. More on that much later.",
          speak: ["Вие сте од Англија."],
        },
        {
          type: "exercise",
          prompt: "**You (plural) are journalists.**",
          answer: "Вие сте журналисти",
          hint: "you-all = вие сте; журналист → журналисти.",
          reviews: ["pronoun-subject", "сум-present", "plural-и", "cognate-ист"],
        },
        {
          type: "exercise",
          prompt: "**You (plural) are doctors.**",
          answer: "Вие сте доктори",
          hint: "вие сте + доктори.",
          after: "доктор → доктор**и**. Same pattern.",
          reviews: ["pronoun-subject", "сум-present", "plural-и", "cognate-ор"],
        },
        {
          type: "exercise",
          prompt: "**You (plural) are from Germany.**",
          answer: "Вие сте од Германија",
          hint: "вие сте + од + Германија.",
          reviews: ["pronoun-subject", "сум-present", "од-from"],
        },
        {
          type: "note",
          title: "They are: тие се",
          body:
            "Last one - 'they are':\n\n- **тие** = they (say 'tee-ye')\n- **се** = are (for 'they')\n\n**Тие се студенти.** - *They are students.*",
          speak: ["Тие се студенти."],
          ru: "Russian они; Macedonian тие. And се here is simply 'they are' - nothing reflexive about it.",
          bg: "Bulgarian те са is Macedonian тие се: both the pronoun and the verb form differ, so don't convert letter by letter.",
        },
        {
          type: "exercise",
          prompt: "**They are students.**",
          answer: "Тие се студенти",
          hint: "they = тие, are = се; plural of студент is студенти.",
          reviews: ["pronoun-subject", "сум-present", "plural-и"],
        },
        {
          type: "exercise",
          prompt: "**They are tourists.**",
          answer: "Тие се туристи",
          hint: "тие се + туристи.",
          reviews: ["pronoun-subject", "сум-present", "plural-и"],
        },
        {
          type: "exercise",
          prompt: "Back to singular: **She is a student.**",
          answer: "Таа е студентка",
          accept: ["таа е студент"],
          hint: "she = таа е; feminine adds -ка.",
          after: "Weaving the singular back in. You're choosing between six forms of 'to be' now.",
          reviews: ["pronoun-subject", "сум-present", "feminine-ка"],
        },
        {
          type: "note",
          title: "Here and there",
          body:
            "Two handy little words:\n\n- **тука** = here (you'll also hear **овде**)\n- **таму** = there\n\n**Тој е тука.** - *He is here.*\n**Таа е таму.** - *She is there.*",
          speak: ["Тој е тука.", "Таа е таму."],
          ru: "Russian тут / там; Macedonian тука / таму - one syllable longer, same meaning.",
          bg: "Bulgarian тук and там grow a vowel here: тука, таму.",
        },
        {
          type: "exercise",
          prompt: "**She is here.**",
          answer: "Таа е тука",
          accept: ["таа е овде"],
          hint: "таа + е + тука.",
          reviews: ["pronoun-subject", "сум-present", "тука"],
        },
        {
          type: "exercise",
          prompt: "**They are there.**",
          answer: "Тие се таму",
          hint: "тие + се + таму.",
          reviews: ["pronoun-subject", "сум-present", "таму"],
        },
        {
          type: "exercise",
          prompt: "**We are here and they are there.**",
          answer: "Ние сме тука и тие се таму",
          accept: ["ние сме овде и тие се таму"],
          hint: "ние сме тука, и (and), тие се таму.",
          after: "Сме for we, се for they - and you kept тука and таму straight.",
          reviews: ["pronoun-subject", "сум-present", "тука", "таму", "и-conjunction"],
        },
        {
          type: "note",
          title: "Now drop the pronoun",
          body:
            "Since **сум** can only mean 'I am' and **сме** can only mean 'we are', Macedonians usually drop the pronoun. The verb form tells you who.\n\nWhen the pronoun goes, the description naturally comes first and the verb follows it:\n\n- Јас сум студент → **Студент сум.**\n- Ние сме туристи → **Туристи сме.**\n- Јас сум од Скопје → **Од Скопје сум.**\n\nThat's the rhythm people actually use. Not a law - just how it sounds right.",
          speak: ["Студент сум.", "Туристи сме.", "Од Скопје сум."],
          introduces: ["pronoun-drop"],
          reviews: ["сум-position"],
          he: "Same idea as Hebrew past tense: הלכתי needs no אני because the ending tells you. Macedonian works the same way.",
          ru: "Russian drops the verb and keeps the pronoun ('I student'). Macedonian does the opposite: drops the pronoun, keeps the verb (Студент сум).",
          bg: "Bulgarian has a hard rule that съм can never be the first word. Macedonian has no such rule - description-first (Студент сум) is simply the natural rhythm, and later you'll see се, ќе and object pronouns start sentences freely.",
        },
        {
          type: "exercise",
          prompt: "Say **I am a doctor** without the pronoun.",
          answer: "Доктор сум",
          accept: ["докторка сум"],
          hint: "Lead with доктор, then сум.",
          reviews: ["сум-present", "pronoun-drop", "сум-position", "cognate-ор"],
        },
        {
          type: "exercise",
          prompt: "**I am a journalist** - no pronoun.",
          answer: "Журналист сум",
          accept: ["журналистка сум"],
          hint: "Noun first, then сум.",
          after: "Журналист сум. Nobody needs јас - сум already says 'I'.",
          reviews: ["сум-present", "pronoun-drop", "сум-position", "cognate-ист"],
        },
        {
          type: "exercise",
          prompt: "**We are tourists** - no pronoun.",
          answer: "Туристи сме",
          hint: "The plural noun first, then the 'we' form: сме.",
          reviews: ["сум-present", "pronoun-drop", "plural-и"],
        },
        {
          type: "exercise",
          prompt: "Without the pronoun: **I am from Macedonia.**",
          answer: "Од Македонија сум",
          hint: "од Македонија goes first, then сум.",
          after: "Од Македонија сум. The whole 'from' phrase moved to the front together.",
          reviews: ["сум-present", "pronoun-drop", "од-from"],
        },
        {
          type: "exercise",
          prompt: "**You (plural) are here** - no pronoun.",
          answer: "Тука сте",
          accept: ["овде сте"],
          hint: "тука first, then the 'you all' form.",
          reviews: ["сум-present", "pronoun-drop", "тука"],
        },
        {
          type: "exercise",
          prompt: "**He is here and she is there.**",
          answer: "Тој е тука и таа е таму",
          accept: ["тој е овде и таа е таму"],
          hint: "тој е тука, и, таа е таму.",
          after: "Switching between long and short sentences keeps the whole system active.",
          reviews: ["pronoun-subject", "сум-present", "тука", "таму", "и-conjunction"],
        },
        {
          type: "note",
          title: "The whole family",
          body:
            "**сум, си, е, сме, сте, се** - you now conjugate the most used verb in the language.\n\n- Јас **сум** - ти **си** - тој/таа/тоа **е**\n- Ние **сме** - вие **сте** - тие **се**\n\nYou got here one form at a time. Say a few true sentences about yourself before moving on. *Студент сум. Од Израел сум. Тука сум.*",
          speak: ["Студент сум.", "Од Израел сум.", "Тука сум."],
          bg: "The full set next to Bulgarian: съм/сум, си/си, е/е, сме/сме, сте/сте, са/се. Only the first and last differ.",
        },
      ],
    },
    {
      id: "m1l4",
      title: "Saying no",
      subtitle: "не",
      items: [
        {
          type: "note",
          title: "Saying no",
          body:
            "Negation is one word, **не**, placed right before the verb:\n\n- **Не сум доктор.** - *I'm not a doctor.*\n- **Тој не е тука.** - *He is not here.*\n\nНе and the verb travel together as a unit. Whatever else is in the sentence, не sits right before the form of 'to be'.",
          speak: ["Не сум доктор.", "Тој не е тука."],
          introduces: ["не-negation"],
          ru: "Same не as Russian - but Russian says 'I not doctor' with no verb. Macedonian keeps the verb: не **сум** доктор.",
          he: "Hebrew לא sits before the predicate (אני לא רופא). Macedonian не does the same, but there's a verb to attach to: не сум.",
        },
        {
          type: "exercise",
          prompt: "**I am not a journalist.**",
          answer: "Не сум журналист",
          accept: ["јас не сум журналист", "не сум журналистка", "јас не сум журналистка"],
          hint: "не goes before the verb: Не сум…",
          after: "Не сум журналист. With the pronoun gone, не simply leads.",
          reviews: ["сум-present", "pronoun-drop", "не-negation"],
        },
        {
          type: "exercise",
          prompt: "**He is not here.**",
          answer: "Тој не е тука",
          accept: ["не е тука", "тој не е овде"],
          hint: "тој + не е + тука.",
          after: "**Не е** flows together as 'ne-E'.",
          reviews: ["pronoun-subject", "сум-present", "тука", "не-negation"],
        },
        {
          type: "exercise",
          prompt: "**She is not a tourist.**",
          answer: "Таа не е туристка",
          accept: ["таа не е турист", "не е туристка"],
          hint: "таа + не е + туристка.",
          after: "Same pattern: не sits right before the verb, and -ка stays on her word.",
          reviews: ["pronoun-subject", "сум-present", "feminine-ка", "не-negation"],
        },
        {
          type: "exercise",
          prompt: "**We are not from Skopje.**",
          answer: "Не сме од Скопје",
          accept: ["ние не сме од Скопје"],
          hint: "не + сме + од Скопје.",
          reviews: ["сум-present", "од-from", "pronoun-drop", "не-negation"],
        },
        {
          type: "exercise",
          prompt: "**They are not students.**",
          answer: "Тие не се студенти",
          accept: ["не се студенти"],
          hint: "тие + не се + студенти.",
          after: "Same не, different verb form. Не works with every form of 'to be'.",
          reviews: ["pronoun-subject", "сум-present", "plural-и", "не-negation"],
        },
        {
          type: "exercise",
          prompt: "**She is not a student, she is a journalist.**",
          answer: "Таа не е студентка, таа е журналистка",
          accept: ["таа не е студентка, таа е журналист", "таа не е студент, таа е журналист", "не е студентка, журналистка е", "таа не е студентка, журналистка е"],
          hint: "не е for 'is not', then таа е for the correction.",
          after: "You can deny and correct in one breath. That's how conversations work.",
          reviews: ["pronoun-subject", "сум-present", "feminine-ка", "не-negation"],
        },
        {
          type: "note",
          title: "Yes and no",
          body:
            "The two shortest answers:\n\n- **Да.** = Yes.\n- **Не.** = No.\n\nAnd the same не does both jobs in one line:\n\n**Не, не сум турист.** - *No, I'm not a tourist.*",
          speak: ["Да.", "Не.", "Не, не сум турист."],
          ru: "Да and не(т) - the same two words, minus Russian's final т on нет.",
        },
        {
          type: "exercise",
          prompt: "**No, I am not a doctor.**",
          answer: "Не, не сум доктор",
          accept: ["не, јас не сум доктор", "не, не сум докторка"],
          hint: "The first не answers; the second не negates the verb.",
          after: "Не, не сум доктор. Two не's, two jobs - and you placed the second one right before сум.",
          reviews: ["сум-present", "pronoun-drop", "не-negation"],
        },
        {
          type: "note",
          body:
            "Не before any form of 'to be' and you've said no. Six verb forms, one rule. Next: asking questions.",
        },
      ],
    },
    {
      id: "m1l5",
      title: "Asking questions",
      subtitle: "дали, ли, нели",
      items: [
        {
          type: "note",
          title: "The question word дали",
          body:
            "The easiest way to ask a yes/no question in Macedonian: put **дали** at the front. Nothing else moves.\n\n- Ти си студент. → **Дали си студент?** - *Are you a student?*\n- Таа е тука. → **Дали е тука?** - *Is she here?*\n\nДали is a signpost: 'question coming'. The sentence behind it stays exactly as it was.",
          speak: ["Дали си студент?", "Дали е тука?"],
          introduces: ["дали-question"],
          he: "Hebrew opens a yes/no question with האם, in exactly the same spot. Дали is your האם.",
          ru: "Russian has no such word - it asks with intonation alone. Macedonian gives you a signpost: дали at the front.",
          bg: "Bulgarian keeps дали for indirect or wondering questions (не знам дали...); in Macedonian it's the everyday, direct way to ask, ahead of ли.",
        },
        {
          type: "exercise",
          prompt: "Ask: **Are you a student?**",
          answer: "Дали си студент?",
          accept: ["дали ти си студент", "дали си студентка"],
          hint: "дали + the statement 'you are a student', pronoun dropped.",
          after: "Дали си студент? You built the statement and put дали in front of it. That's the entire move.",
          reviews: ["сум-present", "pronoun-drop", "дали-question"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Is he from Ohrid?**",
          answer: "Дали е од Охрид?",
          accept: ["дали тој е од Охрид", "дали е тој од Охрид"],
          hint: "дали + е + од Охрид.",
          reviews: ["сум-present", "од-from", "дали-question"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Are they from America?**",
          answer: "Дали се од Америка?",
          accept: ["дали тие се од Америка", "дали се тие од Америка"],
          hint: "дали + се (the 'they' form) + од Америка.",
          reviews: ["сум-present", "од-from", "дали-question"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Are you (plural) tourists?**",
          answer: "Дали сте туристи?",
          accept: ["дали вие сте туристи"],
          hint: "Plural 'you' = сте. дали + сте + туристи.",
          after: "Same дали, different verb form. The question word doesn't care who's speaking.",
          reviews: ["plural-и", "сум-present", "pronoun-drop", "дали-question"],
        },
        {
          type: "note",
          title: "Answering",
          body:
            "— **Дали си студент?**\n— **Да, студент сум.** / **Не, не сум студент.**\n\nThe answer drops the pronoun and puts the description first - the rhythm from last lesson.",
          speak: ["Дали си студент?", "Да, студент сум.", "Не, не сум студент."],
        },
        {
          type: "exercise",
          prompt: "Answer: **Yes, I am a tourist.**",
          answer: "Да, турист сум",
          accept: ["да, туристка сум", "да, јас сум турист", "да, јас сум туристка"],
          hint: "да, then the description, then сум.",
          reviews: ["сум-present", "pronoun-drop", "сум-position"],
        },
        {
          type: "note",
          title: "The particle ли",
          body:
            "The second way to ask: the little word **ли**, placed right *after* the thing you're asking about:\n\n- **Студент ли си?** - *Are you a student?* (asking about 'student')\n- **Тука ли е?** - *Is she here?* (asking about 'here')\n\nЛи is unstressed and glues to the word before it. Use дали when you just want a question; use ли when you want to spotlight one word.",
          speak: ["Студент ли си?", "Тука ли е?"],
          introduces: ["ли-question"],
          ru: "Russian has ли too, but there it's optional and bookish. In Macedonian it's everyday - just second choice after дали.",
          bg: "Bulgarian's default question is ли; Macedonian's default is дали, with ли kept for spotlighting one word. Same particle, same slot, different frequency.",
        },
        {
          type: "exercise",
          prompt: "Ask with ли: **Are you a doctor?**",
          answer: "Доктор ли си?",
          accept: ["ти доктор ли си", "докторка ли си"],
          hint: "Put ли right after доктор, then the verb.",
          reviews: ["сум-present", "pronoun-drop", "ли-question"],
        },
        {
          type: "exercise",
          prompt: "Ask with ли: **Is he a journalist?**",
          answer: "Журналист ли е?",
          accept: ["тој журналист ли е", "журналист ли е тој"],
          hint: "журналист + ли + е.",
          after: "See the rhythm? Word-ли-verb. Same slot every time.",
          reviews: ["сум-present", "pronoun-drop", "ли-question"],
        },
        {
          type: "exercise",
          prompt: "Ask with ли: **Are they here?**",
          answer: "Тука ли се?",
          accept: ["тие тука ли се", "тука ли се тие", "овде ли се"],
          hint: "ли right after тука, then се.",
          reviews: ["сум-present", "тука", "ли-question"],
        },
        {
          type: "exercise",
          prompt: "Your choice of дали or ли: **Are we from Macedonia?**",
          answer: "Дали сме од Македонија?",
          accept: ["од Македонија ли сме", "дали ние сме од Македонија", "ние од Македонија ли сме"],
          hint: "Either дали at the front, or ли after 'од Македонија'.",
          after: "Both work. Дали сме од Македонија? is the plain question; Од Македонија ли сме? leans on 'Macedonia'.",
          reviews: ["сум-present", "од-from", "дали-question", "ли-question"],
        },
        {
          type: "note",
          title: "нели - the tag question",
          body:
            "**Нели** turns a statement into 'right?' / 'isn't it?':\n\n**Ти си од Скопје, нели?** - *You're from Skopje, right?*\n\nJust stick it at the end of any statement.",
          speak: ["Ти си од Скопје, нели?"],
          introduces: ["нели-tag"],
          he: "Like נכון? at the end of a Hebrew sentence.",
          bg: "Bulgarian нали is Macedonian нели - the а becomes е.",
        },
        {
          type: "choice",
          prompt: "**Таа е докторка, нели?** means…",
          options: [
            "She's a doctor, right?",
            "Is she really a doctor?",
            "She is not a doctor.",
          ],
          correct: 0,
          reviews: ["нели-tag", "feminine-ка"],
        },
        {
          type: "exercise",
          prompt: "Ask with a tag: **He is here, right?**",
          answer: "Тој е тука, нели?",
          accept: ["тука е, нели", "тој е овде, нели"],
          hint: "Statement + , нели?",
          reviews: ["pronoun-subject", "сум-present", "тука", "нели-tag"],
        },
        {
          type: "exercise",
          prompt: "**We are from Macedonia, right?**",
          answer: "Ние сме од Македонија, нели?",
          accept: ["од Македонија сме, нели"],
          hint: "Statement + , нели?",
          after: "Нели sits at the end and turns any statement into a question. No moving parts.",
          reviews: ["pronoun-subject", "сум-present", "од-from", "нели-tag"],
        },
        {
          type: "note",
          title: "Negative questions",
          body:
            "To ask a negative question ('Aren't you...?'), combine не with ли. The order: **не** + verb + **ли**:\n\n**Не си ли студент?** - *Aren't you a student?*\n\nNot the pronoun, not the noun: in a negative question, ли follows the verb.",
          speak: ["Не си ли студент?"],
          introduces: ["neg-question"],
          bg: "Same shape as Bulgarian (Не си ли студент?). Colloquial Macedonian also has зар: Зар не си студент?",
        },
        {
          type: "exercise",
          prompt: "**Aren't you a student?**",
          answer: "Не си ли студент?",
          accept: ["ти не си ли студент", "не си ли студентка"],
          hint: "не + verb, then ли after the verb: Не си ли…",
          reviews: ["не-negation", "сум-present", "pronoun-drop", "neg-question"],
        },
        {
          type: "exercise",
          prompt: "**Isn't she here?**",
          answer: "Не е ли тука?",
          accept: ["таа не е ли тука", "не е ли овде"],
          hint: "не + е + ли + тука.",
          after: "In negative questions ли follows the verb: Не си ли…? Не е ли…?",
          reviews: ["не-negation", "сум-present", "тука", "neg-question"],
        },
        {
          type: "exercise",
          prompt: "**Aren't they students?**",
          answer: "Не се ли студенти?",
          accept: ["тие не се ли студенти"],
          hint: "не + се + ли + студенти.",
          after: "Не се ли студенти? On the street you'll also hear **Зар не се студенти?** - зар is a colloquial 'surely...?' Recognize it; you don't need to produce it.",
          reviews: ["не-negation", "сум-present", "plural-и", "neg-question"],
        },
        {
          type: "note",
          body:
            "You can now state, deny, and ask - three ways. That's a complete conversational toolkit.\n\nNext module: verbs - where Macedonian gets genuinely fun.",
          ru: "One false friend to bank early: Macedonian **стол** is a *chair*, not a table. A table is маса.",
        },
      ],
    },
  ],
};
