import type { Module } from "./types";

export const module7: Module = {
  id: "m7",
  title: "8. Being Macedonian",
  blurb:
    "The polite 'you', the art of liking things, and a story that proves you can read Macedonian.",
  lessons: [
    {
      id: "m7l1",
      title: "The polite you",
      subtitle: "Вие, Како сте, Ве молам",
      items: [
        {
          type: "note",
          title: "You already know this form",
          body:
            "Remember **вие сте** - 'you all are'? It doubles as the polite form for one person. A stranger, a waiter, anyone older - you use the same вие-forms you already know, and write it with a capital: **Вие**.\n\nFrench has *vous*. Macedonian has **Вие**. Same idea, and you've already practiced every verb form you need.",
          speak: ["Вие сте од Скопје?", "Како сте?"],
          he: "Hebrew has no polite 'you' - everyone is אתה/את regardless of status. Macedonian has two levels: ти for friends, Вие for respect.",
          ru: "This is exactly Russian вы - same situations, same verb forms. Zero relearning.",
          introduces: ["вие-polite"],
        },
        {
          type: "note",
          title: "Polite in practice",
          body:
            "Every verb you know has a вие-form you've been using for 'you all'. Point it at one person and it turns polite:\n\n**Дали зборувате англиски?** - Do you speak English?\n**Како се викате?** - What's your name?\n**Како сте?** - How are you?\n\nNothing new to learn - just a new person to say it to.",
          speak: ["Дали зборувате англиски?", "Како се викате?", "Како сте?"],
        },
        {
          type: "exercise",
          prompt: "Ask a stranger politely: **Do you speak English?**",
          answer: "Дали зборувате англиски?",
          accept: ["Зборувате ли англиски?"],
          hint: "Polite = the вие-form: дали + зборувате + англиски.",
          after: "The single most useful sentence in Macedonia. Дали up front, зборувате for one respected person - you'll say this one a lot.",
          reviews: ["зборувам", "дали-question", "англиски", "verb-а-group"],
        },
        {
          type: "exercise",
          prompt: "Ask politely: **What's your name?**",
          answer: "Како се викате?",
          hint: "Како + се + the вие-form of се викам (викате).",
          after: "Notice се still lands before the verb - same dance as always, polite or not.",
          reviews: ["како-how", "викам", "reflexive-се", "verb-а-group"],
        },
        {
          type: "exercise",
          prompt: "Ask politely: **How are you?**",
          answer: "Како сте?",
          hint: "Како + the вие-form of сум (сте).",
          after: "**Како сте?** is the default question for anyone you'd address with Вие. You picked сте, the form that goes with вие - that's the whole trick.",
          reviews: ["како-how", "сум-present"],
        },
        {
          type: "note",
          title: "Hello, politely",
          body:
            "**Здраво** is for friends. For someone you'd call Вие, there is no special 'hello' word - you greet them with the time of day:\n\n**Добар ден! Како сте?** - Good day! How are you?\n\nMorning: **Добро утро**. Evening: **Добра вечер**. Any of these plus **Како сте?** and you sound like you've done this before.",
          speak: ["Добар ден! Како сте?"],
          bg: "Bulgarian has a polite hello, Здравейте; Macedonian doesn't - здраво stays informal, and the polite greeting is добар ден.",
          reviews: ["здраво", "добар ден", "добро утро", "добра вечер"],
        },
        {
          type: "choice",
          prompt: "You meet your friend's grandmother for the first time. You say...",
          options: ["Добар ден, како сте?", "Здраво, како си?", "Добро утро, како си?"],
          correct: 0,
          after: "Grandmother = polite. Добар ден + Како сте. Always safe.",
          reviews: ["добар ден", "како-how", "сум-present"],
        },
        {
          type: "exercise",
          prompt: "Ask politely: **Do you want coffee?**",
          answer: "Дали сакате кафе?",
          accept: ["Сакате ли кафе?"],
          hint: "Polite = the вие-form of сакам: дали + сакате + кафе.",
          after: "You're not learning new verbs - just shifting to the вие-form you already own. Сакате, the same ending you used for 'you all', now addressed to one person.",
          reviews: ["сакам", "дали-question", "verb-а-group"],
        },
        {
          type: "exercise",
          prompt: "Ask politely: **Where do you live?**",
          answer: "Каде живеете?",
          hint: "Каде + the вие-form of живеам (живеете).",
          after: "Живеете - the е-group's вие-form, with its double е. Polite and correct.",
          reviews: ["verb-е-group", "каде-where", "живеам"],
        },
        {
          type: "note",
          title: "Ве молам, finally explained",
          body:
            "You've been saying **Ве молам** for 'please' since module 2. Now you can see inside it: **ве** is 'you' (the вие object pronoun), and **молам** is 'I ask, I beg'. So 'please' is literally *I ask you* - a polite Вие sentence.\n\nWhich means with a friend it changes: **те молам** - 'I ask you' with the ти pronoun.",
          speak: ["Ве молам.", "Те молам."],
          he: "Hebrew's בבקשה is a noun ('by request'). Macedonian's please is a verb with a pronoun - 'I ask you' - so it changes with the person you're asking.",
          ru: "Russian пожалуйста is a fixed word; the Macedonian please is built like прошу вас / прошу тебя - a verb plus 'you'.",
          bg: "Bulgarian моля stands alone; Macedonian keeps the object pronoun in there - Ве молам to a stranger, те молам to a friend.",
          requires: ["object-pronoun-pl"],
          reviews: ["ве молам", "object-pronoun-pl", "object-pronoun-sg"],
        },
        {
          type: "exercise",
          prompt: "Ask a friend: **Please, one coffee.**",
          answer: "Те молам, едно кафе",
          accept: ["Едно кафе, те молам"],
          hint: "Friend = ти-level, so the pronoun is те: те молам + едно кафе.",
          after: "You switched ве to те because it's a friend - the 'please' moved down a register with you.",
          reviews: ["ве молам", "object-pronoun-sg", "numbers-1-5"],
        },
        {
          type: "exercise",
          prompt: "To the waiter: **Excuse me, the bill, please.**",
          answer: "Извинете, сметката, Ве молам",
          accept: ["Извинете, Ве молам, сметката"],
          hint: "извинете + сметката (the bill, feminine -та) + the polite please.",
          after: "A waiter gets Вие, so it's Ве молам. And извинете is itself a вие-form - you've been polite all along.",
          reviews: ["извинете", "сметка", "definite-fem", "ве молам", "вие-polite"],
        },
        {
          type: "note",
          title: "Наздравје!",
          body:
            "**Наздравје** - literally 'to health' - is *cheers!* with a raised glass, and also *bless you!* after a sneeze. With this and Вие, your social Macedonian is complete.",
          speak: ["Наздравје!"],
          ru: "Russian на здоровье looks identical but means 'you're welcome' - in Macedonia you say it with a glass in your hand.",
          bg: "Bulgarian наздраве; Macedonian adds a ј before the ending: наздравје.",
        },
        {
          type: "exercise",
          prompt: "Greet someone politely and ask where they're from: **Good day! Where are you from?**",
          answer: "Добар ден! Од каде сте?",
          accept: ["Добар ден, од каде сте?"],
          hint: "Polite greeting + од каде + the вие-form of сум.",
          after: "Од каде сте - 'from where are you'. Од leads, сте closes, and the whole thing is polite because of that one verb form.",
          reviews: ["вие-polite", "добар ден", "од-from", "каде-where", "сум-present"],
        },
        {
          type: "exercise",
          prompt: "Raise your glass: **Cheers! The beer is good!**",
          answer: "Наздравје! Пивото е добро!",
          accept: ["Наздравје, пивото е добро"],
          hint: "наздравје + пивото (the beer, neuter -то) + добро (neuter form).",
          after: "Пиво is neuter, so both the article and the adjective end in -о: пивото е добро. Gender agreement, even after a drink.",
          bg: "Bulgarian бирата е хубава is feminine; Macedonian пиво is neuter, so the article and adjective take -о: пивото е добро.",
          reviews: ["наздравје", "пиво", "definite-neuter", "добар", "adj-agreement", "сум-present"],
        },
      ],
    },
    {
      id: "m7l2",
      title: "Liking things",
      subtitle: "ми се допаѓа, вкусно, уште",
      items: [
        {
          type: "note",
          title: "It pleases me",
          body:
            "Macedonian doesn't say 'I like it'. It says 'it pleases me':\n\n**Ми се допаѓа.** - I like it. (literally: to-me it-pleases)\n\nThree pieces in a fixed order: **ми** (to me), then **се**, then the verb **допаѓа**. The little words go first, the verb last - and that ми is the same 'to me' from **Мило ми е**.",
          speak: ["Ми се допаѓа."],
          introduces: ["допаѓа-ми"],
          he: "Hebrew has the same shape in מוצא חן בעיני - the thing does the pleasing, and you are the one it happens to.",
          ru: "The logic is мне нравится - dative you, the thing as subject. Russian has no се in there and puts the verb first; Macedonian puts ми се before it.",
          bg: "Bulgarian харесва ми puts the verb first and the ми after; Macedonian ми се допаѓа starts with the clitics, in the order ми, се, verb - even at the start of a sentence.",
        },
        {
          type: "exercise",
          prompt: "**I like it.**",
          answer: "Ми се допаѓа",
          hint: "To-me + се + допаѓа. Little words first.",
          after: "Ми, се, допаѓа - you started the sentence with the little words, which is exactly where Macedonian wants them.",
          reviews: ["dative-ми", "clitic-proclitic"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you like it?**",
          answer: "Дали ти се допаѓа?",
          accept: ["Ти се допаѓа ли?", "Ти се допаѓа?"],
          hint: "Swap ми for ти (to you), and put дали in front.",
          after: "Ми became ти - 'to you' - and everything else stayed put. Дали sits in front and never disturbs the ми-се-verb chain.",
          reviews: ["дали-question", "dative-ми"],
        },
        {
          type: "exercise",
          prompt: "**I don't like it.**",
          answer: "Не ми се допаѓа",
          hint: "не goes first, then the chain: ми се допаѓа.",
          after: "Не in front, and the three-word chain stays glued together behind it. Same placement rule as Не те разбирам.",
          reviews: ["не-negation", "clitic-placement"],
        },
        {
          type: "note",
          title: "Naming the thing you like",
          body:
            "The liked thing is the grammatical subject - it's the one doing the pleasing:\n\n**Ми се допаѓа Скопје.** - I like Skopje. (Skopje pleases me)\n\nThe thing can also go first - **Скопје ми се допаѓа** - but the chain **ми се допаѓа** stays together, in that order, either way.",
          speak: ["Ми се допаѓа Скопје.", "Скопје ми се допаѓа."],
        },
        {
          type: "exercise",
          prompt: "**I like Macedonia.**",
          answer: "Ми се допаѓа Македонија",
          accept: ["Македонија ми се допаѓа"],
          hint: "The chain first, then the thing: ми се допаѓа + Македонија.",
          after: "Macedonia is doing the pleasing, you're on the receiving end. The chain didn't move.",
          reviews: ["допаѓа-ми", "dative-ми"],
        },
        {
          type: "exercise",
          prompt: "**I like the coffee.**",
          answer: "Ми се допаѓа кафето",
          accept: ["Кафето ми се допаѓа"],
          hint: "ми се допаѓа + кафето (the coffee).",
          after: "Same pattern, different subject. Кафето with its -то, since it's a specific coffee that pleases you.",
          reviews: ["допаѓа-ми", "dative-ми", "definite-neuter"],
        },
        {
          type: "exercise",
          prompt: "**I don't like the wine.**",
          answer: "Не ми се допаѓа виното",
          accept: ["Виното не ми се допаѓа"],
          hint: "не ми се допаѓа + виното (the wine).",
          after: "Не, then the chain, then the wine. Or the wine first and the rest unchanged - both are how people say it.",
          reviews: ["не-negation", "clitic-placement", "definite-neuter", "вино"],
        },
        {
          type: "note",
          title: "Liking more than one thing",
          body:
            "Since the liked thing is the subject, the verb agrees with it. Several things → the they-form:\n\n**Ми се допаѓаат студентите.** - I like the students. (they please me)\n\nДопаѓа is an а-group verb, so the they-form has the double а you know from сакаат.",
          speak: ["Ми се допаѓаат студентите."],
          bg: "Bulgarian харесват ми becomes ми се допаѓаат - the а-group they-form with its double а.",
          reviews: ["verb-а-group"],
        },
        {
          type: "exercise",
          prompt: "**I like the students.**",
          answer: "Ми се допаѓаат студентите",
          accept: ["Студентите ми се допаѓаат"],
          hint: "Plural subject → допаѓаат (double а) + студентите.",
          after: "You matched the verb to the students, not to yourself - they're the ones pleasing you, so they get the they-form.",
          reviews: ["допаѓа-ми", "verb-а-group", "noun-plural-basic"],
        },
        {
          type: "note",
          title: "Liking a person: ми се допаѓаш",
          body:
            "A person can be the subject too - and then the verb agrees with *them*:\n\n**Ми се допаѓаш.** - I like you. (you please me - so the verb takes the you-ending -ш)\n\nOne step up the scale is **Те сакам** - I love you. Сакам is 'want' and 'love'; допаѓа is 'like'. Use responsibly.",
          speak: ["Ми се допаѓаш.", "Те сакам."],
          bg: "Bulgarian switches to a direct verb for people (харесвам те); Macedonian keeps the dative pattern and just conjugates it: ми се допаѓаш.",
          reviews: ["сакам", "object-pronoun-sg"],
        },
        {
          type: "exercise",
          prompt: "**I like you.**",
          answer: "Ми се допаѓаш",
          hint: "Same chain, but the verb agrees with 'you': допаѓаш.",
          after: "You are the subject here, so the verb wears the -ш of ти. The ми still says who's doing the liking.",
          reviews: ["допаѓа-ми", "verb-а-group", "dative-ми"],
        },
        {
          type: "exercise",
          prompt: "**I love you.**",
          answer: "Те сакам",
          hint: "The direct verb: те (you, object) + сакам.",
          after: "Сакам wants and loves; the pronoun те goes before it, as every short pronoun does. Now you have the whole scale.",
          reviews: ["сакам", "object-pronoun-sg", "clitic-proclitic"],
        },
        {
          type: "note",
          title: "He likes, she likes",
          body:
            "To change who's doing the liking, change the first word of the chain. You know **му** (to him) and **ѝ** (to her) from possession:\n\n**Му се допаѓа Скопје.** - He likes Skopje.\n**Ѝ се допаѓа кафето.** - She likes the coffee.\n\nThe се and the verb don't care who it is - only the first slot changes.",
          speak: ["Му се допаѓа Скопје.", "Ѝ се допаѓа кафето."],
          requires: ["dative-му-ѝ"],
          reviews: ["dative-му-ѝ"],
        },
        {
          type: "exercise",
          prompt: "**He likes Skopje.**",
          answer: "Му се допаѓа Скопје",
          accept: ["Скопје му се допаѓа"],
          hint: "му (to him) + се допаѓа + Скопје.",
          after: "Му in the first slot - the same му from телефонот му. One small word tells you it's him doing the liking.",
          reviews: ["допаѓа-ми", "dative-му-ѝ"],
        },
        {
          type: "exercise",
          prompt: "**She doesn't like the city.**",
          answer: "Не ѝ се допаѓа градот",
          accept: ["Градот не ѝ се допаѓа"],
          hint: "не + ѝ (to her) + се допаѓа + градот.",
          after: "Не first, ѝ next, then се допаѓа, then the city with its -от. Four decisions, all correct.",
          reviews: ["не-negation", "dative-му-ѝ", "definite-masc", "град"],
        },
        {
          type: "note",
          title: "вкусно - tasty",
          body:
            "The word that belongs at every Macedonian table: **вкусно** - tasty, delicious.\n\n**Многу е вкусно!** - It's very tasty!\n**Вкусно е, нели?** - It's tasty, right?",
          speak: ["Многу е вкусно!", "Вкусно е, нели?"],
          ru: "Вкусно is the same word as Russian вкусно, letter for letter.",
        },
        {
          type: "exercise",
          prompt: "**It's very tasty!**",
          answer: "Многу е вкусно!",
          accept: ["Многу вкусно е"],
          hint: "многу + е + вкусно.",
          after: "Многу е вкусно - the compliment every cook in Macedonia is waiting for.",
          reviews: ["многу", "вкусно", "сум-present"],
        },
        {
          type: "exercise",
          prompt: "**It's tasty, right?**",
          answer: "Вкусно е, нели?",
          hint: "вкусно + е + нели (right?).",
          after: "Нели at the end turns a statement into a nudge for agreement - the same tag you learned in module 1.",
          reviews: ["вкусно", "сум-present", "нели-tag"],
        },
        {
          type: "note",
          title: "уште - more, still",
          body:
            "**Уште** means 'more' when you're ordering and 'still' when you're describing:\n\n**Уште едно кафе, Ве молам.** - One more coffee, please.\n**Дали сакаш уште вино?** - Do you want more wine?",
          speak: ["Уште едно кафе, Ве молам.", "Дали сакаш уште вино?"],
          ru: "Уште is Russian ещё - same root, Macedonian shape.",
          bg: "Bulgarian още → Macedonian уште: the щ becomes шт, and the word grows a у in front.",
        },
        {
          type: "exercise",
          prompt: "To the waiter: **One more coffee, please.**",
          answer: "Уште едно кафе, Ве молам",
          accept: ["Уште едно кафе, молам"],
          hint: "уште + едно кафе + the polite please.",
          after: "Уште едно - 'still one', which is how Macedonian says 'one more'. And Ве молам, because it's the waiter.",
          reviews: ["уште", "numbers-1-5", "ве молам", "вие-polite"],
        },
        {
          type: "exercise",
          prompt: "Ask a friend: **Do you want more beer or more wine?**",
          answer: "Дали сакаш уште пиво или уште вино?",
          accept: ["Сакаш ли уште пиво или уште вино?", "Дали сакаш уште пиво или вино?"],
          hint: "дали + сакаш + уште пиво + или + уште вино.",
          after: "Friend, so сакаш. Или between the choices. And уште does the 'more' twice, or once - both are fine.",
          reviews: ["или-or", "уште", "пиво", "вино", "дали-question", "сакам"],
        },
        {
          type: "note",
          title: "ми - three encounters, one principle",
          body:
            "You've now seen **ми** in three disguises:\n\n**Мило ми е** - nice TO ME\n**колата ми** - MY car\n**ми се допаѓа** - it pleases ME\n\nSame small word, same job every time: pointing at you. Whether it comes out as 'to me' or 'my' depends on the sentence, but the underlying idea is one thing - *this concerns me*.",
          he: "Hebrew's ל- does a similar triple duty: נעים לי (pleasant to me), שלי (my), and the general dative לי. Same one-word-many-jobs logic.",
          reviews: ["dative-ми", "мило", "допаѓа-ми"],
        },
        {
          type: "choice",
          prompt: "**Ми се допаѓа кафето** means...",
          options: ["I like the coffee.", "My coffee is good.", "The coffee is mine."],
          correct: 0,
          after: "Ми се допаѓа = 'it pleases me' = I like it. The coffee is doing the pleasing - you're just receiving.",
          reviews: ["допаѓа-ми", "dative-ми"],
        },
        {
          type: "exercise",
          prompt: "**I like you, but I don't like the coffee.**",
          answer: "Ми се допаѓаш, но не ми се допаѓа кафето",
          accept: ["Ми се допаѓаш, но кафето не ми се допаѓа", "Ми се допаѓаш, ама не ми се допаѓа кафето"],
          hint: "For the person: ми се допаѓаш. For the coffee: не ми се допаѓа кафето.",
          after: "Two subjects, two verb endings: -ш for you, -а for the coffee. The ми never changed - you did the liking both times.",
          reviews: ["допаѓа-ми", "verb-а-group", "но-but", "definite-neuter", "не-negation", "clitic-placement"],
        },
        {
          type: "exercise",
          prompt: "**Why do you like her?**",
          answer: "Зошто ти се допаѓа таа?",
          accept: ["Зошто таа ти се допаѓа?"],
          hint: "зошто + ти се допаѓа + таа (she, as the subject).",
          after: "She is the one pleasing, so she's the subject - таа, not a short object pronoun. Зошто leads, and no дали is needed once a question word is there.",
          bg: "Bulgarian Защо я харесваш? makes 'her' the object; in Macedonian she is the subject of the pleasing: Зошто ти се допаѓа таа?",
          reviews: ["зошто-why", "допаѓа-ми", "pronoun-subject", "dative-ми"],
        },
      ],
    },
    {
      id: "m7l3",
      title: "Your first Macedonian story",
      subtitle: "Reading, understanding, celebrating",
      items: [
        {
          type: "note",
          title: "Read this - part one",
          body:
            "Everything below uses only what you've learned. Read it slowly - out loud if you can - then answer the questions.\n\n**Здраво! Се викам Ана и сум од Канада. Вчера патував во Скопје со мајка ми. Градот е голем и многу убав!**",
          speak: [
            "Здраво! Се викам Ана и сум од Канада.",
            "Вчера патував во Скопје со мајка ми.",
            "Градот е голем и многу убав!",
          ],
          reviews: ["викам", "past-в", "family-article-drop", "adj-agreement"],
        },
        {
          type: "choice",
          prompt: "**Ана е од...**",
          options: ["Канада", "Македонија", "Скопје"],
          correct: 0,
          after: "Сум од Канада - she says it in the second sentence, with the pronoun dropped.",
          reviews: ["од-from", "pronoun-drop"],
        },
        {
          type: "choice",
          prompt: "**Ана патува во Скопје со...**",
          options: ["мајка ѝ", "татко ѝ", "Марко"],
          correct: 0,
          after: "Ана says мајка ми - my mother. Talking about her, it becomes мајка ѝ - her mother. No article on family words either way.",
          reviews: ["family-article-drop", "dative-му-ѝ", "со-with"],
        },
        {
          type: "note",
          title: "Part two",
          body:
            "**Учам македонски, затоа што ја сакам Македонија. Зборувам малку, но разбирам многу. Сега сме во ресторан во центарот. Извинете, колку чини кафето? Едно кафе со млеко, Ве молам.**",
          speak: [
            "Учам македонски, затоа што ја сакам Македонија.",
            "Зборувам малку, но разбирам многу.",
            "Сега сме во ресторан во центарот.",
            "Извинете, колку чини кафето? Едно кафе со млеко, Ве молам.",
          ],
          reviews: ["зошто-why", "clitic-doubling", "колку-how-much", "чини"],
        },
        {
          type: "choice",
          prompt: "**Зошто Ана учи македонски?**",
          options: [
            "Затоа што ја сака Македонија.",
            "Затоа што работи во Скопје.",
            "Затоа што е студентка.",
          ],
          correct: 0,
          after: "Затоа што ја сака Македонија - and notice the ја: Macedonia is a definite object, so it gets doubled. That's the sound of real Macedonian.",
          reviews: ["зошто-why", "clitic-doubling", "сакам"],
        },
        {
          type: "choice",
          prompt: "**Што сака Ана?**",
          options: ["Кафе со млеко", "Чај", "Пиво"],
          correct: 0,
          after: "Едно кафе со млеко, Ве молам. Со = with, млеко = milk - both from module 4.",
          reviews: ["што-what", "со-with", "млеко"],
        },
        {
          type: "note",
          title: "One new word before the ending: секој",
          body:
            "**Секој** = every. It dresses for gender like an adjective: **секој ден** (every day), **секоја вечер** (every evening), **секое утро** (every morning).",
          speak: ["секој ден", "секоја вечер", "секое утро"],
          ru: "Russian says каждый день; Macedonian секој is closer to Russian всякий, with its first two letters swapped around.",
          bg: "Bulgarian всеки / всяка; Macedonian секој / секоја - the same word with в and с swapped, and -ој where Bulgarian has -и.",
          reviews: ["adj-agreement", "добар ден", "добра вечер", "добро утро"],
        },
        {
          type: "note",
          title: "Part three",
          body:
            "**Многу е вкусно! Мајка ми сака уште едно кафе. Секој ден зборувам со Марко од Битола. Утре ќе учам уште македонски. Македонија ми се допаѓа!**",
          speak: [
            "Многу е вкусно! Мајка ми сака уште едно кафе.",
            "Секој ден зборувам со Марко од Битола.",
            "Утре ќе учам уште македонски. Македонија ми се допаѓа!",
          ],
          reviews: ["вкусно", "уште", "секој", "future-ќе", "допаѓа-ми"],
        },
        {
          type: "choice",
          prompt: "**Што сака мајка ѝ?**",
          options: ["Уште едно кафе", "Уште едно пиво", "Вода"],
          correct: 0,
          after: "Мајка ми сака уште едно кафе - one more coffee. Уште did the 'more'.",
          reviews: ["уште", "dative-му-ѝ", "family-article-drop", "numbers-1-5"],
        },
        {
          type: "exercise",
          prompt: "Now you. Say: **Yesterday I traveled to Skopje.**",
          answer: "Вчера патував во Скопје",
          accept: ["Патував во Скопје вчера", "Вчера патував до Скопје"],
          hint: "Вчера + the past of патувам (патував) + во + Скопје.",
          after: "The -в past doing its job. Вчера патував - yesterday I traveled, no pronoun needed.",
          reviews: ["past-в", "вчера", "патувам", "во-in", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**I speak a little, but I understand a lot.**",
          answer: "Зборувам малку, но разбирам многу",
          accept: ["Зборувам малку, ама разбирам многу"],
          hint: "зборувам малку + но + разбирам многу.",
          after: "This is the most honest sentence in language learning. And the most hopeful.",
          reviews: ["но-but", "зборувам", "малку", "разбирам", "многу", "verb-а-group", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**I'm learning Macedonian because I love Macedonia.**",
          answer: "Учам македонски, затоа што ја сакам Македонија",
          accept: ["Учам македонски затоа што ја сакам Македонија"],
          hint: "учам македонски + затоа што + ја сакам Македонија (don't forget the doubling).",
          after: "You doubled Macedonia with ја - the mark of a sentence built the Macedonian way, not translated.",
          reviews: ["зошто-why", "clitic-doubling", "учам", "сакам", "македонски"],
        },
        {
          type: "exercise",
          prompt: "**Every day I speak with Marko.**",
          answer: "Секој ден зборувам со Марко",
          accept: ["Зборувам со Марко секој ден"],
          hint: "секој ден + зборувам + со Марко.",
          after: "Секој with a masculine ден. Со before the name. The verb in the middle, no pronoun - all yours.",
          reviews: ["секој", "добар ден", "зборувам", "со-with", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**Every evening I learn more Macedonian.**",
          answer: "Секоја вечер учам уште македонски",
          accept: ["Учам уште македонски секоја вечер"],
          hint: "вечер is feminine, so секој becomes секоја. Then учам + уште + македонски.",
          after: "Секоја for the feminine вечер - the same agreement you did with добра вечер. And уште slid in for 'more'.",
          reviews: ["секој", "добра вечер", "adj-agreement", "учам", "уште"],
        },
        {
          type: "exercise",
          prompt: "One sentence, and mean it: **I want to speak Macedonian every day.**",
          answer: "Сакам да зборувам македонски секој ден",
          accept: ["Секој ден сакам да зборувам македонски"],
          hint: "сакам + да зборувам + македонски + секој ден.",
          after: "**Секој ден.** You just said something real in Macedonian. That's not a drill - that's a decision.",
          reviews: ["да-subjunctive", "сакам", "зборувам", "македонски", "секој", "verb-а-group", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**Excuse me, I want two beers for us and one coffee for him, please.**",
          answer: "Извинете, сакам две пива за нас и едно кафе за него, Ве молам",
          accept: ["Извинете сакам две пива за нас и едно кафе за него Ве молам"],
          hint: "извинете + сакам + две пива за нас + и + едно кафе за него + the polite please.",
          after: "Две пива (neuter plural), за нас and за него (long pronouns after за), and Ве молам to close. Half the course in one order.",
          reviews: ["извинете", "numbers-1-5", "пиво", "noun-plural-basic", "за-for", "strong-pronouns", "и-conjunction", "ве молам"],
        },
        {
          type: "note",
          title: "Ајде - да зборуваме македонски!",
          body:
            "**Ајде** - 'come on, let's go!' - is the Balkans' favorite word of motion. And yes, it's why this app is called Ајде.\n\nYou can introduce yourself, want, have, ask, refuse, describe, like, time-travel between yesterday and tomorrow, be polite in two registers, and read a story in Macedonian. Eight modules ago you didn't know a single Cyrillic letter.\n\n**Ајде - да зборуваме македонски!** Наздравје!",
          speak: ["Ајде - да зборуваме македонски!", "Наздравје!"],
          he: "Ајде is the Balkan equivalent of יאללה - same word, same usage.",
          ru: "Russian давай does this job; colloquial айда is the same Turkish loan that gave the Balkans ајде.",
          bg: "Bulgarian хайде → Macedonian ајде: the й becomes ј, and the х at the front is gone.",
          reviews: ["ајде", "да-subjunctive", "наздравје"],
        },
        {
          type: "exercise",
          prompt: "**Come on! Good day! How are you?**",
          answer: "Ајде! Добар ден! Како сте?",
          accept: ["Ајде, добар ден, како сте?", "Ајде! Добар ден! Како си?"],
          hint: "ајде + добар ден + the polite 'how are you'.",
          after: "Ајде to get things moving, добар ден to be polite, како сте to mean it.",
          reviews: ["ајде", "добар ден", "како-how", "вие-polite", "сум-present"],
        },
        {
          type: "exercise",
          prompt: "**Every day I learn more Macedonian. Here you go - I understand everything!**",
          answer: "Секој ден учам уште македонски. Повелете - разбирам сѐ!",
          accept: ["Секој ден учам уште македонски, повелете, разбирам сѐ"],
          hint: "секој ден + учам + уште + македонски. Then the waiter's word, repurposed, and сѐ for 'everything'.",
          after: "Секој ден, уште, повелете, сѐ - four words from four different lessons, and you just put them in one breath. Ајде!",
          reviews: ["секој", "учам", "уште", "македонски", "повелете", "сѐ", "разбирам"],
        },
      ],
    },
  ],
};
