import type { Module } from "./types";

export const module6: Module = {
  id: "m6",
  title: "7. Asking and connecting",
  blurb:
    "Question words crack open conversations. Numbers get you fed. And a handful of small words turn your sentences into actual thought.",
  lessons: [
    {
      id: "m6l1",
      title: "What and who",
      subtitle: "што, кој, која - and a warm-up",
      items: [
        {
          type: "exercise",
          prompt: "Warm-up - nothing new yet. **Yesterday I worked.**",
          answer: "Вчера работев",
          accept: ["работев вчера", "јас вчера работев"],
          hint: "Past of работам: работев. Вчера = yesterday.",
          after: "Still here. The -ев past of the и-group is yours now.",
          reviews: ["past-и-е-group", "вчера", "работам", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**Tomorrow I will speak Macedonian.**",
          answer: "Утре ќе зборувам македонски",
          accept: ["ќе зборувам македонски утре"],
          hint: "Future = ќе + the present form.",
          after: "Утре swapped in for вчера, and ќе flipped the tense. Same sentence, different day.",
          reviews: ["утре", "future-ќе", "зборувам", "македонски", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**She was here, right?**",
          answer: "Таа беше тука, нели?",
          accept: ["беше тука, нели"],
          hint: "беше = was (he/she), нели = right?",
          after: "Past, future, tag questions - all still in your pocket. Now let's put them to work.",
          reviews: ["past-бев", "pronoun-subject", "тука", "нели-tag"],
        },
        {
          type: "note",
          title: "што - what",
          body:
            "Your first question word: **што** = what.\n\n- **Што сакаш?** - What do you want?\n- **Што е ова?** - What is this?\n\nYou already know **ова** (this) and **тоа** (that) from asking people's names. Now they get a question in front of them. No дали, no ли - the question word does the asking all by itself.",
          speak: ["Што сакаш?", "Што е ова?"],
          introduces: ["што-what"],
          he: "Like מה - it sits at the front and the sentence follows unchanged.",
          ru: "Што is exactly how Russian *pronounces* что. Macedonian just spells it the way it sounds.",
          bg: "Bulgarian asks какво; Macedonian asks што. In Macedonian какво means 'what kind of', so Какво е ова? asks what sort of thing it is, not what it is.",
        },
        {
          type: "exercise",
          prompt: "**What do you want?**",
          answer: "Што сакаш?",
          hint: "Што + the you-form of сакам.",
          after: "Што walked up to сакаш, the verb you already had, and the question wrote itself.",
          reviews: ["verb-а-group", "сакам", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**What is this?**",
          answer: "Што е ова?",
          hint: "Што е + ова.",
          after: "**Ова** points at everything within reach. **Тоа** points a little further away. You will use both constantly.",
          reviews: ["сум-present", "ова-this"],
        },
        {
          type: "exercise",
          prompt: "**What do you see?**",
          answer: "Што гледаш?",
          hint: "Што + гледаш (you see).",
          after: "Same slot, different verb. Any verb you know can follow што.",
          reviews: ["гледам", "verb-а-group", "pronoun-drop"],
        },
        {
          type: "note",
          title: "кој and која - who",
          body:
            "**Кој** = who. Like adjectives, it dresses for gender:\n\n- **Кој е тој?** - Who is he?\n- **Која е таа?** - Who is she?\n\nAsking about a man or a masculine noun - кој. About a woman - која. The same -/-а pattern you know from нов/нова.",
          speak: ["Кој е тој?", "Која е таа?"],
          introduces: ["кој-who"],
          he: "Hebrew מי is one word for everyone. Macedonian кој/која changes with the person you are asking about, the way adjectives do.",
          ru: "Кој is the cousin of кто and of который - it does both jobs: 'who' and 'which'.",
          bg: "Bulgarian кой/коя becomes кој/која - the й is written ј, and я is spelled ја.",
        },
        {
          type: "exercise",
          prompt: "**Who is he?**",
          answer: "Кој е тој?",
          hint: "Кој + е + тој.",
          after: "Кој took што's spot at the front. Same slot, new question word.",
          reviews: ["сум-present", "pronoun-subject"],
        },
        {
          type: "exercise",
          prompt: "**Who is she?**",
          answer: "Која е таа?",
          hint: "Feminine form: која.",
          after: "кој/која - you matched the question word to the person, exactly as you match нов/нова to a noun.",
          reviews: ["сум-present", "pronoun-subject", "adj-agreement"],
        },
        {
          type: "exercise",
          prompt: "Try the plural: **Who are they?** (кој becomes кои for a group)",
          answer: "Кои се тие?",
          hint: "кои + се + тие.",
          after: "Кои for a group - the same -и that makes студенти out of студент.",
          reviews: ["сум-present", "pronoun-subject", "plural-и"],
        },
        {
          type: "note",
          title: "This one here, that one there",
          body:
            "Supporting information - you will see it, you don't have to produce it. Next to the article **-то/-та/-от** (the), Macedonian has two more:\n\n- **-во/-ва/-ов** - this one, right here: **кафево** (this coffee here), **куќава** (this house here), **градов** (this city we're in).\n- **-но/-на/-он** - that one, over there: **кафено**, **куќана**, **градон**.\n\nThey are ова and тоа squeezed into the ending. Скопје speakers use them all the time; for now, just recognize them.",
          speak: ["кафето, кафево, кафено", "градот, градов, градон"],
          introduces: ["article-ов-он"],
          bg: "Bulgarian has one definite article; Macedonian has three sets. -ов/-он are extra - the plain -от/-та/-то still works everywhere Bulgarian uses -ът/-та/-то.",
        },
        {
          type: "choice",
          prompt: "A friend in Skopje says **Градов е убав.** They mean...",
          options: ["This city here is beautiful.", "That city over there is beautiful.", "A city is beautiful."],
          correct: 0,
          after: "-ов = this one here. They are talking about the city you are both standing in.",
          reviews: ["article-ов-он", "град", "убав"],
        },
        {
          type: "exercise",
          prompt: "**Where is my coffee?**",
          answer: "Каде е кафето ми?",
          hint: "каде (where) + е + кафето ми (my coffee).",
          after: "Каде was your first question word, back in Module 4. Што and кој just joined it at the front of the sentence.",
          reviews: ["dative-ми", "каде-where", "сум-present", "definite-neuter"],
        },
        {
          type: "exercise",
          prompt: "**Who sees us?**",
          answer: "Кој нѐ гледа?",
          hint: "кој (who) + нѐ (us, with the accent) + гледа (sees).",
          after: "The short pronoun still goes before the verb - кој just stands in front of both.",
          reviews: ["гледам", "object-pronoun-pl", "clitic-proclitic", "verb-а-group"],
        },
        {
          type: "exercise",
          prompt: "**Who is the doctor?**",
          answer: "Кој е докторот?",
          hint: "кој + е + доктор with 'the'. Masculine - which ending?",
          reviews: ["кој-who", "cognate-ор", "definite-masc", "сум-present"],
        },
        {
          type: "exercise",
          prompt: "A common way to ask someone's job: **What do you work?** (literally - it means 'what do you do?')",
          answer: "Што работиш?",
          hint: "Што + работиш.",
          after: "**Што работиш?** is how people ask what you do for a living. Answer with anything: Студент сум. Доктор сум.",
          reviews: ["што-what", "работам", "verb-и-group", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**I live in the beautiful city.**",
          answer: "Живеам во убавиот град",
          accept: ["јас живеам во убавиот град"],
          hint: "When 'the' rides the adjective, the noun stays bare.",
          reviews: ["живеам", "во-in", "adj-definite", "убав", "град"],
        },
      ],
    },
    {
      id: "m6l2",
      title: "Why and because",
      subtitle: "кога, зошто, затоа што, мислам, дека",
      items: [
        {
          type: "note",
          title: "кога - when",
          body:
            "**Кога** = when. Same pattern as што - question word up front, a normal sentence after it:\n\n**Кога работиш?** - When do you work?",
          speak: ["Кога работиш?"],
          introduces: ["кога-when"],
          ru: "Кога = когда minus the -да. The cognate parade continues: што≈что, кој≈кто, кога≈когда.",
        },
        {
          type: "exercise",
          prompt: "**When do you work?**",
          answer: "Кога работиш?",
          hint: "Кога + the you-form of работам.",
          after: "Кога slid into the front seat што and кој already broke in for you.",
          reviews: ["работам", "verb-и-group", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**When will she be here?**",
          answer: "Кога ќе биде тука?",
          accept: ["кога таа ќе биде тука", "кога ќе е тука", "кога таа ќе е тука"],
          hint: "Кога + the future of е (ќе биде).",
          after: "A question word plus the future tense. Everything you know keeps multiplying.",
          reviews: ["future-ќе", "тука", "сум"],
        },
        {
          type: "exercise",
          prompt: "**When does she work?**",
          answer: "Кога работи таа?",
          accept: ["кога таа работи"],
          hint: "Кога + работи (she works) + таа.",
          reviews: ["работам", "verb-и-group", "pronoun-subject"],
        },
        {
          type: "exercise",
          prompt: "**When will you go to Ohrid?**",
          answer: "Кога ќе одиш во Охрид?",
          accept: ["кога ти ќе одиш во охрид"],
          hint: "Кога + ќе одиш + во Охрид.",
          reviews: ["future-ќе", "одам", "во-in", "verb-и-group"],
        },
        {
          type: "note",
          title: "зошто and затоа што - a matched pair",
          body:
            "**Зошто** = why. **Затоа што** = because - literally 'for that, what', which is a fine description of an explanation. They share the што, so the question carries its answer inside it:\n\n- **Зошто учиш македонски?** - Why are you learning Macedonian?\n- **Затоа што сакам да патувам.** - Because I want to travel.",
          speak: ["Зошто учиш македонски?", "Затоа што сакам да патувам."],
          introduces: ["зошто-why"],
          he: "зошто/затоа што works like למה/כי - the question and its answer are a natural pair.",
          ru: "Зошто is за + што - 'for what', like Russian зачем's cousin за что. Затоа што = 'for that what'.",
          bg: "Bulgarian защо/защото becomes зошто/затоа што: щ turns into шт, and 'because' is two words.",
        },
        {
          type: "exercise",
          prompt: "**Why are you learning Macedonian?**",
          answer: "Зошто учиш македонски?",
          hint: "Зошто + учиш + македонски.",
          after: "Зошто, then the plain sentence you would have said anyway. No twist required.",
          reviews: ["учам", "verb-и-group", "македонски", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "Answer: **Because I want to travel.**",
          answer: "Затоа што сакам да патувам",
          hint: "Затоа што + сакам да патувам.",
          after: "Затоа што in front, and the да-construction from Module 2 did the rest.",
          reviews: ["сакам", "да-subjunctive", "патувам", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**Why must you work today?**",
          answer: "Зошто треба да работиш денес?",
          hint: "зошто (why) + треба да работиш (you must work) + денес (today).",
          reviews: ["треба-да", "работам", "verb-и-group", "денес"],
        },
        {
          type: "exercise",
          prompt: "**Because I can't work tomorrow.**",
          answer: "Затоа што не можам да работам утре",
          hint: "затоа што + не можам да работам (I can't work) + утре.",
          reviews: ["не-negation", "можам-conjugation", "да-subjunctive", "работам", "утре"],
        },
        {
          type: "exercise",
          prompt: "**Why are you waiting for Marko?**",
          answer: "Зошто го чекаш Марко?",
          hint: "A name is a definite object - say it twice: го чекаш Марко.",
          after: "Зошто up front, then го before чекаш, then Марко. The doubling from Module 4 survives a question word just fine.",
          reviews: ["clitic-doubling", "чекам", "object-pronoun-sg", "clitic-proclitic"],
        },
        {
          type: "note",
          title: "мислам - I think",
          body:
            "New verb: **мислам** = I think. И-group, like учам and работам: мислам, мисл**иш**, мисл**и**.\n\n**Не мислам.** - I don't think so.\n\nSoon it will get something to think about. First, just get it under your fingers.",
          speak: ["Не мислам."],
          ru: "Мислам keeps the old Slavic root of мысль (a thought). Russian says думаю for the everyday verb.",
        },
        {
          type: "exercise",
          prompt: "**I don't think so.**",
          answer: "Не мислам",
          hint: "не + мислам.",
          after: "Мислам settled. Now let's give it a thought to hold.",
          reviews: ["не-negation", "verb-и-group", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you think so?**",
          answer: "Мислиш ли?",
          accept: ["дали мислиш"],
          hint: "мислиш (you think) + ли, or дали in front.",
          reviews: ["ли-question", "дали-question", "verb-и-group", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**She doesn't think so.**",
          answer: "Таа не мисли",
          accept: ["не мисли"],
          hint: "таа + не + мисли (she thinks).",
          after: "мисли - the и-group he/she form, same as работи and учи.",
          reviews: ["не-negation", "pronoun-subject", "verb-и-group"],
        },
        {
          type: "note",
          title: "дека - that (the connector)",
          body:
            "**Дека** = that - the connecting word, not the pointing word. It glues a thought to the verb that thinks it:\n\n**Мислам дека зборуваш добро.** - I think that you speak well.\n\nEnglish drops 'that' half the time. Macedonian keeps **дека** every time. No comma needed before it.",
          speak: ["Мислам дека зборуваш добро."],
          introduces: ["дека-that"],
          he: "Hebrew ש does this job (אני חושב ש...). Дека is the same glue, standing as its own word.",
          ru: "Russian uses что here (думаю, что...). Дека is a different word entirely - don't reach for што.",
          bg: "Bulgarian says че with a comma before it (Мисля, че...); Macedonian says дека, usually without a comma (Мислам дека...).",
        },
        {
          type: "exercise",
          prompt: "**I think that you speak well.**",
          answer: "Мислам дека зборуваш добро",
          hint: "Мислам дека + зборуваш + добро.",
          after: "Мислам opens it, дека links it, and the rest is a sentence you already knew cold.",
          reviews: ["зборувам", "verb-а-group", "добро", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**I think that she is here.**",
          answer: "Мислам дека таа е тука",
          accept: ["мислам дека е тука"],
          hint: "Мислам дека + таа е тука.",
          after: "Same дека, same job - reporting something you take to be a fact.",
          reviews: ["сум-present", "тука", "pronoun-subject"],
        },
        {
          type: "exercise",
          prompt: "**I think that I understand them.**",
          answer: "Мислам дека ги разбирам",
          hint: "Мислам дека + ги (them) before разбирам.",
          after: "Ги stayed right before its verb. Дека doesn't disturb the short pronouns.",
          reviews: ["дека-that", "object-pronoun-pl", "clitic-proclitic", "разбирам"],
        },
        {
          type: "exercise",
          prompt: "**Why does he want to work here?**",
          answer: "Зошто тој сака да работи тука?",
          accept: ["зошто сака да работи тука"],
          hint: "Зошто + тој сака да работи + тука.",
          after: "A question word plus the да-construction. These pieces snap together beautifully.",
          reviews: ["сакам", "verb-а-group", "да-subjunctive", "работам", "verb-и-group", "тука", "pronoun-subject"],
        },
        {
          type: "exercise",
          prompt: "**She won't speak Macedonian.** (negative future)",
          answer: "Таа нема да зборува македонски",
          accept: ["нема да зборува македонски"],
          hint: "Negative future: нема да + the present form.",
          reviews: ["future-neg", "pronoun-subject", "зборувам", "verb-а-group", "македонски"],
        },
        {
          type: "exercise",
          prompt: "**Hello! Why are you here?**",
          answer: "Здраво! Зошто си тука?",
          accept: ["здраво, зошто си тука"],
          hint: "здраво = hello. зошто = why.",
          reviews: ["здраво", "сум-present", "тука"],
        },
        {
          type: "exercise",
          prompt: "**The woman doesn't understand.**",
          answer: "Жената не разбира",
          hint: "Feminine noun + 'the' - which ending?",
          reviews: ["жена", "definite-fem", "разбирам", "verb-а-group", "не-negation"],
        },
        {
          type: "exercise",
          prompt: "**I want the bill. There is no bill.**",
          answer: "Ја сакам сметката. Нема сметка.",
          hint: "The bill is definite - double it with ја. Then нема = there isn't.",
          after: "Ја сакам сметката - doubled, because 'the bill' is a specific one. Нема сметка - no doubling, because there isn't one to point at.",
          reviews: ["clitic-doubling", "сакам", "сметка", "definite-fem", "има-existential"],
        },
        {
          type: "exercise",
          prompt: "**Nice to meet you! Good day!**",
          answer: "Мило ми е! Добар ден!",
          accept: ["драго ми е! добар ден!"],
          hint: "The set phrase + the daytime greeting.",
          reviews: ["мило", "dative-ми", "добар ден", "добар"],
        },
        {
          type: "exercise",
          prompt: "**When do we work?**",
          answer: "Кога работиме?",
          hint: "кога = when. We-form of работам.",
          reviews: ["кога-when", "работам", "verb-и-group", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**My father doesn't live here.**",
          answer: "Татко ми не живее тука",
          hint: "татко ми = my father (no article on family). не before the verb.",
          reviews: ["татко", "family-article-drop", "не-negation", "живеам", "verb-е-group", "тука"],
        },
      ],
    },
    {
      id: "m6l3",
      title: "Connecting thoughts",
      subtitle: "а, или, знам, сѐ, можеби",
      items: [
        {
          type: "note",
          title: "а - the other 'but'",
          body:
            "You know **но** ('but'). Macedonian has a softer contrast word: **а** - more like 'whereas' or 'and on the other hand':\n\n**Јас зборувам македонски, а таа зборува англиски.** - I speak Macedonian, and she speaks English.\n\n**Но** is for surprises ('I tried, but it didn't work'). **А** just shows two sides of the same picture.",
          speak: ["Јас зборувам македонски, а таа зборува англиски."],
          introduces: ["а-contrast"],
          ru: "This is exactly Russian а - same feel, same position, same comma. Free of charge.",
        },
        {
          type: "exercise",
          prompt: "**I live here, and she lives there.** (contrast - use а)",
          answer: "Јас живеам тука, а таа живее таму",
          accept: ["живеам тука, а таа живее таму"],
          hint: "...тука, а таа живее таму.",
          after: "Two people, two places, one а sitting between them showing the contrast.",
          reviews: ["живеам", "тука", "таму", "pronoun-subject", "verb-е-group"],
        },
        {
          type: "exercise",
          prompt: "**He works, and she doesn't.** (contrast - use а)",
          answer: "Тој работи, а таа не работи",
          hint: "...а таа не работи.",
          reviews: ["работам", "не-negation", "pronoun-subject", "verb-и-group"],
        },
        {
          type: "exercise",
          prompt: "**I speak Macedonian, and you speak English.** (contrast - use а)",
          answer: "Јас зборувам македонски, а ти зборуваш англиски",
          accept: ["зборувам македонски, а ти зборуваш англиски"],
          hint: "...а ти зборуваш + англиски.",
          reviews: ["зборувам", "македонски", "англиски", "pronoun-subject", "verb-а-group"],
        },
        {
          type: "note",
          title: "или - or",
          body:
            "**Или** = or. Simple, essential:\n\n**Чај или кафе?** - Tea or coffee?",
          speak: ["Чај или кафе?"],
          introduces: ["или-or"],
          he: "Или is או. Same job, same spot between the two options.",
          ru: "Identical to Russian или.",
        },
        {
          type: "exercise",
          prompt: "**Tea or coffee?**",
          answer: "Чај или кафе?",
          hint: "Чај + или + кафе.",
          after: "Или between two nouns you already own. That's the entire lesson.",
          reviews: ["чај", "кафе"],
        },
        {
          type: "exercise",
          prompt: "**Today or tomorrow?**",
          answer: "Денес или утре?",
          hint: "Денес + или + утре.",
          after: "Same или, different pair of words. The construction doesn't care what you plug in.",
          reviews: ["денес", "утре"],
        },
        {
          type: "exercise",
          prompt: "**Do you want tea or coffee?**",
          answer: "Сакаш чај или кафе?",
          accept: ["дали сакаш чај или кафе", "сакаш ли чај или кафе"],
          hint: "Сакаш + чај + или + кафе. Дали in front is fine too.",
          after: "With a choice on the table, the rising tone does the asking - дали is optional here.",
          reviews: ["сакам", "чај", "verb-а-group", "дали-question"],
        },
        {
          type: "note",
          title: "знам - I know",
          body:
            "New verb: **знам** = I know. It's an е-group verb, like можам and живеам: знам, зна**е**ш, зна**е**, зна**е**ме, зна**е**те, знаат.\n\n**Не знам.** - I don't know. Second most useful sentence in any language.",
          speak: ["Не знам."],
          ru: "Знам = знаю, same root; the you-form знаеш is Russian знаешь without the soft sign.",
        },
        {
          type: "exercise",
          prompt: "**I don't know.**",
          answer: "Не знам",
          hint: "не + знам.",
          after: "Не знам - you will use it daily, and now you own it.",
          reviews: ["не-negation", "verb-м-first-person"],
        },
        {
          type: "exercise",
          prompt: "**She knows.** (she-form of знам)",
          answer: "Таа знае",
          accept: ["знае"],
          hint: "знам → знаеш → знае (he/she).",
          after: "Знае - that е stepping in, just like може and живее.",
          reviews: ["pronoun-subject", "verb-е-group"],
        },
        {
          type: "exercise",
          prompt: "Ask: **Do you know?**",
          answer: "Знаеш ли?",
          accept: ["дали знаеш"],
          hint: "знаеш (you know) + ли.",
          reviews: ["ли-question", "verb-е-group"],
        },
        {
          type: "exercise",
          prompt: "**Do you know Marko?**",
          answer: "Го знаеш ли Марко?",
          accept: ["дали го знаеш марко"],
          hint: "Marko is definite - го before знаеш, then ли, then Марко.",
          after: "Го знаеш ли Марко - the doubling holds, and ли slips in right after the verb.",
          reviews: ["clitic-doubling", "object-pronoun-sg", "ли-question", "verb-е-group"],
        },
        {
          type: "note",
          title: "сѐ - everything",
          body:
            "**Сѐ** = everything. Notice the little accent mark: it tells сѐ (everything) apart from **се** (the се of се викам). The checker doesn't mind if you skip it, but writers keep it.\n\n**Знам сѐ.** - I know everything.",
          speak: ["Знам сѐ."],
          he: "Сѐ is הכל - one word for 'everything'.",
          ru: "Сѐ = всё, minus the в. Same word underneath.",
          bg: "Bulgarian всичко is a long word; Macedonian сѐ is one syllable, written with an accent to distinguish it from reflexive се.",
        },
        {
          type: "exercise",
          prompt: "**I know everything.**",
          answer: "Знам сѐ",
          hint: "знам + сѐ.",
          after: "Знам сѐ - two syllables, big claim.",
          reviews: ["знам", "сѐ"],
        },
        {
          type: "exercise",
          prompt: "**I don't understand everything.**",
          answer: "Не разбирам сѐ",
          hint: "не + разбирам + сѐ.",
          reviews: ["не-negation", "разбирам", "сѐ", "verb-а-group"],
        },
        {
          type: "note",
          title: "дека reports, да wishes",
          body:
            "You now have two small words that link verbs. Here's how they divide the work:\n\n- **дека** reports a fact: Знам **дека** таа е тука. (I know that she is here.)\n- **да** drives a wish: Сакам **да** е тука. (I want her to be here.)\n\nAfter thinking and knowing - **дека**. After wanting and needing - **да**. You've been using да since Module 2. Now you can see why дека needed its own entrance.",
          speak: ["Знам дека таа е тука.", "Сакам да е тука."],
          he: "Hebrew uses ש for both (יודע ש..., רוצה ש...). Macedonian splits the job: дека for facts, да for wishes.",
          reviews: ["дека-that", "да-subjunctive"],
        },
        {
          type: "exercise",
          prompt: "**I know that she is here.**",
          answer: "Знам дека таа е тука",
          accept: ["знам дека е тука"],
          hint: "Знам дека + таа е тука.",
          after: "Знам instead of мислам, but дека still does the same linking work.",
          reviews: ["сум-present", "тука", "pronoun-subject", "дека-that"],
        },
        {
          type: "exercise",
          prompt: "**I know that you don't understand me.**",
          answer: "Знам дека не ме разбираш",
          hint: "знам (I know) + дека (that) + не ме разбираш (you don't understand me).",
          after: "Не, then ме, then the verb - the order from Module 4, tucked inside a дека clause.",
          reviews: ["clitic-placement", "не-negation", "object-pronoun-sg", "разбирам"],
        },
        {
          type: "exercise",
          prompt: "**I think that you speak well, but I don't understand everything.**",
          answer: "Мислам дека зборуваш добро, но не разбирам сѐ",
          hint: "Мислам дека ..., но не разбирам + сѐ.",
          after: "Дека, но, не - three words of glue holding together things you already knew. That's how real speech starts to form.",
          reviews: ["зборувам", "добро", "но-but", "не-negation", "разбирам", "сѐ"],
        },
        {
          type: "note",
          title: "можеби - maybe",
          body:
            "**Можеби** = maybe. One word, built from можам: 'it can be'. The most Balkan of answers.\n\n**Можеби утре.** - Maybe tomorrow.",
          speak: ["Можеби утре."],
          introduces: ["можеби"],
          he: "Можеби is אולי - drop it at the front and hedge the whole sentence.",
          ru: "Можеби is может быть squeezed into one word.",
          bg: "Bulgarian writes може би as two words; Macedonian writes можеби as one, and stresses it МОжеби.",
        },
        {
          type: "exercise",
          prompt: "**Maybe tomorrow.**",
          answer: "Можеби утре",
          hint: "Можеби + утре.",
          after: "Можеби plus a time word - the shortest hedge in the language.",
          reviews: ["утре"],
        },
        {
          type: "exercise",
          prompt: "**I think that maybe she knows.**",
          answer: "Мислам дека можеби таа знае",
          accept: ["мислам дека можеби знае"],
          hint: "Мислам дека можеби + таа знае.",
          after: "Four layers - мислам + дека + можеби + знае - in one sentence. You're chaining thoughts like a real speaker.",
          reviews: ["pronoun-subject", "дека-that", "мислам", "знам"],
        },
        {
          type: "exercise",
          prompt: "**Maybe she doesn't know.**",
          answer: "Можеби таа не знае",
          accept: ["можеби не знае"],
          hint: "можеби + таа + не знае.",
          reviews: ["не-negation", "pronoun-subject", "знам"],
        },
        {
          type: "exercise",
          prompt: "**The man works, and the woman doesn't work.**",
          answer: "Мажот работи, а жената не работи",
          hint: "маж + -от = мажот. жена + -та = жената. а = whereas.",
          reviews: ["маж", "definite-masc", "жена", "definite-fem", "а-contrast", "работам", "не-negation"],
        },
        {
          type: "exercise",
          prompt: "**I don't have bread, but I have water.**",
          answer: "Немам леб, но имам вода",
          hint: "немам (fused negation of имам) + леб. Surprise-contrast, so но.",
          reviews: ["немам-fused", "леб", "имам", "вода", "но-but", "pronoun-drop"],
        },
        {
          type: "exercise",
          prompt: "**Maybe the sea is there.**",
          answer: "Можеби морето е таму",
          hint: "море + -то = морето.",
          reviews: ["можеби", "море", "definite-neuter", "сум-present", "таму"],
        },
        {
          type: "exercise",
          prompt: "**I know that she won't work tomorrow.**",
          answer: "Знам дека таа нема да работи утре",
          accept: ["знам дека нема да работи утре"],
          hint: "знам + дека + the negative future.",
          reviews: ["знам", "дека-that", "future-neg", "работам", "утре", "pronoun-subject"],
        },
        {
          type: "exercise",
          prompt: "**I was in Skopje, and she was in Ohrid.**",
          answer: "Јас бев во Скопје, а таа беше во Охрид",
          accept: ["бев во скопје, а таа беше во охрид"],
          hint: "бев (I was), беше (she was). а = whereas.",
          reviews: ["past-бев", "во-in", "а-contrast", "pronoun-subject"],
        },
        {
          type: "exercise",
          prompt: "**Who knows?**",
          answer: "Кој знае?",
          hint: "кој + знае.",
          after: "Кој знае - the Macedonian shrug. Two words, endless uses.",
          reviews: ["кој-who", "знам", "verb-е-group"],
        },
        {
          type: "exercise",
          prompt: "**My father lives in the city with my mother.**",
          answer: "Татко ми живее во градот со мајка ми",
          hint: "во = in, со = with. Family words drop the article, градот keeps it.",
          reviews: ["татко", "во-in", "град", "definite-masc", "со-with", "мајка", "family-article-drop", "живеам"],
        },
      ],
    },
    {
      id: "m6l4",
      title: "Numbers and counting",
      subtitle: "колку, еден-пет, две кафиња",
      items: [
        {
          type: "note",
          title: "колку - how much / how many",
          body:
            "**Колку** = how much / how many. One word does both jobs.\n\nNew verb: **чини** = it costs. You'll mostly hear just this one form.\n\n**Колку чини?** - How much does it cost? The survival question.",
          speak: ["Колку чини?"],
          introduces: ["колку-how-much"],
          ru: "Колку = сколько, same root. But чини is a false friend: Russian чинить means to repair. Here it means 'costs'.",
          bg: "Bulgarian колко becomes колку, and 'costs' is чини, not струва. Струва exists in Macedonian but sounds bookish.",
        },
        {
          type: "exercise",
          prompt: "**How much does it cost?**",
          answer: "Колку чини?",
          hint: "Колку + чини.",
          after: "You'll use this one constantly. Asking it in Macedonian beats pointing and looking hopeful.",
          reviews: ["колку-how-much", "чини"],
        },
        {
          type: "exercise",
          prompt: "**How much does the coffee cost?**",
          answer: "Колку чини кафето?",
          hint: "Колку + чини + кафето (the coffee).",
          after: "Кафето with its -то - the thing has a price, so it's definite.",
          reviews: ["колку-how-much", "чини", "definite-neuter"],
        },
        {
          type: "note",
          title: "едно - one (for a coffee)",
          body:
            "Your first number, in the form you'll use most:\n\n**Едно кафе, Ве молам.** - One coffee, please.\n\n**Едно** is 'one' for neuter nouns - кафе, пиво, вино. All the drinks, conveniently.",
          speak: ["Едно кафе, Ве молам."],
          introduces: ["numbers-1-5"],
        },
        {
          type: "exercise",
          prompt: "**One coffee, please.**",
          answer: "Едно кафе, Ве молам",
          accept: ["едно кафе, молам"],
          hint: "Едно + кафе, + Ве молам.",
          after: "Едно кафе - you just ordered your first coffee in Macedonian.",
          reviews: ["ве молам", "кафе"],
        },
        {
          type: "exercise",
          prompt: "**One beer, please.**",
          answer: "Едно пиво, Ве молам",
          accept: ["едно пиво, молам"],
          hint: "Пиво is neuter, like кафе - so едно again.",
          after: "Едно пиво - neuter, so the same едно. Two orders down, no new thinking needed.",
          reviews: ["пиво", "noun-gender", "ве молам"],
        },
        {
          type: "exercise",
          prompt: "**How much does one coffee cost?**",
          answer: "Колку чини едно кафе?",
          hint: "Колку чини + едно кафе.",
          reviews: ["колку-how-much", "чини", "кафе"],
        },
        {
          type: "note",
          title: "една and еден - one dresses for gender",
          body:
            "Like adjectives, 'one' matches the noun:\n\n- **едно** кафе (n)\n- **една** вода (f) - one water\n- **еден** чај (m) - one tea\n\nSame -/-а/-о pattern as добар/добра/добро, applied to a number.",
          speak: ["една вода", "еден чај", "едно кафе"],
          he: "Same idea as אחד/אחת - the low numbers carry gender.",
          ru: "Один/одна/одно - the same three-way split, and еден keeps its д just like один does.",
        },
        {
          type: "exercise",
          prompt: "**One water, please.**",
          answer: "Една вода, Ве молам",
          accept: ["една вода, молам"],
          hint: "Вода is feminine - which form of 'one'?",
          after: "Една вода - feminine form, matching вода's -а ending. Gender keeps being predictable.",
          reviews: ["вода", "noun-gender", "ве молам"],
        },
        {
          type: "exercise",
          prompt: "**One tea, please.**",
          answer: "Еден чај, Ве молам",
          accept: ["еден чај, молам"],
          hint: "Чај ends in a consonant - masculine.",
          after: "Еден for masculine - the bare form, like добар with no ending.",
          reviews: ["чај", "noun-gender", "ве молам"],
        },
        {
          type: "exercise",
          prompt: "**One tea and one water, please.**",
          answer: "Еден чај и една вода, Ве молам",
          accept: ["еден чај и една вода, молам"],
          hint: "Masculine: еден чај. Feminine: една вода.",
          reviews: ["noun-gender", "чај", "вода", "и-conjunction", "ве молам"],
        },
        {
          type: "note",
          title: "More than one: the drinks in plural",
          body:
            "To order more than one, the noun goes plural. For the neuter drinks:\n\n- кафе → **кафиња** (coffees)\n- пиво → **пива** (beers)\n- вино → **вина** (wines)\n\nNeuter words in -о just swap it for -а. Neuter words in -е grow the ending **-иња**. You'll meet the other genders in a moment.",
          speak: ["кафе, кафиња", "пиво, пива", "вино, вина"],
          introduces: ["noun-plural-basic"],
          bg: "Bulgarian кафета becomes кафиња - the -иња plural is a Macedonian signature (also мориња, времиња).",
        },
        {
          type: "exercise",
          prompt: "**The beers are good.**",
          answer: "Пивата се добри",
          hint: "пива + -та (the) + се + добри (plural).",
          after: "Пивата - the plural takes -та for 'the', and добри matched it. Plural is plural all the way down the sentence.",
          reviews: ["пиво", "adj-agreement", "добар", "сум-present"],
        },
        {
          type: "exercise",
          prompt: "**The wines are from Macedonia.**",
          answer: "Вината се од Македонија",
          hint: "вино → вина, then -та.",
          reviews: ["вино", "од-from", "сум-present"],
        },
        {
          type: "note",
          title: "две - two",
          body:
            "**Две** = two, for feminine and neuter nouns - which covers every drink on the menu:\n\n**Две кафиња, Ве молам.** - Two coffees, please.\n**Две пива.** - Two beers.\n**Две води.** - Two waters (вода → води, the feminine plural in -и).",
          speak: ["Две кафиња, Ве молам.", "Две пива.", "Две води."],
          he: "Like שתיים before feminine nouns - две is the two that goes with the -а and -о words.",
        },
        {
          type: "exercise",
          prompt: "**two coffees**",
          answer: "две кафиња",
          hint: "кафе is neuter, so две. Plural: кафе → кафиња.",
          after: "Две matched кафе's gender, and кафиња carried its own plural along for the ride.",
          reviews: ["кафе", "noun-plural-basic"],
        },
        {
          type: "exercise",
          prompt: "**Two beers, please.**",
          answer: "Две пива, Ве молам",
          accept: ["две пива, молам"],
          hint: "Две + пива, + Ве молам.",
          after: "Две пива - your second order, still effortless.",
          reviews: ["пиво", "noun-plural-basic", "ве молам"],
        },
        {
          type: "exercise",
          prompt: "**One coffee and two beers, please.**",
          answer: "Едно кафе и две пива, Ве молам",
          accept: ["едно кафе и две пива, молам"],
          hint: "Едно кафе + и + две пива, + Ве молам.",
          reviews: ["кафе", "пиво", "и-conjunction", "ве молам"],
        },
        {
          type: "note",
          title: "два - two for masculine",
          body:
            "For masculine nouns, two is **два**:\n\n**два студенти** - two students\n**два туристи** - two tourists\n\nThe plural is the -и you've known since Module 1. Два for the consonant words, две for everything else.",
          speak: ["два студенти", "два туристи"],
          bg: "Bulgarian switches to a special counted form after numbers (два града, два студента); Macedonian just uses the ordinary plural: два студенти, пет хотели.",
        },
        {
          type: "exercise",
          prompt: "**There are two students in the hotel.**",
          answer: "Има два студенти во хотелот",
          accept: ["во хотелот има два студенти"],
          hint: "има (there are) + два студенти + во хотелот.",
          after: "Два for masculine студент, and the -и plural you've had since Module 1 did the rest.",
          reviews: ["има-existential", "plural-и", "во-in", "definite-masc"],
        },
        {
          type: "exercise",
          prompt: "**Two tourists and two coffees.**",
          answer: "Два туристи и две кафиња",
          hint: "два for masculine турист, две for neuter кафе.",
          reviews: ["noun-gender", "и-conjunction", "noun-plural-basic"],
        },
        {
          type: "note",
          title: "три, четири, пет - three, four, five",
          body:
            "Three more numbers finish the set:\n\n**три** - three\n**четири** - four\n**пет** - five\n\nThese never change for gender. They just sit in front of the plural noun.",
          speak: ["три, четири, пет"],
          ru: "Три, четыре, пять - the same numbers with the soft sign gone from пет.",
        },
        {
          type: "exercise",
          prompt: "**Three coffees, please.**",
          answer: "Три кафиња, Ве молам",
          accept: ["три кафиња, молам"],
          hint: "Три + кафиња, + Ве молам.",
          after: "Три doesn't change - it sits unchanged in front of whatever plural you need.",
          reviews: ["кафе", "noun-plural-basic", "ве молам"],
        },
        {
          type: "exercise",
          prompt: "Count from one to five.",
          answer: "еден, два, три, четири, пет",
          accept: ["едно, две, три, четири, пет", "една, две, три, четири, пет"],
          hint: "еден, два, три, четири, пет.",
          after: "Five numbers under your belt - and the first two you can dress for any noun.",
          reviews: ["numbers-1-5"],
        },
        {
          type: "note",
          title: "Plurals for the consonant words",
          body:
            "Masculine nouns take **-и** (хотели, студенти). Short one-syllable ones grow **-ови**: град → **градови**, леб → **лебови**. And маж → **мажи**.\n\n**Скопје и Охрид се убави градови.** - Skopje and Ohrid are beautiful cities.\n\nFeminine nouns in -а also take -и: жена → **жени**, куќа → **куќи**, кола → **коли**.",
          speak: ["Скопје и Охрид се убави градови.", "жени, куќи, коли"],
          ru: "Градови is Russian города with the Macedonian -ови; the -ови plural is the Russian -овья/-овья family (сыновья, братья) turned regular.",
          bg: "Same -ове idea as Bulgarian градове, but spelled -ови: градови, лебови.",
        },
        {
          type: "exercise",
          prompt: "**Skopje and Ohrid are beautiful cities.**",
          answer: "Скопје и Охрид се убави градови",
          hint: "град → градови (one-syllable masculine). убави matches the plural.",
          after: "Градови - the -ови plural for a short masculine noun, and убави agreed with it.",
          reviews: ["град", "adj-agreement", "убав", "сум-present"],
        },
        {
          type: "exercise",
          prompt: "**There are five hotels in the city.**",
          answer: "Во градот има пет хотели",
          accept: ["има пет хотели во градот"],
          hint: "во градот + има + пет хотели.",
          reviews: ["има-existential", "во-in", "definite-masc", "хотел"],
        },
        {
          type: "exercise",
          prompt: "Order at a cafe: **Can I get two coffees and one tea, please?**",
          answer: "Може ли две кафиња и еден чај, Ве молам?",
          accept: ["две кафиња и еден чај, ве молам"],
          hint: "Може ли + две кафиња + и + еден чај, + Ве молам.",
          after: "That sentence works exactly as written in any cafe in Skopje. Not textbook Macedonian - real Macedonian.",
          reviews: ["може-ли-polite", "чај", "и-conjunction", "ве молам"],
        },
        {
          type: "exercise",
          prompt: "**How much do three coffees cost?** (they-form of чини: чинат)",
          answer: "Колку чинат три кафиња?",
          hint: "Колку + чинат (plural) + три кафиња.",
          after: "Чинат - the same -ат they-ending you know from работат and учат.",
          reviews: ["колку-how-much", "чини", "verb-и-group"],
        },
        {
          type: "exercise",
          prompt: "**I want five beers and two coffees.**",
          answer: "Сакам пет пива и две кафиња",
          hint: "пет + пива, две + кафиња.",
          reviews: ["numbers-1-5", "пиво", "noun-plural-basic", "сакам", "и-conjunction"],
        },
        {
          type: "exercise",
          prompt: "**How many hotels are there in Ohrid?**",
          answer: "Колку хотели има во Охрид?",
          accept: ["колку хотели има во охрид"],
          hint: "колку + хотели (plural) + има + во Охрид.",
          after: "Колку with a plural noun = how many. Same word, no extra work.",
          reviews: ["колку-how-much", "има-existential", "во-in", "хотел"],
        },
        {
          type: "note",
          title: "Five numbers, infinite orders",
          body:
            "You've used every piece. Here it is in one place:\n\n- **еден / една / едно** - one (m / f / n)\n- **два / две** - two (m / f+n)\n- **три, четири, пет** - three, four, five (no gender)\n\nPlurals: masculine -и (хотели), short ones -ови (градови); feminine -и (води, жени); neuter -о → -а (пива), -е → -иња (кафиња).\n\n**Колку**, the numbers and the plurals - that's your ordering toolkit. The waiter does the hard part: bringing it.",
          reviews: ["numbers-1-5", "noun-plural-basic"],
        },
      ],
    },
    {
      id: "m6l5",
      title: "At the cafe",
      subtitle: "за, до, мене, тебе, извинете, повелете",
      items: [
        {
          type: "note",
          title: "за and мене - for me",
          body:
            "**За** = for (and sometimes 'about'). After a preposition, a pronoun puts on its long form. First one:\n\n- **мене** - me (the long form of ме)\n\n**За мене кафе, Ве молам.** - Coffee for me, please.\n\nYou met мене briefly with doubling (Мене ме разбираш?). After за it stands alone.",
          speak: ["За мене кафе, Ве молам."],
          introduces: ["за-for", "strong-pronouns"],
          he: "Hebrew fuses the pronoun into the preposition (בשבילי). Macedonian keeps them apart: за + мене.",
          ru: "Мене is Russian меня with the vowel shifted - the same long form you'd use after для.",
          bg: "Bulgarian shortens to мен (за мен); Macedonian keeps the full мене (за мене).",
        },
        {
          type: "exercise",
          prompt: "**Coffee for me, please.**",
          answer: "За мене кафе, Ве молам",
          accept: ["кафе за мене, ве молам", "за мене кафе, молам"],
          hint: "За мене + кафе, + Ве молам.",
          after: "За мене up front, кафе and Ве молам doing what they always do.",
          reviews: ["за-for", "strong-pronouns", "ве молам"],
        },
        {
          type: "exercise",
          prompt: "**The beer is for me.**",
          answer: "Пивото е за мене",
          hint: "пивото (the beer) + е + за мене.",
          reviews: ["пиво", "definite-neuter", "сум-present", "за-for", "strong-pronouns"],
        },
        {
          type: "exercise",
          prompt: "**This is for me, right?**",
          answer: "Ова е за мене, нели?",
          hint: "Ова е за мене + нели.",
          reviews: ["ова-this", "сум-present", "за-for", "strong-pronouns", "нели-tag"],
        },
        {
          type: "note",
          title: "тебе - you (long form)",
          body:
            "The long form of те (you) is **тебе**. Same job as мене, for the other person.\n\n**Ова е за тебе.** - This is for you.",
          speak: ["Ова е за тебе."],
          ru: "Тебе looks exactly like Russian тебе, though here it does the job of тебя after prepositions.",
          bg: "Bulgarian за теб; Macedonian за тебе.",
        },
        {
          type: "exercise",
          prompt: "**This is for you.**",
          answer: "Ова е за тебе",
          hint: "Ова е за + the long form of 'you'.",
          after: "За pulled тебе into its long form, just like it did with мене.",
          reviews: ["ова-this", "сум-present", "за-for", "strong-pronouns"],
        },
        {
          type: "exercise",
          prompt: "**A beer for me and a coffee for you, please.**",
          answer: "Едно пиво за мене и едно кафе за тебе, Ве молам",
          accept: ["пиво за мене и кафе за тебе, ве молам", "едно пиво за мене и едно кафе за тебе, молам"],
          hint: "Едно пиво за мене + и + едно кафе за тебе, + Ве молам.",
          after: "Both long pronouns in one sentence - за мене, за тебе. Same slot, different person.",
          reviews: ["numbers-1-5", "пиво", "за-for", "strong-pronouns", "и-conjunction", "ве молам"],
        },
        {
          type: "note",
          title: "него and неа - him and her",
          body:
            "Го and ја grow long forms too:\n\n- **него** - him\n- **неа** - her\n\n**Кафето е за него, а пивото е за неа.** - The coffee is for him, and the beer is for her.\n\nThey also follow **со**: **со него** (with him), **со неа** (with her).",
          speak: ["Кафето е за него, а пивото е за неа.", "со него, со неа"],
          ru: "Него/неа are Russian него/неё - the same forms Russian uses after a preposition.",
        },
        {
          type: "exercise",
          prompt: "**The coffee is for her.**",
          answer: "Кафето е за неа",
          hint: "кафето + е + за неа.",
          after: "За неа - ја went long. The pattern is holding.",
          reviews: ["definite-neuter", "сум-present", "за-for", "strong-pronouns"],
        },
        {
          type: "exercise",
          prompt: "**I'm going to Ohrid with him.**",
          answer: "Одам во Охрид со него",
          accept: ["со него одам во охрид", "јас одам во охрид со него"],
          hint: "одам + во Охрид + со него.",
          after: "Со works like за - it wants the long form, so го became него.",
          reviews: ["одам", "во-in", "со-with", "strong-pronouns"],
        },
        {
          type: "note",
          title: "до - next to",
          body:
            "**До** = next to (also 'until' - but 'next to' comes up first at a table).\n\n**Таа е до мене.** - She is next to me.",
          speak: ["Таа е до мене."],
          introduces: ["до-next-to"],
          ru: "Russian до is only 'until'. Macedonian до is also 'next to' - the meaning you'll use at a cafe.",
        },
        {
          type: "exercise",
          prompt: "**She is next to me.**",
          answer: "Таа е до мене",
          hint: "Таа е до + мене (long form).",
          after: "До + мене - the same long pronoun за taught you, now behind a different preposition.",
          reviews: ["pronoun-subject", "сум-present", "до-next-to", "strong-pronouns"],
        },
        {
          type: "exercise",
          prompt: "**Who is next to you?**",
          answer: "Кој е до тебе?",
          hint: "кој (who) + е + до тебе.",
          reviews: ["кој-who", "сум-present", "до-next-to", "strong-pronouns"],
        },
        {
          type: "note",
          title: "нас, вас, нив - us, you all, them",
          body:
            "The plural long forms:\n\n- **нас** - us\n- **вас** - you all\n- **нив** - them\n\n**Ова е за нас.** - This is for us.\n**Две кафиња за вас.** - Two coffees for you.",
          speak: ["Ова е за нас.", "Две кафиња за вас."],
          ru: "Нас and вас are identical to Russian; нив is Russian них with the final х turned into в.",
        },
        {
          type: "exercise",
          prompt: "**This is for us.**",
          answer: "Ова е за нас",
          hint: "Ова е за + нас.",
          reviews: ["ова-this", "сум-present", "за-for", "strong-pronouns"],
        },
        {
          type: "exercise",
          prompt: "**The beers are for them.**",
          answer: "Пивата се за нив",
          hint: "пивата (the beers) + се + за нив.",
          after: "Пивата се - plural noun, plural се. За нив closes it.",
          reviews: ["пиво", "noun-plural-basic", "сум-present", "за-for", "strong-pronouns"],
        },
        {
          type: "note",
          title: "извинете - excuse me",
          body:
            "**Извинете** = excuse me (polite). The word that opens every interaction with a stranger.\n\nIt's the polite form - use it as-is. To a friend you'd say **извини**.",
          speak: ["Извинете!"],
          ru: "Извините without the soft sign - same word, same job.",
        },
        {
          type: "exercise",
          prompt: "Get a waiter's attention: **Excuse me, can I get two coffees, please?**",
          answer: "Извинете, може ли две кафиња, Ве молам?",
          hint: "Извинете, + може ли + две кафиња, + Ве молам.",
          after: "Извинете opens the door, може ли asks politely, Ве молам closes with warmth. Three moves of courtesy in one sentence.",
          reviews: ["извинете", "може-ли-polite", "numbers-1-5", "noun-plural-basic", "ве молам"],
        },
        {
          type: "exercise",
          prompt: "**Excuse me, how much does this cost?**",
          answer: "Извинете, колку чини ова?",
          hint: "Извинете, + колку чини + ова.",
          reviews: ["извинете", "колку-how-much", "чини", "ова-this"],
        },
        {
          type: "note",
          title: "повелете - here you go",
          body:
            "**Повелете** = here you go. The waiter says it when bringing your order. It can also mean 'come in', 'go ahead', 'after you', or 'what would you like?' when they come to your table - a Swiss Army knife of Macedonian hospitality.\n\nYou won't say it much yourself - but you'll hear it dozens of times a day.",
          speak: ["Повелете."],
          bg: "Bulgarian заповядайте is a different word; in Macedonia you'll hear повелете in every one of those situations.",
        },
        {
          type: "choice",
          prompt: "The waiter brings your coffee and says **Повелете.** This means:",
          options: ["Here you go.", "What would you like?", "How much is it?"],
          correct: 0,
          after: "**Повелете** - you'll hear it dozens of times a day in Macedonia. It always means something generous.",
          reviews: ["повелете"],
        },
        {
          type: "exercise",
          prompt: "**Excuse me, is there tea?**",
          answer: "Извинете, има ли чај?",
          accept: ["извинете, дали има чај"],
          hint: "извинете + има ли (is there) + чај.",
          after: "Има ли чај - the existential има from Module 2, with ли riding on it.",
          reviews: ["извинете", "има-existential", "ли-question", "чај"],
        },
        {
          type: "note",
          title: "The whole scene",
          body:
            "Read it once, then you'll play both parts.\n\n- **Извинете, може ли едно кафе и една вода, Ве молам?**\n- **Повелете.**\n- **Благодарам. Колку чини?**\n- **Ја сакате сметката?** - You want the bill?\n- **Да, ја сакам сметката, Ве молам.**\n- **Повелете.**\n- **Благодарам, довидување!**\n\nNotice **ја сакам сметката** - the bill is definite, so it gets doubled, exactly as in Module 4.",
          speak: ["Извинете, може ли едно кафе и една вода, Ве молам?", "Повелете.", "Ја сакам сметката, Ве молам."],
          reviews: ["clitic-doubling", "може-ли-polite", "повелете"],
        },
        {
          type: "exercise",
          prompt: "Your first line: **Excuse me, can I get one coffee and one water, please?**",
          answer: "Извинете, може ли едно кафе и една вода, Ве молам?",
          hint: "Извинете + може ли + едно кафе и една вода + Ве молам.",
          after: "Едно for neuter кафе, една for feminine вода - the gender work from last lesson, now at a real table.",
          reviews: ["извинете", "може-ли-polite", "numbers-1-5", "noun-gender", "ве молам"],
        },
        {
          type: "exercise",
          prompt: "Ask for the bill: **I want the bill, please.**",
          answer: "Ја сакам сметката, Ве молам",
          accept: ["сакам ја сметката, ве молам"],
          hint: "The bill is definite - ја before сакам, then сметката.",
          after: "Ја сакам сметката - the doubling that makes a sentence sound Macedonian, at the moment it matters most.",
          reviews: ["clitic-doubling", "object-pronoun-sg", "сметка", "definite-fem", "ве молам"],
        },
        {
          type: "exercise",
          prompt: "Close the scene: **Thank you, goodbye!**",
          answer: "Благодарам, довидување!",
          accept: ["фала, довидување"],
          hint: "Благодарам + довидување.",
          after: "You just lived a complete cafe scene in Macedonian. Извинете, може ли, Ве молам, повелете, колку чини, сметката, благодарам - one real interaction. You're ready for Skopje.",
          reviews: ["благодарам", "довидување"],
        },
        {
          type: "exercise",
          prompt: "**Excuse me, I want three beers for us, please.**",
          answer: "Извинете, сакам три пива за нас, Ве молам",
          accept: ["извинете, сакам три пива за нас, молам"],
          hint: "извинете + сакам + три пива + за нас + Ве молам.",
          reviews: ["извинете", "сакам", "numbers-1-5", "пиво", "noun-plural-basic", "за-for", "strong-pronouns", "ве молам"],
        },
        {
          type: "exercise",
          prompt: "The waiter's line: **Here you go! Two coffees for you.**",
          answer: "Повелете! Две кафиња за вас.",
          hint: "повелете + две кафиња + за вас.",
          reviews: ["повелете", "numbers-1-5", "noun-plural-basic", "за-for", "strong-pronouns"],
        },
      ],
    },
  ],
};
